Repository envoyproxy/envoy, pull requests merged in 2019-12, with the labels that each got.

#9131 repokitteh: pin modules to git SHAs.
  repokitteh.star
Labels: rk:blessed

#8872 build: initialize const vector explicitly
  source/common/http/async_client_impl.h
Labels: waiting

#9046 udp proxy: complete MVP
  api/docs/BUILD
  api/envoy/config/filter/udp/udp_proxy/v2alpha/udp_proxy.proto
  docs/root/api-v2/config/filter/filter.rst
  docs/root/api-v2/config/filter/udp/udp.rst
  docs/root/configuration/listeners/listeners.rst
  docs/root/configuration/listeners/udp_filters/udp_filters.rst
  docs/root/configuration/listeners/udp_filters/udp_proxy.rst
  docs/root/intro/arch_overview/listeners/listeners.rst
  docs/root/intro/arch_overview/listeners/listeners_toc.rst
  docs/root/intro/arch_overview/listeners/udp_proxy.rst
  docs/root/intro/version_history.rst
  include/envoy/upstream/resource_manager.h
  source/extensions/extensions_build_config.bzl
  source/extensions/filters/udp/udp_proxy/BUILD
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
  test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
Labels: api

#8606 Ensure Redis Proxy can follow redirection when doing request mirroring
  docs/root/intro/version_history.rst
  source/extensions/clusters/redis/redis_cluster.h
  source/extensions/filters/network/common/redis/client.h
  source/extensions/filters/network/common/redis/client_impl.cc
  source/extensions/filters/network/common/redis/client_impl.h
  source/extensions/filters/network/common/redis/utility.cc
  source/extensions/filters/network/common/redis/utility.h
  source/extensions/filters/network/redis_proxy/command_splitter_impl.cc
  source/extensions/filters/network/redis_proxy/command_splitter_impl.h
  source/extensions/filters/network/redis_proxy/conn_pool.h
  source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
  source/extensions/filters/network/redis_proxy/conn_pool_impl.h
  source/extensions/health_checkers/redis/redis.cc
  source/extensions/health_checkers/redis/redis.h
  test/extensions/clusters/redis/redis_cluster_test.cc
  test/extensions/filters/network/common/redis/client_impl_test.cc
  test/extensions/filters/network/common/redis/mocks.cc
  test/extensions/filters/network/common/redis/mocks.h
  test/extensions/filters/network/redis_proxy/command_split_speed_test.cc
  test/extensions/filters/network/redis_proxy/command_splitter_impl_test.cc
  test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
  test/extensions/filters/network/redis_proxy/mocks.cc
  test/extensions/filters/network/redis_proxy/mocks.h
  test/extensions/health_checkers/redis/redis_test.cc
Labels: no stalebot

#9277 fix merge race
  api/envoy/api/v3alpha/route/route.proto
Labels: api

#9276 api: add type database rule and use it from protoxform
  tools/api_proto_plugin/BUILD
  tools/api_proto_plugin/plugin.bzl
  tools/api_proto_plugin/plugin.py
  tools/proto_format.sh
  tools/protodoc/protodoc.py
  tools/protoxform/migrate.py
  tools/protoxform/protoxform.bzl
  tools/protoxform/protoxform.py
  tools/protoxform/utils.py
  tools/type_whisperer/type_database.bzl
  tools/type_whisperer/type_whisperer.py
  tools/type_whisperer/typedb_gen.py
Labels: api

#9175 api: include v1alpha1 in proto_sync.py
  tools/proto_sync.py
  tools/type_whisperer/typedb_gen.py
Labels: api

#9303 Correct trie test by comparing string contents
  test/common/common/utility_test.cc
Labels: waiting

#7415 Vhds readme
  .gitattributes
  api/envoy/api/v2/discovery.proto
  api/envoy/api/v2/rds.proto
  api/envoy/api/v3alpha/discovery.proto
  api/envoy/api/v3alpha/rds.proto
  api/xds_protocol.rst
  docs/root/configuration/http/http_conn_man/http_conn_man.rst
  docs/root/configuration/http/http_conn_man/rds.rst
  docs/root/configuration/http/http_conn_man/vhds.rst
  docs/root/intro/arch_overview/operations/dynamic_configuration.rst
Labels: no stalebot

#9209 xds: share rds configuration among envoy 2/2
  include/envoy/config/config_provider.h
  include/envoy/router/rds.h
  include/envoy/router/route_config_provider_manager.h
  source/common/router/rds_impl.cc
  source/common/router/rds_impl.h
  source/common/router/scoped_rds.cc
  source/common/router/scoped_rds.h
  source/extensions/filters/network/http_connection_manager/config.h
  test/common/router/rds_impl_test.cc
  test/common/router/scoped_rds_test.cc
  test/mocks/router/mocks.h
Labels: waiting

#8667 http1 encode trailers in chunk encoding
  api/envoy/api/v2/core/protocol.proto
  api/envoy/api/v3alpha/core/protocol.proto
  docs/root/intro/version_history.rst
  include/envoy/http/codec.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/codec_impl.h
  source/common/http/utility.cc
  source/extensions/filters/http/grpc_http1_reverse_bridge/filter.cc
  source/extensions/filters/http/grpc_http1_reverse_bridge/filter.h
  source/extensions/filters/http/grpc_web/grpc_web_filter.cc
  test/common/http/http1/codec_impl_test.cc
  test/extensions/filters/http/grpc_http1_reverse_bridge/reverse_bridge_integration_test.cc
  test/extensions/filters/http/grpc_http1_reverse_bridge/reverse_bridge_test.cc
  test/extensions/filters/http/grpc_web/BUILD
  test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc
  test/extensions/filters/http/grpc_web/grpc_web_filter_test.cc
  test/integration/autonomous_upstream.cc
  test/integration/autonomous_upstream.h
  test/integration/fake_upstream.cc
  test/integration/http2_integration_test.cc
  test/integration/http2_upstream_integration_test.cc
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/integration.cc
  test/integration/integration.h
  test/integration/integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/transport_socket_match_integration_test.cc
Labels: no stalebot

#9480 build: add API_NO_BOOST* annotations.
  source/common/config/BUILD
  source/common/config/api_version.h
  source/common/config/type_to_endpoint.cc
  source/common/router/BUILD
  source/common/router/rds_impl.cc
  source/common/router/scoped_rds.cc
  source/common/router/vhds.cc
  source/common/runtime/BUILD
  source/common/runtime/runtime_impl.cc
  source/common/secret/BUILD
  source/common/secret/sds_api.cc
  source/common/upstream/BUILD
  source/common/upstream/cds_api_impl.cc
  source/common/upstream/eds.cc
  source/server/BUILD
  source/server/lds_api.cc
  test/common/config/BUILD
  test/common/config/delta_subscription_impl_test.cc
  test/common/config/grpc_mux_impl_test.cc
  test/common/config/grpc_subscription_test_harness.h
  test/common/router/BUILD
  test/common/router/scoped_rds_test.cc
  test/integration/BUILD
  test/integration/header_integration_test.cc
  test/integration/integration.cc
  test/integration/integration.h
  test/integration/scoped_rds_integration_test.cc
  test/integration/sds_dynamic_integration_test.cc
  test/integration/tcp_proxy_integration_test.cc
  tools/api_boost/api_boost.py
  tools/api_boost/api_boost_test.py
  tools/api_boost/testdata/BUILD
  tools/api_boost/testdata/decl_ref_expr.cc
  tools/api_boost/testdata/decl_ref_expr.cc.gold
  tools/api_boost/testdata/no_boost_file.cc
  tools/api_boost/testdata/no_boost_file.cc.gold
  tools/clang_tools/api_booster/main.cc
  tools/type_whisperer/api_type_db.cc
  tools/type_whisperer/api_type_db.h
Labels: api/v3

#9498 listener: use typed config for transport socket conversion.
  source/server/listener_manager_impl.cc
Labels: api/v3

#9354 rate limit: add local rate limit network filter
  CODEOWNERS
  api/BUILD
  api/docs/BUILD
  api/envoy/api/v2/route/route.proto
  api/envoy/api/v3alpha/route/route.proto
  api/envoy/config/filter/network/local_rate_limit/v2alpha/BUILD
  api/envoy/config/filter/network/local_rate_limit/v2alpha/local_rate_limit.proto
  api/envoy/config/filter/network/local_rate_limit/v3alpha/BUILD
  api/envoy/config/filter/network/local_rate_limit/v3alpha/local_rate_limit.proto
  api/envoy/type/token_bucket.proto
  api/envoy/type/v3alpha/token_bucket.proto
  docs/root/api-v2/config/filter/network/network.rst
  docs/root/api-v2/types/types.rst
  docs/root/configuration/http/http_filters/rate_limit_filter.rst
  docs/root/configuration/listeners/network_filters/local_rate_limit_filter.rst
  docs/root/configuration/listeners/network_filters/network_filters.rst
  docs/root/configuration/listeners/network_filters/rate_limit_filter.rst
  docs/root/configuration/other_features/rate_limit.rst
  docs/root/configuration/other_protocols/thrift_filters/rate_limit_filter.rst
  docs/root/faq/load_balancing/transient_failures.rst
  docs/root/install/ref_configs.rst
  docs/root/intro/arch_overview/listeners/listener_filters.rst
  docs/root/intro/arch_overview/listeners/listeners.rst
  docs/root/intro/arch_overview/listeners/network_filters.rst
  docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
  docs/root/intro/arch_overview/other_features/local_rate_limiting.rst
  docs/root/intro/arch_overview/other_features/other_features.rst
  docs/root/intro/version_history.rst
  docs/root/intro/what_is_envoy.rst
  generated_api_shadow/BUILD
  generated_api_shadow/envoy/admin/v2alpha/clusters.proto
  generated_api_shadow/envoy/admin/v3alpha/clusters.proto
  generated_api_shadow/envoy/api/v2/cds.proto
  generated_api_shadow/envoy/api/v2/core/config_source.proto
  generated_api_shadow/envoy/api/v2/route/route.proto
  generated_api_shadow/envoy/api/v3alpha/cds.proto
  generated_api_shadow/envoy/api/v3alpha/core/config_source.proto
  generated_api_shadow/envoy/api/v3alpha/route/route.proto
  generated_api_shadow/envoy/config/filter/network/local_rate_limit/v2alpha/BUILD
  generated_api_shadow/envoy/config/filter/network/local_rate_limit/v2alpha/local_rate_limit.proto
  generated_api_shadow/envoy/config/filter/network/local_rate_limit/v3alpha/BUILD
  generated_api_shadow/envoy/config/filter/network/local_rate_limit/v3alpha/local_rate_limit.proto
  generated_api_shadow/envoy/type/token_bucket.proto
  generated_api_shadow/envoy/type/v3alpha/token_bucket.proto
  source/common/common/BUILD
  source/common/common/thread_synchronizer.cc
  source/common/common/thread_synchronizer.h
  source/extensions/extensions_build_config.bzl
  source/extensions/filters/network/local_ratelimit/BUILD
  source/extensions/filters/network/local_ratelimit/config.cc
  source/extensions/filters/network/local_ratelimit/config.h
  source/extensions/filters/network/local_ratelimit/local_ratelimit.cc
  source/extensions/filters/network/local_ratelimit/local_ratelimit.h
  source/extensions/filters/network/well_known_names.h
  test/config/utility.cc
  test/config/utility.h
  test/extensions/filters/network/local_ratelimit/BUILD
  test/extensions/filters/network/local_ratelimit/local_ratelimit_integration_test.cc
  test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc
  tools/spelling_dictionary.txt
Labels: api

#9468 api: xDS API version specifier
  api/envoy/api/v2/core/config_source.proto
  api/envoy/api/v3alpha/core/config_source.proto
  generated_api_shadow/envoy/api/v2/core/config_source.proto
  generated_api_shadow/envoy/api/v3alpha/core/config_source.proto
  source/common/router/BUILD
  source/common/router/rds_impl.cc
  source/common/router/rds_impl.h
  source/common/router/scoped_rds.cc
  source/common/router/scoped_rds.h
  source/common/router/vhds.cc
  source/common/router/vhds.h
  source/common/runtime/BUILD
  source/common/runtime/runtime_impl.cc
  source/common/runtime/runtime_impl.h
  source/common/secret/sds_api.cc
  source/common/secret/sds_api.h
  source/common/upstream/BUILD
  source/common/upstream/cds_api_impl.cc
  source/common/upstream/cds_api_impl.h
  source/common/upstream/eds.cc
  source/common/upstream/eds.h
  source/server/BUILD
  source/server/lds_api.cc
  source/server/lds_api.h
  tools/spelling_dictionary.txt
Labels: api/v3

#9519 ci: fix Windows target broken by #9429.
  .gitattributes
  ci/windows_ci_steps.sh
  generated_api_shadow/bazel
  generated_api_shadow/bazel/BUILD
  generated_api_shadow/bazel/api_build_system.bzl
  generated_api_shadow/bazel/envoy_http_archive.bzl
  generated_api_shadow/bazel/external_proto_deps.bzl
  generated_api_shadow/bazel/repositories.bzl
  generated_api_shadow/bazel/repository_locations.bzl
  tools/proto_format.sh
Labels: api/v3
