Repository envoyproxy/envoy, pull requests merged in 2020-11, with the labels that each got.

#13773 jwt_authn: Support per-route config
  api/envoy/extensions/filters/http/jwt_authn/v3/config.proto
  api/envoy/extensions/filters/http/jwt_authn/v4alpha/config.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/http/jwt_authn/v3/config.proto
  generated_api_shadow/envoy/extensions/filters/http/jwt_authn/v4alpha/config.proto
  source/extensions/filters/http/jwt_authn/filter.cc
  source/extensions/filters/http/jwt_authn/filter_config.cc
  source/extensions/filters/http/jwt_authn/filter_config.h
  source/extensions/filters/http/jwt_authn/filter_factory.cc
  source/extensions/filters/http/jwt_authn/filter_factory.h
  test/extensions/filters/http/jwt_authn/filter_config_test.cc
  test/extensions/filters/http/jwt_authn/filter_factory_test.cc
  test/extensions/filters/http/jwt_authn/filter_integration_test.cc
  test/extensions/filters/http/jwt_authn/filter_test.cc
Labels: waiting

#13837 [Windows] Address status/fix various flaky_on_windows tests
  test/common/network/listener_impl_test.cc
  test/extensions/filters/http/ratelimit/BUILD
  test/extensions/grpc_credentials/file_based_metadata/BUILD
  test/extensions/grpc_credentials/file_based_metadata/integration_test.cc
  test/extensions/quic_listeners/quiche/integration/BUILD
  test/extensions/quic_listeners/quiche/integration/quic_http_integration_test.cc
  test/extensions/stats_sinks/metrics_service/BUILD
  test/extensions/transport_sockets/alts/BUILD
  test/integration/BUILD
  test/server/BUILD
Labels: area/build, area/test flakes, area/windows

#13768 proxy_proto: fixing hashing bug
  docs/root/version_history/current.rst
  include/envoy/network/proxy_protocol.h
  include/envoy/network/transport_socket.h
  source/common/network/raw_buffer_socket.h
  source/common/network/transport_socket_options_impl.cc
  source/common/network/transport_socket_options_impl.h
  source/common/upstream/cluster_manager_impl.cc
  source/extensions/quic_listeners/quiche/quic_transport_socket_factory.h
  source/extensions/transport_sockets/alts/tsi_socket.h
  source/extensions/transport_sockets/proxy_protocol/proxy_protocol.h
  source/extensions/transport_sockets/tap/tap.cc
  source/extensions/transport_sockets/tap/tap.h
  source/extensions/transport_sockets/tls/ssl_socket.h
  test/common/network/BUILD
  test/common/network/raw_buffer_socket_test.cc
  test/common/upstream/transport_socket_matcher_test.cc
  test/extensions/transport_sockets/alts/tsi_socket_test.cc
  test/extensions/transport_sockets/proxy_protocol/proxy_protocol_integration_test.cc
  test/extensions/transport_sockets/tap/tap_config_impl_test.cc
  test/integration/base_integration_test.cc
  test/integration/base_integration_test.h
  test/integration/fake_upstream.h
  test/integration/integration_tcp_client.cc
  test/integration/integration_tcp_client.h
  test/mocks/network/transport_socket.h
Labels: backport/review

#13957 update grpc-httpjson-transcoding to support custom verb
  bazel/repository_locations.bzl
Labels: deps

#13930 wasm: Force stop iteration after local response is sent
  bazel/repository_locations.bzl
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: deps

#13585 router: call chargeStats() in recreateStream() when handling internal redirects
  include/envoy/http/filter.h
  source/common/http/async_client_impl.h
  source/common/http/conn_manager_impl.cc
  source/common/http/conn_manager_impl.h
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/router/router.cc
  source/extensions/filters/http/on_demand/on_demand_update.cc
  test/common/http/conn_manager_impl_test_2.cc
  test/common/router/router_test.cc
  test/extensions/filters/http/on_demand/on_demand_filter_test.cc
  test/integration/redirect_integration_test.cc
  test/mocks/http/mocks.h
Labels: api, deps, v2-freeze

#13753 wasm: allow execution of multiple instances of the same plugin.
  bazel/repository_locations.bzl
  source/extensions/access_loggers/wasm/config.cc
  source/extensions/access_loggers/wasm/wasm_access_log_impl.h
  source/extensions/bootstrap/wasm/config.cc
  source/extensions/bootstrap/wasm/config.h
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/common/wasm/wasm_extension.cc
  source/extensions/common/wasm/wasm_extension.h
  source/extensions/filters/http/wasm/wasm_filter.cc
  source/extensions/filters/http/wasm/wasm_filter.h
  source/extensions/filters/network/wasm/wasm_filter.cc
  source/extensions/filters/network/wasm/wasm_filter.h
  source/extensions/stat_sinks/wasm/config.cc
  source/extensions/stat_sinks/wasm/wasm_stat_sink_impl.h
  test/extensions/bootstrap/wasm/test_data/logging_cpp.cc
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/test_data/test_cpp.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/filters/network/wasm/config_test.cc
  test/extensions/filters/network/wasm/wasm_filter_test.cc
  test/test_common/wasm_base.h
Labels: deps

#13958 1.13: backport ci fixes
  .azure-pipelines/bazel.yml
  .azure-pipelines/cleanup.sh
  .azure-pipelines/pipelines.yml
  .circleci/config.yml
  bazel/envoy_internal.bzl
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  ci/api_mirror.sh
  ci/do_ci.sh
  ci/filter_example_mirror.sh
  ci/go_mirror.sh
  ci/mac_ci_setup.sh
  ci/run_envoy_docker.sh
  ci/setup_cache.sh
  ci/upload_gcs_artifact.sh
  docs/build.sh
  docs/publish.sh
  test/extensions/quic_listeners/quiche/platform/quic_platform_test.cc
  test/integration/cx_limit_integration_test.cc
  tools/api/generate_go_protobuf.py
  tools/api_boost/api_boost.py
Labels: deps

#13840 wasm: fix order of callbacks for paused requests.
  bazel/external/cargo/Cargo.toml
  bazel/repository_locations.bzl
  source/extensions/common/wasm/context.cc
  test/extensions/filters/http/wasm/BUILD
  test/extensions/filters/http/wasm/test_data/BUILD
  test/extensions/filters/http/wasm/test_data/resume_call_rust.rs
  test/extensions/filters/http/wasm/test_data/test_resume_call_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: deps

#14031 config: fix crash when type URL doesn't match proto.
  source/common/config/version_converter.cc
  test/common/config/version_converter_test.cc
  test/integration/ads_integration_test.cc
Labels: waiting

#14014 wasm: use static registration for runtimes
  CODEOWNERS
  api/envoy/extensions/wasm/v3/wasm.proto
  bazel/repository_locations.bzl
  generated_api_shadow/envoy/extensions/wasm/v3/wasm.proto
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm_runtime_factory.h
  source/extensions/common/wasm/wasm_vm.cc
  source/extensions/extensions_build_config.bzl
  source/extensions/wasm_runtime/null/BUILD
  source/extensions/wasm_runtime/null/config.cc
  source/extensions/wasm_runtime/v8/BUILD
  source/extensions/wasm_runtime/v8/config.cc
  source/extensions/wasm_runtime/wasmtime/BUILD
  source/extensions/wasm_runtime/wasmtime/config.cc
  source/extensions/wasm_runtime/wavm/BUILD
  source/extensions/wasm_runtime/wavm/config.cc
  test/extensions/access_loggers/wasm/BUILD
  test/extensions/access_loggers/wasm/config_test.cc
  test/extensions/bootstrap/wasm/BUILD
  test/extensions/bootstrap/wasm/config_test.cc
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/BUILD
  test/extensions/common/wasm/wasm_runtime.cc
  test/extensions/common/wasm/wasm_runtime.h
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/http/wasm/BUILD
  test/extensions/filters/http/wasm/config_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/extensions/filters/network/wasm/BUILD
  test/extensions/filters/network/wasm/config_test.cc
  test/extensions/filters/network/wasm/wasm_filter_test.cc
  test/extensions/stats_sinks/wasm/BUILD
  test/extensions/stats_sinks/wasm/config_test.cc
  test/extensions/stats_sinks/wasm/wasm_stat_sink_test.cc
  test/per_file_coverage.sh
Labels: deps

#14062 wasm: make dependency clearer
  bazel/external/proxy_wasm_cpp_host.BUILD
  bazel/repository_locations.bzl
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/wasm_runtime_factory.h
  source/extensions/wasm_runtime/null/BUILD
  source/extensions/wasm_runtime/v8/BUILD
  source/extensions/wasm_runtime/wasmtime/BUILD
  source/extensions/wasm_runtime/wavm/BUILD
Labels: deps

#14066 vrp: allow supervisord to open its log file
  ci/Dockerfile-envoy-google-vrp
  configs/google-vrp/supervisor.conf
Labels: backport/approved

#14103 test: fix use after free in oauth_integration_test
  test/extensions/filters/http/oauth2/oauth_integration_test.cc
Labels: backport/approved

#14092 lua: reset downstream_ssl_connection in StreamInfoWrapper when object is marked dead by Lua GC
  source/extensions/filters/http/lua/wrappers.h
  test/extensions/filters/http/lua/lua_filter_test.cc
Labels: backport/review

#13960 perf: add annotations for non-concurrent cross-scoped duration measurements
  source/common/common/perf_annotation.h
  test/common/common/perf_annotation_disabled_test.cc
  test/common/common/perf_annotation_test.cc
Labels: waiting

#13220 [Windows] Fix thrift proxy tests
  test/extensions/filters/network/thrift_proxy/BUILD
  test/extensions/filters/network/thrift_proxy/driver/BUILD
  test/extensions/filters/network/thrift_proxy/driver/client.py
  test/extensions/filters/network/thrift_proxy/driver/generate_fixture.sh
  test/extensions/filters/network/thrift_proxy/driver/server.py
  test/extensions/filters/network/thrift_proxy/integration.cc
  test/extensions/filters/network/thrift_proxy/integration_test.cc
Labels: area/thrift, area/windows

#14185 repokitteh: add support for randomized auto-assign.
  ci/repokitteh/modules/ownerscheck.star
  repokitteh.star
Labels: api, rk:blessed

#13592 thrift filter: support skip decoding data after metadata in the thrift message
  api/envoy/extensions/filters/network/thrift_proxy/v3/thrift_proxy.proto
  api/envoy/extensions/filters/network/thrift_proxy/v4alpha/thrift_proxy.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/network/thrift_proxy/v3/thrift_proxy.proto
  generated_api_shadow/envoy/extensions/filters/network/thrift_proxy/v4alpha/thrift_proxy.proto
  source/extensions/filters/network/thrift_proxy/config.cc
  source/extensions/filters/network/thrift_proxy/config.h
  source/extensions/filters/network/thrift_proxy/conn_manager.cc
  source/extensions/filters/network/thrift_proxy/conn_manager.h
  source/extensions/filters/network/thrift_proxy/decoder.cc
  source/extensions/filters/network/thrift_proxy/decoder.h
  source/extensions/filters/network/thrift_proxy/decoder_events.h
  source/extensions/filters/network/thrift_proxy/filters/filter.h
  source/extensions/filters/network/thrift_proxy/filters/pass_through_filter.h
  source/extensions/filters/network/thrift_proxy/protocol_converter.h
  source/extensions/filters/network/thrift_proxy/router/router_impl.cc
  source/extensions/filters/network/thrift_proxy/router/router_impl.h
  source/extensions/filters/network/thrift_proxy/thrift_object_impl.h
  test/config/utility.cc
  test/config/utility.h
  test/extensions/filters/network/thrift_proxy/BUILD
  test/extensions/filters/network/thrift_proxy/config_test.cc
  test/extensions/filters/network/thrift_proxy/conn_manager_test.cc
  test/extensions/filters/network/thrift_proxy/decoder_test.cc
  test/extensions/filters/network/thrift_proxy/integration_test.cc
  test/extensions/filters/network/thrift_proxy/mocks.h
  test/extensions/filters/network/thrift_proxy/router_test.cc
Labels: v2-freeze

#14216 dependencies: fix release_dates error behavior.
  bazel/repository_locations.bzl
  tools/dependency/release_dates.py
Labels: deps
