Repository envoyproxy/envoy, pull requests merged in 2020-05, with the labels that each got.

#10531 http: max stream duration upstream support
  api/envoy/api/v2/core/protocol.proto
  api/envoy/config/accesslog/v3/accesslog.proto
  api/envoy/config/accesslog/v4alpha/accesslog.proto
  api/envoy/config/core/v3/protocol.proto
  api/envoy/config/core/v4alpha/protocol.proto
  api/envoy/data/accesslog/v3/accesslog.proto
  clang-tidy-fixes.yaml
  docs/root/configuration/observability/access_log/usage.rst
  docs/root/configuration/upstream/cluster_manager/cluster_stats.rst
  docs/root/faq/configuration/timeouts.rst
  generated_api_shadow/envoy/api/v2/core/protocol.proto
  generated_api_shadow/envoy/config/accesslog/v3/accesslog.proto
  generated_api_shadow/envoy/config/accesslog/v4alpha/accesslog.proto
  generated_api_shadow/envoy/config/core/v3/protocol.proto
  generated_api_shadow/envoy/config/core/v4alpha/protocol.proto
  generated_api_shadow/envoy/data/accesslog/v3/accesslog.proto
  include/envoy/stream_info/stream_info.h
  include/envoy/upstream/upstream.h
  source/common/router/router.cc
  source/common/router/router.h
  source/common/router/upstream_request.cc
  source/common/router/upstream_request.h
  source/common/stream_info/utility.cc
  source/common/stream_info/utility.h
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  test/common/access_log/access_log_impl_test.cc
  test/common/router/router_test.cc
  test/common/router/upstream_request_test.cc
  test/common/stream_info/utility_test.cc
  test/extensions/access_loggers/grpc/grpc_access_log_utils_test.cc
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/protocol_integration_test.cc
  test/integration/stats_integration_test.cc
  test/integration/tcp_tunneling_integration_test.cc
  test/mocks/upstream/cluster_info.cc
  test/mocks/upstream/cluster_info.h
Labels: no stalebot

#11090 ci: fork repokitteh ownerscheck.star.
  ci/repokitteh/modules/ownerscheck.star
  repokitteh.star
Labels: rk:blessed

#11092 ci: force /lgtm v2-freeze on any v2 API changes.
  ci/repokitteh/modules/ownerscheck.star
  repokitteh.star
Labels: rk:blessed

#11116 Revert "http: Introduce preserve_upstream_date option (#11077)"
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_impl.cc
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/server/http/admin.h
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/conn_manager_utility_test.cc
  test/extensions/filters/network/http_connection_manager/config_test.cc
Labels: api

#11122 ci: fix missing spec.owner in ownerscheck.star.
  ci/repokitteh/modules/ownerscheck.star
Labels: rk:blessed

#11143 ci: really fix spec.owner in ownerscheck.star.
  ci/repokitteh/modules/ownerscheck.star
Labels: rk:blessed

#11100 caching: fixing date header and response details
  api/envoy/config/accesslog/v3/accesslog.proto
  api/envoy/config/accesslog/v4alpha/accesslog.proto
  api/envoy/data/accesslog/v3/accesslog.proto
  generated_api_shadow/envoy/config/accesslog/v3/accesslog.proto
  generated_api_shadow/envoy/config/accesslog/v4alpha/accesslog.proto
  generated_api_shadow/envoy/data/accesslog/v3/accesslog.proto
  include/envoy/stream_info/stream_info.h
  source/common/http/conn_manager_impl.cc
  source/common/stream_info/utility.cc
  source/common/stream_info/utility.h
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  source/extensions/filters/http/cache/cache_filter.cc
  test/common/access_log/access_log_impl_test.cc
  test/common/stream_info/utility_test.cc
  test/config/utility.cc
  test/extensions/access_loggers/grpc/grpc_access_log_utils_test.cc
  test/extensions/filters/http/cache/cache_filter_integration_test.cc
  test/integration/integration.cc
  test/integration/integration.h
  test/integration/proxy_proto_integration_test.cc
Labels: api

#11128 util: refactor mechanism used for atomic creation of http code stat-names to a general utility
  source/common/common/BUILD
  source/common/common/thread.h
  source/common/http/codes.cc
  source/common/http/codes.h
  test/common/common/BUILD
  test/common/common/lock_guard_test.cc
  test/common/common/thread_test.cc
Labels: waiting

#11146 connect: docs and cleanup
  api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
  api/envoy/config/route/v3/route_components.proto
  api/envoy/config/route/v4alpha/route_components.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  docs/root/intro/arch_overview/http/upgrades.rst
  docs/root/version_history/current.rst
  docs/root/version_history/v1.4.0.rst
  generated_api_shadow/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
  generated_api_shadow/envoy/config/route/v3/route_components.proto
  generated_api_shadow/envoy/config/route/v4alpha/route_components.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  test/integration/protocol_integration_test.cc
Labels: v2-freeze

#11087 [admin] extract logs and profiler handlers to separate classes
  source/server/http/BUILD
  source/server/http/admin.cc
  source/server/http/admin.h
  source/server/http/logs_handler.cc
  source/server/http/logs_handler.h
  source/server/http/profiling_handler.cc
  source/server/http/profiling_handler.h
  test/server/http/BUILD
  test/server/http/admin_test.cc
  test/server/http/logs_handler_test.cc
  test/server/http/profiling_handler_test.cc
Labels: waiting

#11132 http conn man: default preserve_upstream_date to true, add runtime guard
  docs/root/version_history/current.rst
  source/common/http/conn_manager_impl.cc
  source/common/runtime/runtime_features.cc
  test/common/http/conn_manager_impl_test.cc
Labels: api
