Repository envoyproxy/envoy, pull requests merged in 2020-01, with the labels that each got.

#9520 tools: protoxform support for oneof field promotion.
  api/bazel/repository_locations.bzl
  generated_api_shadow/bazel/repository_locations.bzl
  tools/protoxform/migrate.py
  tools/protoxform_test_helper.py
  tools/testdata/protoxform/envoy/v2/BUILD
  tools/testdata/protoxform/envoy/v2/oneof.proto
  tools/testdata/protoxform/envoy/v2/oneof.proto.v2.gold
  tools/testdata/protoxform/envoy/v2/oneof.proto.v3alpha.envoy_internal.gold
  tools/testdata/protoxform/envoy/v2/oneof.proto.v3alpha.gold
  tools/testdata/protoxform/envoy/v2/package_move.proto.v3alpha.envoy_internal.gold
  tools/testdata/protoxform/envoy/v2/sample.proto.v3alpha.envoy_internal.gold
Labels: api/v3

#9502 config: shadow-based upgrading/downgrading for versioned messages.
  source/common/config/BUILD
  source/common/config/api_type_oracle.cc
  source/common/config/api_type_oracle.h
  source/common/config/utility.cc
  source/common/config/utility.h
  source/common/config/version_converter.cc
  source/common/config/version_converter.h
  source/common/protobuf/BUILD
  source/common/protobuf/utility.cc
  source/common/router/config_impl.cc
  source/common/upstream/cluster_factory_impl.h
  source/common/upstream/upstream_impl.cc
  source/extensions/filters/network/dubbo_proxy/config.cc
  test/common/config/BUILD
  test/common/config/api_type_oracle_test.cc
  test/common/config/delta_subscription_test_harness.h
  test/common/config/grpc_mux_impl_test.cc
  test/common/config/grpc_subscription_test_harness.h
  test/common/config/new_grpc_mux_impl_test.cc
  test/common/config/utility_test.cc
  test/common/config/version_converter_test.cc
  test/common/protobuf/BUILD
  test/common/protobuf/utility_test.cc
  test/extensions/clusters/aggregate/cluster_test.cc
  test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
  test/extensions/clusters/redis/redis_cluster_test.cc
  test/integration/BUILD
  test/integration/integration.h
  test/integration/scoped_rds_integration_test.cc
  test/integration/sds_dynamic_integration_test.cc
Labels: api/v3

#9510 tools: API boosting support for deprecations, misc.
  bazel/envoy_test.bzl
  tools/api_boost/api_boost.py
  tools/api_boost/api_boost_test.py
  tools/api_boost/testdata/BUILD
  tools/api_boost/testdata/decl_ref_expr.cc
  tools/api_boost/testdata/decl_ref_expr.cc.gold
  tools/api_boost/testdata/deprecate.cc
  tools/api_boost/testdata/deprecate.cc.gold
  tools/api_boost/testdata/elaborated_type.cc
  tools/api_boost/testdata/elaborated_type.cc.gold
  tools/api_boost/testdata/using_decl.cc
  tools/api_boost/testdata/using_decl.cc.gold
  tools/api_boost/testdata/validate.cc
  tools/api_boost/testdata/validate.cc.gold
  tools/check_format.py
  tools/check_spelling_pedantic.py
  tools/clang_tools/api_booster/main.cc
  tools/clang_tools/api_booster/proto_cxx_utils.cc
  tools/clang_tools/api_booster/proto_cxx_utils.h
  tools/clang_tools/api_booster/proto_cxx_utils_test.cc
  tools/testdata/check_format/proto_format.proto
  tools/testdata/check_format/proto_format.proto.gold
  tools/type_whisperer/api_type_db.cc
  tools/type_whisperer/api_type_db.h
Labels: api/v3

#9368 upstream: fix eds crash when changing priorities
  source/common/upstream/eds.cc
  test/common/upstream/eds_test.cc
  test/integration/eds_integration_test.cc
Labels: no stalebot

#9542 test: remove some API version asserts.
  test/config/utility.cc
  test/extensions/access_loggers/grpc/tcp_grpc_access_log_integration_test.cc
Labels: api/v3

#9545 protobuf: API boosting enhancements.
  source/common/protobuf/utility.cc
  test/common/protobuf/utility_test.cc
Labels: api/v3

#9544 test/tools: enhanced API_NO_BOOST annotations.
  test/common/secret/secret_manager_impl_test.cc
  tools/api_boost/testdata/BUILD
  tools/api_boost/testdata/decl_ref_expr.cc
  tools/api_boost/testdata/decl_ref_expr.cc.gold
  tools/clang_tools/api_booster/main.cc
  tools/spelling_dictionary.txt
Labels: api/v3

#9476 http: extract common connect timeout handling to base class
  source/common/http/BUILD
  source/common/http/conn_pool_base.cc
  source/common/http/conn_pool_base.h
  source/common/http/http1/conn_pool.cc
  source/common/http/http1/conn_pool.h
  source/common/http/http2/conn_pool.cc
  source/common/http/http2/conn_pool.h
  test/common/http/http1/conn_pool_test.cc
  test/common/http/http2/conn_pool_test.cc
Labels: no stalebot

#9526 config: distinct resource/transport API versions.
  api/envoy/api/v2/core/config_source.proto
  api/envoy/config/core/v3alpha/config_source.proto
  generated_api_shadow/envoy/api/v2/core/config_source.proto
  generated_api_shadow/envoy/config/core/v3alpha/config_source.proto
  source/common/config/BUILD
  source/common/config/delta_subscription_state.h
  source/common/config/grpc_mux_impl.h
  source/common/config/http_subscription_impl.cc
  source/common/config/http_subscription_impl.h
  source/common/config/new_grpc_mux_impl.h
  source/common/config/protobuf_link_hacks.h
  source/common/config/subscription_factory_impl.cc
  source/common/config/type_to_endpoint.cc
  source/common/config/type_to_endpoint.h
  source/common/router/rds_impl.cc
  source/common/router/rds_impl.h
  source/common/router/scoped_rds.cc
  source/common/router/scoped_rds.h
  source/common/router/vhds.cc
  source/common/router/vhds.h
  source/common/runtime/runtime_impl.cc
  source/common/runtime/runtime_impl.h
  source/common/secret/sds_api.cc
  source/common/secret/sds_api.h
  source/common/upstream/cds_api_impl.cc
  source/common/upstream/cds_api_impl.h
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/eds.cc
  source/common/upstream/eds.h
  source/server/lds_api.cc
  source/server/lds_api.h
  test/common/config/delta_subscription_test_harness.h
  test/common/config/http_subscription_test_harness.h
  test/integration/BUILD
  test/integration/README.md
  test/integration/api_version_integration_test.cc
  test/integration/cds_integration_test.cc
  test/integration/load_stats_integration_test.cc
Labels: api/v3

#9484 cleanup: Remove remaining use of the deprecated google.protobuf.Struct
  source/common/upstream/upstream_impl.cc
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/thrift_proxy/config.cc
  source/server/listener_manager_impl.cc
  test/common/tcp_proxy/tcp_proxy_test.cc
  test/config/utility.cc
  test/config/utility.h
  test/extensions/access_loggers/file/config_test.cc
  test/extensions/grpc_credentials/aws_iam/aws_iam_grpc_credentials_test.cc
  test/extensions/grpc_credentials/file_based_metadata/file_based_metadata_grpc_credentials_test.cc
  test/server/configuration_impl_test.cc
Labels: api/v3

#9633 config: support recovery of original message when upgrading.
  api/envoy/admin/v2alpha/BUILD
  api/envoy/admin/v2alpha/config_dump.proto
  api/envoy/admin/v3alpha/BUILD
  api/envoy/admin/v3alpha/config_dump.proto
  generated_api_shadow/envoy/admin/v2alpha/BUILD
  generated_api_shadow/envoy/admin/v2alpha/config_dump.proto
  generated_api_shadow/envoy/admin/v3alpha/BUILD
  generated_api_shadow/envoy/admin/v3alpha/config_dump.proto
  include/envoy/upstream/locality.h
  source/common/config/BUILD
  source/common/config/grpc_mux_impl.cc
  source/common/config/http_subscription_impl.cc
  source/common/config/new_grpc_mux_impl.cc
  source/common/config/version_converter.cc
  source/common/config/version_converter.h
  source/common/local_info/BUILD
  source/common/local_info/local_info_impl.h
  source/common/protobuf/BUILD
  source/common/protobuf/utility.cc
  source/common/protobuf/utility.h
  source/common/protobuf/well_known.h
  source/common/router/BUILD
  source/common/router/rds_impl.cc
  source/common/router/scoped_rds.cc
  source/common/secret/BUILD
  source/common/secret/secret_manager_impl.cc
  source/common/upstream/BUILD
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/eds.cc
  source/common/upstream/health_discovery_service.cc
  source/common/upstream/health_discovery_service.h
  source/common/upstream/load_stats_reporter.cc
  source/common/upstream/load_stats_reporter.h
  source/server/BUILD
  source/server/http/admin.cc
  source/server/listener_manager_impl.cc
  source/server/server.cc
  test/common/config/BUILD
  test/common/config/version_converter_test.cc
  test/common/protobuf/utility_test.cc
  test/common/router/rds_impl_test.cc
  test/common/router/scoped_rds_test.cc
  test/common/secret/secret_manager_impl_test.cc
  test/common/upstream/cluster_manager_impl_test.cc
  test/common/upstream/hds_test.cc
  test/common/upstream/load_stats_reporter_test.cc
  test/common/upstream/utility.h
  test/integration/BUILD
  test/integration/api_version_integration_test.cc
  test/integration/integration_admin_test.cc
  test/integration/stats_integration_test.cc
  test/proto/deprecated.proto
  test/server/http/admin_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/utility.h
  test/test_common/BUILD
  test/test_common/utility.h
  tools/check_format.py
Labels: api/v3

#9672 api: document annotations and how to add an extension config.
  api/API_VERSIONING.md
  api/STYLE.md
Labels: api/v3

#9663 api: deprecate hosts in Cluster.
  api/envoy/api/v2/cluster.proto
  api/envoy/config/cluster/v3alpha/cluster.proto
  examples/grpc-bridge/server/envoy-proxy.yaml
  generated_api_shadow/envoy/api/v2/cluster.proto
  generated_api_shadow/envoy/config/cluster/v3alpha/cluster.proto
  source/common/config/version_converter.cc
  source/common/upstream/health_discovery_service.cc
  source/common/upstream/logical_dns_cluster.cc
  source/common/upstream/original_dst_cluster.cc
  source/common/upstream/static_cluster.cc
  source/common/upstream/strict_dns_cluster.cc
  source/extensions/clusters/redis/redis_cluster.cc
  test/common/config/version_converter_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/config/integration/google_com_proxy_port_0.v2.yaml
  test/config/integration/server.yaml
  test/config/integration/server_unix_listener.yaml
  test/config/utility.cc
  test/config/utility.h
  test/extensions/clusters/aggregate/cluster_integration_test.cc
  test/extensions/clusters/redis/redis_cluster_integration_test.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
  test/integration/ads_integration.h
  test/integration/custom_cluster_integration_test.cc
  test/integration/eds_integration_test.cc
  test/integration/hds_integration_test.cc
  test/integration/header_integration_test.cc
  test/integration/http2_integration_test.cc
  test/integration/http_subset_lb_integration_test.cc
  test/integration/load_stats_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/proxy_proto_integration_test.cc
  test/integration/rtds_integration_test.cc
  test/integration/stats_integration_test.cc
  test/integration/transport_socket_match_integration_test.cc
  test/integration/uds_integration_test.h
  test/integration/vhds_integration_test.cc
  test/server/listener_manager_impl_quic_only_test.cc
  test/server/server_fuzz_test.cc
Labels: api/v3

#9706 config: API boosting for pb_text.
  source/common/protobuf/utility.cc
  test/common/protobuf/BUILD
  test/common/protobuf/utility_test.cc
  test/server/BUILD
  test/server/server_test.cc
  test/server/test_data/server/callbacks_stats_sink_bootstrap.yaml
  test/server/test_data/server/cluster_dupe_bootstrap.yaml
  test/server/test_data/server/cluster_health_check_bootstrap.yaml
  test/server/test_data/server/empty_bootstrap.yaml
  test/server/test_data/server/invalid_bootstrap.yaml
  test/server/test_data/server/invalid_layered_runtime_duplicate_name.yaml
  test/server/test_data/server/invalid_layered_runtime_missing_name.yaml
  test/server/test_data/server/invalid_layered_runtime_no_layer_specifier.yaml
  test/server/test_data/server/invalid_legacy_runtime_bootstrap.yaml
  test/server/test_data/server/invalid_runtime_bootstrap.yaml
  test/server/test_data/server/node_bootstrap.pb_text
  test/server/test_data/server/node_bootstrap.yaml
  test/server/test_data/server/node_bootstrap_no_admin_port.yaml
  test/server/test_data/server/node_bootstrap_with_admin_socket_options.yaml
  test/server/test_data/server/node_bootstrap_without_access_log.yaml
  test/server/test_data/server/proxy_version_bootstrap.yaml
  test/server/test_data/server/runtime_bootstrap.yaml
  test/server/test_data/server/stats_sink_bootstrap.yaml
  test/server/test_data/server/valid_v2_but_invalid_v3_bootstrap.pb_text
  test/server/test_data/server/zipkin_tracing.yaml
  test/test_common/environment.cc
Labels: api/v3

#9641 xds: fix upstream filter typed struct conversion
  source/common/upstream/upstream_impl.cc
Labels: api/v3, waiting

#9355 stats: add mechanism to create dynamic tokens without locks or sharing
  include/envoy/stats/symbol_table.h
  source/common/http/codes.cc
  source/common/http/codes.h
  source/common/router/router.cc
  source/common/router/router.h
  source/common/stats/fake_symbol_table_impl.h
  source/common/stats/symbol_table_impl.cc
  source/common/stats/symbol_table_impl.h
  source/docs/stats.md
  source/docs/symtab.png
  source/extensions/filters/http/dynamo/dynamo_filter.cc
  source/extensions/filters/http/dynamo/dynamo_stats.cc
  source/extensions/filters/http/dynamo/dynamo_stats.h
  source/extensions/filters/http/fault/fault_filter.cc
  source/extensions/filters/http/fault/fault_filter.h
  source/extensions/filters/http/ip_tagging/ip_tagging_filter.cc
  source/extensions/filters/network/mongo_proxy/mongo_stats.h
  source/extensions/filters/network/mongo_proxy/proxy.cc
  test/common/http/codes_test.cc
  test/common/stats/stat_test_utility.cc
  test/common/stats/symbol_table_fuzz_test.cc
  test/common/stats/symbol_table_impl_test.cc
  test/server/server_test.cc
Labels: no stalebot

#9257 Proxy-WASM ABI Part 1.
  include/abi/wasm/proxy_wasm_common.h
  include/abi/wasm/proxy_wasm_exports.h
  include/abi/wasm/proxy_wasm_imports.h
Labels: api
