Repository envoyproxy/envoy, pull requests merged in 2020-10, with the labels that each got.

#13305 access log: add CONNECTION_TERMINATION_DETAILS operator
  docs/root/configuration/http/http_filters/rbac_filter.rst
  docs/root/configuration/listeners/network_filters/rbac_filter.rst
  docs/root/configuration/observability/access_log/usage.rst
  docs/root/version_history/current.rst
  include/envoy/stream_info/stream_info.h
  source/common/formatter/substitution_formatter.cc
  source/common/stream_info/stream_info_impl.h
  source/extensions/filters/network/rbac/rbac_filter.cc
  source/extensions/filters/network/rbac/rbac_filter.h
  test/common/formatter/substitution_formatter_test.cc
  test/common/stream_info/stream_info_impl_test.cc
  test/common/stream_info/test_util.h
  test/extensions/filters/network/rbac/integration_test.cc
  test/mocks/stream_info/mocks.cc
  test/mocks/stream_info/mocks.h
Labels: api

#13439 docs: Move install section into getting started
  DEVELOPER.md
  bazel/README.md
  docs/redirects.txt
  docs/root/index.rst
  docs/root/install/install.rst
  docs/root/start/building.rst
  docs/root/start/install/ref_configs.rst
  docs/root/start/install/sandboxes/local_docker_build.rst
  docs/root/start/install/tools/config_load_check_tool.rst
  docs/root/start/install/tools/route_table_check_tool.rst
  docs/root/start/install/tools/schema_validator_check_tool.rst
  docs/root/start/install/tools/tools.rst
  docs/root/start/start.rst
Labels: waiting

#13374 Windows: Add CI for per-commit/release image build
  .azure-pipelines/pipelines.yml
  ci/Dockerfile-envoy-windows
  ci/docker-entrypoint.bat
  ci/docker_ci.sh
Labels: area/build, area/windows

#13133 Correct windows build flags for clang-cl/msvc-cl under opt/fastbuild/dbg
  .bazelrc
  bazel/BUILD
  bazel/envoy_binary.bzl
  bazel/envoy_internal.bzl
  bazel/envoy_test.bzl
  bazel/foreign_cc/BUILD
  bazel/foreign_cc/curl.patch
  bazel/repositories.bzl
  test/exe/BUILD
  test/extensions/filters/http/adaptive_concurrency/BUILD
  test/extensions/filters/http/common/compressor/BUILD
  test/extensions/filters/http/grpc_json_transcoder/BUILD
  test/extensions/filters/http/jwt_authn/BUILD
  test/extensions/filters/http/lua/BUILD
  test/extensions/filters/network/sni_dynamic_forward_proxy/BUILD
  test/extensions/quic_listeners/quiche/integration/BUILD
  test/extensions/stats_sinks/hystrix/BUILD
  test/server/BUILD
Labels: area/build, area/windows

#13309 repokitteh: Add welcome message for new contributors
  ci/repokitteh/modules/newcontributor.star
  repokitteh.star
Labels: area/repokitteh

#13483 wasm: support list lookup in get_property
  source/extensions/common/wasm/context.cc
  test/extensions/filters/http/wasm/test_data/test_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: waiting

#13509 Windows: Enable wasm vm test
  test/extensions/common/wasm/BUILD
Labels: area/windows

#13494 mongo_proxy: support configurable command list for metrics
  api/envoy/extensions/filters/network/mongo_proxy/v3/mongo_proxy.proto
  docs/root/configuration/listeners/network_filters/mongo_proxy_filter.rst
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/network/mongo_proxy/v3/mongo_proxy.proto
  source/extensions/filters/network/mongo_proxy/config.cc
  source/extensions/filters/network/mongo_proxy/mongo_stats.cc
  source/extensions/filters/network/mongo_proxy/mongo_stats.h
  source/extensions/filters/network/mongo_proxy/utility.cc
  test/extensions/filters/network/mongo_proxy/config_test.cc
  test/extensions/filters/network/mongo_proxy/proxy_test.cc
  test/extensions/filters/network/mongo_proxy/utility_test.cc
Labels: v2-freeze

#13482 http2: Proactively disconnect connections flooded when resetting stream
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl_legacy.cc
  test/common/http/http2/codec_impl_test.cc
  test/integration/autonomous_upstream.cc
  test/integration/autonomous_upstream.h
  test/integration/http2_integration_test.cc
Labels: waiting

#13515 overload: prevent segfault when disabling listener
  source/server/connection_handler_impl.cc
  source/server/connection_handler_impl.h
  test/server/connection_handler_test.cc
Labels: backport/review

#13549 Update opencensus library
  bazel/repository_locations.bzl
Labels: deps

#13552 dependencies: CVE scanner for repository_locations.bzl metadata.
  api/bazel/external_deps.bzl
  bazel/repository_locations.bzl
  ci/do_ci.sh
  docs/build.sh
  docs/generate_external_dep_rst.py
  generated_api_shadow/bazel/external_deps.bzl
  tools/dependency/cve_scan.py
  tools/dependency/cve_scan_test.py
  tools/dependency/utils.py
Labels: deps

#13288 ext_authz: Avoid calling check multiple times
  source/extensions/filters/http/ext_authz/ext_authz.cc
  test/extensions/filters/http/ext_authz/ext_authz_test.cc
Labels: waiting

#13638 tap: fix upstream streamed transport socket taps
  api/envoy/config/common/tap/v2alpha/BUILD
  api/envoy/config/common/tap/v2alpha/common.proto
  api/envoy/extensions/common/tap/v3/BUILD
  api/envoy/extensions/common/tap/v3/common.proto
  api/envoy/extensions/common/tap/v4alpha/BUILD
  api/envoy/extensions/common/tap/v4alpha/common.proto
  generated_api_shadow/envoy/config/common/tap/v2alpha/BUILD
  generated_api_shadow/envoy/config/common/tap/v2alpha/common.proto
  generated_api_shadow/envoy/extensions/common/tap/v3/BUILD
  generated_api_shadow/envoy/extensions/common/tap/v3/common.proto
  generated_api_shadow/envoy/extensions/common/tap/v4alpha/BUILD
  generated_api_shadow/envoy/extensions/common/tap/v4alpha/common.proto
  source/extensions/common/tap/extension_config_base.cc
  source/extensions/transport_sockets/tap/tap_config_impl.cc
  test/extensions/common/tap/common.cc
  test/extensions/common/tap/common.h
  test/extensions/filters/http/common/fuzz/uber_per_filter.cc
  test/extensions/filters/http/tap/BUILD
  test/extensions/filters/http/tap/tap_filter_integration_test.cc
  test/extensions/transport_sockets/tls/integration/BUILD
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
Labels: api, v2-freeze

#13582 dependencies: compute and check release dates via GitHub API.
  .azure-pipelines/pipelines.yml
  DEPENDENCY_POLICY.md
  api/bazel/external_deps.bzl
  api/bazel/repository_locations.bzl
  bazel/repositories_extra.bzl
  bazel/repository_locations.bzl
  ci/check_repository_locations.sh
  ci/do_ci.sh
  ci/run_envoy_docker.sh
  docs/generate_external_dep_rst.py
  generated_api_shadow/bazel/external_deps.bzl
  generated_api_shadow/bazel/repository_locations.bzl
  tools/dependency/release_dates.py
  tools/dependency/release_dates.sh
  tools/dependency/requirements.txt
  tools/dependency/utils.py
  tools/deprecate_version/deprecate_version.py
  tools/github/sync_assignable.py
  tools/shell_utils.sh
Labels: deps

#13661 build: update bazel to 3.6.0
  .bazelversion
  bazel/repository_locations.bzl
Labels: deps

#13667 wasm: remove no longer needed Emscripten metadata.
  bazel/repository_locations.bzl
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_vm_test.cc
Labels: deps

#13669 repokitteh: Secure azure creds
  ci/repokitteh/modules/azure_pipelines.star
Labels: rk:blessed

#13652 build: don't build shared libraries for zlib and zlib-ng.
  bazel/foreign_cc/BUILD
  bazel/foreign_cc/zlib.patch
Labels: deps

#13707 wasm: update Emscripten to v2.0.7.
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: deps

#13430 Adds TCP info on Windows
  bazel/README.md
  bazel/envoy_internal.bzl
  include/envoy/api/os_sys_calls.h
  include/envoy/common/platform.h
  source/common/api/posix/os_sys_calls_impl.cc
  source/common/api/posix/os_sys_calls_impl.h
  source/common/api/win32/os_sys_calls_impl.cc
  source/common/api/win32/os_sys_calls_impl.h
  source/common/network/io_socket_handle_impl.cc
  test/common/network/BUILD
  test/common/network/io_socket_handle_impl_integration_test.cc
  test/common/network/io_socket_handle_impl_test.cc
  test/mocks/api/mocks.h
Labels: area/windows

#13744 rk: improve azp retry
  ci/repokitteh/modules/azure_pipelines.star
Labels: rk:blessed

#13712 build: update protobuf to 3.13.0
  bazel/envoy_internal.bzl
  bazel/protobuf.patch
  bazel/repository_locations.bzl
  test/extensions/filters/common/lua/lua_wrappers.h
  test/extensions/filters/http/lua/wrappers_test.cc
Labels: deps

#13264 Windows: Fix ssl_socket_test
  source/common/filesystem/win32/filesystem_impl.cc
  source/extensions/transport_sockets/tls/ssl_socket.cc
  source/extensions/transport_sockets/tls/ssl_socket.h
  test/extensions/transport_sockets/tls/BUILD
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
Labels: area/tls, area/windows

#13798 http: fixing a bug with IPv6 hosts
  docs/root/version_history/current.rst
  source/common/http/utility.cc
  test/common/http/utility_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/integration/integration_test.cc
Labels: backport/review
