Repository envoyproxy/envoy, pull requests merged in 2020-02, with the labels that each got.

#9906 repokitteh: add backport labeling
  repokitteh.star
  source/docs/repokitteh.md
Labels: backport/review

#9878 filter: Add HttpCache interface and helpers
  source/common/http/headers.h
  source/extensions/filters/http/cache/BUILD
  source/extensions/filters/http/cache/http_cache.cc
  source/extensions/filters/http/cache/http_cache.h
  source/extensions/filters/http/cache/key.proto
  test/extensions/filters/http/cache/BUILD
  test/extensions/filters/http/cache/http_cache_test.cc
  tools/spelling_dictionary.txt
Labels: api

#10010 matcher: add PathMatcher and use in routing, jwt and rbac
  api/envoy/config/rbac/v2/rbac.proto
  api/envoy/config/rbac/v3/rbac.proto
  api/envoy/type/matcher/path.proto
  api/envoy/type/matcher/v3/path.proto
  docs/root/api-v2/types/types.rst
  docs/root/api-v3/types/types.rst
  docs/root/intro/version_history.rst
  generated_api_shadow/envoy/config/rbac/v2/rbac.proto
  generated_api_shadow/envoy/config/rbac/v3/rbac.proto
  generated_api_shadow/envoy/type/matcher/path.proto
  generated_api_shadow/envoy/type/matcher/v3/path.proto
  source/common/common/BUILD
  source/common/common/matchers.cc
  source/common/common/matchers.h
  source/common/http/path_utility.cc
  source/common/http/path_utility.h
  source/common/router/BUILD
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/extensions/filters/common/rbac/matchers.cc
  source/extensions/filters/common/rbac/matchers.h
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/matcher.cc
  test/common/common/matchers_test.cc
  test/common/http/path_utility_test.cc
  test/extensions/filters/common/rbac/matchers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_test.cc
Labels: backport/approved

#10016 [release/v1.13] string matcher: add ignore_case to StringMatcher (#9868)
  api/envoy/type/matcher/string.proto
  api/envoy/type/matcher/v3/string.proto
  generated_api_shadow/envoy/type/matcher/string.proto
  generated_api_shadow/envoy/type/matcher/v3/string.proto
  source/common/common/matchers.cc
  test/common/common/BUILD
  test/common/common/matchers_test.cc
Labels: api, waiting

#10017 [release/v1.12] string matcher: add ignore_case to StringMatcher (#9868)
  api/envoy/type/matcher/string.proto
  api/envoy/type/matcher/v3alpha/string.proto
  source/common/common/matchers.cc
  test/common/common/BUILD
  test/common/common/matchers_test.cc
Labels: api

#10038 [release/v1.12] matcher: add PathMatcher and use in routing, jwt and rbac
  api/envoy/config/rbac/v2/rbac.proto
  api/envoy/config/rbac/v3alpha/rbac.proto
  api/envoy/type/matcher/path.proto
  api/envoy/type/matcher/v3alpha/path.proto
  docs/root/api-v2/types/types.rst
  docs/root/intro/version_history.rst
  source/common/common/BUILD
  source/common/common/matchers.cc
  source/common/common/matchers.h
  source/common/http/path_utility.cc
  source/common/http/path_utility.h
  source/common/router/BUILD
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/extensions/filters/common/rbac/matchers.cc
  source/extensions/filters/common/rbac/matchers.h
  source/extensions/filters/http/jwt_authn/BUILD
  source/extensions/filters/http/jwt_authn/matcher.cc
  test/common/common/matchers_test.cc
  test/common/http/path_utility_test.cc
  test/extensions/filters/common/rbac/matchers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_test.cc
Labels: api

#9715 ext_authz: Deprecate LowerCaseStringMatcher
  docs/root/intro/deprecated.rst
  docs/root/intro/version_history.rst
  source/common/common/matchers.cc
  source/common/common/matchers.h
  source/common/runtime/runtime_features.cc
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.h
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_authz/ext_authz.h
  test/common/common/matchers_test.cc
  test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_test.cc
Labels: api

#10093 [api] [fuzz] fix many header related config fuzz bugs
  api/bazel/repository_locations.bzl
  api/envoy/api/v2/core/base.proto
  api/envoy/api/v2/route.proto
  api/envoy/api/v2/route/route_components.proto
  api/envoy/config/core/v3/base.proto
  api/envoy/config/route/v3/route.proto
  api/envoy/config/route/v3/route_components.proto
  api/envoy/type/tracing/v2/custom_tag.proto
  api/envoy/type/tracing/v3/custom_tag.proto
  generated_api_shadow/bazel/repository_locations.bzl
  generated_api_shadow/envoy/api/v2/core/base.proto
  generated_api_shadow/envoy/api/v2/route.proto
  generated_api_shadow/envoy/api/v2/route/route_components.proto
  generated_api_shadow/envoy/config/core/v3/base.proto
  generated_api_shadow/envoy/config/route/v3/route.proto
  generated_api_shadow/envoy/config/route/v3/route_components.proto
  generated_api_shadow/envoy/type/tracing/v2/custom_tag.proto
  generated_api_shadow/envoy/type/tracing/v3/custom_tag.proto
  test/common/http/conn_manager_impl_corpus/clusterfuzz-testcase-minimized-conn_manager_impl_fuzz_test-5714279517126656
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/router/header_parser_fuzz_test.cc
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-4592245302362112
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5206842068697088
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5634743613259776
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5635252339343360
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5661762636742656
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5699465522970624
  test/common/router/route_corpus/clusterfuzz-testcase-minimized-route_fuzz_test-5750746072481792
  test/common/router/route_fuzz_test.cc
  test/fuzz/utility.h
Labels: api

#10214 docker: push SHA tag for release branch too
  ci/docker_build.sh
  ci/docker_push.sh
Labels: backport/review
