Repository envoyproxy/envoy, pull requests merged in 2021-07, with the labels that each got.

#17118 listener: add filter chain match support for direct source address
  api/envoy/config/listener/v3/listener_components.proto
  api/envoy/config/listener/v4alpha/listener_components.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/listener/v3/listener_components.proto
  generated_api_shadow/envoy/config/listener/v4alpha/listener_components.proto
  source/server/filter_chain_manager_impl.cc
  source/server/filter_chain_manager_impl.h
  test/integration/base_integration_test.cc
  test/integration/proxy_proto_integration_test.cc
  test/integration/proxy_proto_integration_test.h
  test/mocks/network/mocks.h
  test/server/filter_chain_benchmark_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
Labels: api

#16774 Add ability to filter ConfigDump.
  docs/root/operations/admin.rst
  envoy/server/BUILD
  envoy/server/config_tracker.h
  source/common/common/matchers.h
  source/common/config/config_provider_impl.cc
  source/common/config/config_provider_impl.h
  source/common/router/rds_impl.cc
  source/common/router/rds_impl.h
  source/common/router/scoped_rds.cc
  source/common/router/scoped_rds.h
  source/common/secret/secret_manager_impl.cc
  source/common/secret/secret_manager_impl.h
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/cluster_manager_impl.h
  source/server/admin/BUILD
  source/server/admin/config_dump_handler.cc
  source/server/admin/config_dump_handler.h
  source/server/listener_manager_impl.cc
  source/server/listener_manager_impl.h
  source/server/server.cc
  test/common/config/config_provider_impl_test.cc
  test/common/router/BUILD
  test/common/router/rds_impl_test.cc
  test/common/router/scoped_rds_test.cc
  test/common/secret/BUILD
  test/common/secret/secret_manager_impl_test.cc
  test/common/upstream/BUILD
  test/common/upstream/cluster_manager_impl_test.cc
  test/integration/BUILD
  test/integration/ads_integration.cc
  test/integration/base_integration_test.cc
  test/integration/integration_admin_test.cc
  test/mocks/matcher/BUILD
  test/mocks/matcher/mocks.h
  test/server/BUILD
  test/server/admin/BUILD
  test/server/admin/config_dump_handler_test.cc
  test/server/admin/config_tracker_impl_test.cc
  test/server/config_validation/BUILD
  test/server/config_validation/xds_fuzz.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
Labels: api

#17207 dns cache: add DNS query timeout option
  api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
  api/envoy/extensions/common/dynamic_forward_proxy/v4alpha/dns_cache.proto
  docs/root/configuration/http/http_filters/dynamic_forward_proxy_filter.rst
  docs/root/version_history/current.rst
  envoy/network/dns.h
  generated_api_shadow/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
  generated_api_shadow/envoy/extensions/common/dynamic_forward_proxy/v4alpha/dns_cache.proto
  source/common/network/apple_dns_impl.cc
  source/common/network/apple_dns_impl.h
  source/common/network/dns_impl.h
  source/common/upstream/logical_dns_cluster.cc
  source/common/upstream/strict_dns_cluster.cc
  source/extensions/clusters/redis/redis_cluster.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
  test/common/network/apple_dns_impl_test.cc
  test/common/network/dns_impl_test.cc
  test/common/upstream/logical_dns_cluster_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/extensions/clusters/redis/redis_cluster_test.cc
  test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
  test/mocks/network/mocks.h
Labels: api

#17172 tools: Add AsyncChecker
  tools/base/checker.py
  tools/base/tests/test_checker.py
  tools/testing/BUILD
  tools/testing/requirements.txt
Labels: deps

#16670 http: setting default lazy headermap threshold to 3
  docs/root/intro/arch_overview/http/http_connection_management.rst
  docs/root/version_history/current.rst
  source/common/http/header_map_impl.h
  source/docs/header_map.md
Labels: no stalebot

#17347 docs: fix bullet lists
  docs/conf.py
  tools/docs/requirements.txt
Labels: deps

#17294 repokitteh: add warning for draft PRs
  ci/repokitteh/modules/newpr.star
  repokitteh.star
Labels: rk:blessed

#17196 [alts]: store tsi peer property in dynamic metadata.
  api/envoy/extensions/transport_sockets/alts/v3/alts.proto
  generated_api_shadow/envoy/extensions/transport_sockets/alts/v3/alts.proto
  source/extensions/transport_sockets/alts/config.cc
  source/extensions/transport_sockets/alts/tsi_socket.cc
  source/extensions/transport_sockets/alts/tsi_socket.h
  test/extensions/transport_sockets/alts/BUILD
  test/extensions/transport_sockets/alts/alts_integration_test.cc
  test/extensions/transport_sockets/alts/tsi_socket_test.cc
  test/integration/filters/BUILD
  test/integration/filters/decode_dynamic_metadata_filter.cc
Labels: api, v2-freeze

#17360 tooling: Add misc contextmanagers/decorators
  .github/dependabot.yml
  bazel/repositories_extra.bzl
  tools/base/runner.py
  tools/base/tests/test_runner.py
  tools/base/tests/test_utils.py
  tools/base/utils.py
  tools/git/BUILD
  tools/git/requirements.txt
  tools/git/tests/test_utils.py
  tools/git/utils.py
Labels: deps

#17399 dist: Add GPG identity util
  .github/dependabot.yml
  bazel/repositories_extra.bzl
  tools/gpg/BUILD
  tools/gpg/identity.py
  tools/gpg/requirements.txt
  tools/gpg/tests/test_identity.py
  tools/testing/BUILD
Labels: deps

#17384 tooling: Add docker build util
  .github/dependabot.yml
  bazel/repositories_extra.bzl
  tools/docker/BUILD
  tools/docker/requirements.txt
  tools/docker/tests/test_utils.py
  tools/docker/utils.py
Labels: deps

#17414 listener: allow TCP and UDP on the same port
  source/server/listener_impl.cc
  source/server/listener_impl.h
  source/server/listener_manager_impl.cc
  source/server/listener_manager_impl.h
  test/server/listener_manager_impl_test.cc
Labels: no stalebot, waiting

#17407 config: extending usage of EnvoyMobileHttpConnectionManager
  api/envoy/config/listener/v3/api_listener.proto
  api/envoy/config/listener/v4alpha/api_listener.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  generated_api_shadow/envoy/config/listener/v3/api_listener.proto
  generated_api_shadow/envoy/config/listener/v4alpha/api_listener.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/extensions/filters/network/well_known_names.h
  source/server/api_listener_impl.cc
  test/extensions/filters/network/common/fuzz/network_readfilter_corpus/envoy_mobile_http_connection_manager_1
  test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc
  test/server/api_listener_test.cc
  tools/extensions/extensions_check.py
  tools/protodoc/protodoc.py
Labels: waiting

#17413 docs: updated quickstart/run envoy doc to ensure a smoother first time experience
  .gitignore
  docs/root/start/quick-start/run-envoy.rst
Labels: api
