Repository envoyproxy/envoy, pull requests merged in 2021-05, with the labels that each got.

#16077 docs: Remove api v2
  api/BUILD
  api/xds_protocol.rst
  docs/build.sh
  docs/conf.py
  docs/root/api-v3/config/filter/thrift/thrift.rst
  docs/root/api-v3/config/health_checker/health_checker.rst
  docs/root/api-v3/config/resource_monitor/resource_monitor.rst
  docs/root/api-v3/config/retry/retry.rst
  docs/root/configuration/http/http_conn_man/rds.rst
  docs/root/configuration/http/http_conn_man/vhds.rst
  docs/root/configuration/listeners/lds.rst
  docs/root/configuration/other_protocols/dubbo_filters/router_filter.rst
  docs/root/configuration/overview/xds_api.rst
  docs/root/configuration/upstream/cluster_manager/cds.rst
  docs/v2-api-header.rst
Labels: api, deps

#15967 udp: add new key based hash policy
  api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  source/extensions/filters/udp/udp_proxy/hash_policy_impl.cc
  test/extensions/filters/udp/udp_proxy/hash_policy_impl_test.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: api

#16264 skywalking: fix string_view UB while span reporting
  source/extensions/tracers/skywalking/tracer.cc
  test/extensions/tracers/skywalking/tracer_test.cc
Labels: backport/review

#16459 dependabot: Updates
  configs/requirements.txt
  docs/requirements.txt
  source/extensions/filters/network/kafka/requirements.txt
  tools/protodoc/requirements.txt
Labels: deps

#16483 Revert "dependabot: Updates (#16459)"
  configs/requirements.txt
  docs/requirements.txt
  source/extensions/filters/network/kafka/requirements.txt
  tools/protodoc/requirements.txt
Labels: deps

#16373 Crash support: Restore crash context on filter's posted callback
  docs/root/version_history/current.rst
  include/envoy/event/dispatcher.h
  include/envoy/http/BUILD
  include/envoy/http/filter.h
  include/envoy/network/connection.h
  source/common/common/BUILD
  source/common/common/scope_tracked_object_stack.h
  source/common/event/dispatcher_impl.h
  source/common/http/BUILD
  source/common/http/async_client_impl.h
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/network/connection_impl.h
  source/common/quic/envoy_quic_client_session.h
  source/common/quic/envoy_quic_server_session.h
  source/server/api_listener_impl.h
  test/common/common/BUILD
  test/common/common/scope_tracked_object_stack_test.cc
  test/common/event/dispatcher_impl_test.cc
  test/common/http/filter_manager_test.cc
  test/common/quic/test_utils.h
  test/extensions/filters/http/kill_request/BUILD
  test/extensions/filters/http/kill_request/crash_integration_test.cc
  test/integration/filters/BUILD
  test/integration/filters/stop_and_continue_filter_config.proto
  test/integration/filters/stop_iteration_and_continue_filter.cc
  test/integration/integration_test.cc
  test/integration/multiplexed_integration_test.cc
  test/mocks/event/mocks.h
  test/mocks/event/wrapped_dispatcher.h
  test/mocks/http/mocks.h
  test/mocks/network/connection.h
  test/test_common/utility.h
Labels: waiting

#16541 quic: reduce socket option header exposure
  source/common/quic/active_quic_listener.cc
  source/common/quic/active_quic_listener.h
Labels: area/quic

#15843 Per connection local rate limiting
  api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
  docs/root/configuration/http/http_filters/local_rate_limit_filter.rst
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto
  source/extensions/filters/http/local_ratelimit/local_ratelimit.cc
  source/extensions/filters/http/local_ratelimit/local_ratelimit.h
  test/extensions/filters/http/local_ratelimit/filter_test.cc
Labels: deps, v2-freeze

#16576 Revert "JwtAuthn: complete padding on forward jwt payload header"
  source/common/common/base64.cc
  source/common/common/base64.h
  source/extensions/filters/http/jwt_authn/authenticator.cc
  test/common/common/base64_test.cc
  test/extensions/filters/http/jwt_authn/BUILD
  test/extensions/filters/http/jwt_authn/test_common.h
Labels: backport/approved

#16618 extensions: Add extensions metadata.yaml
  CONTRIBUTING.md
  bazel/envoy_library.bzl
  docs/build.sh
  docs/requirements.txt
  source/extensions/BUILD
  source/extensions/extensions_metadata.yaml
  tools/extensions/BUILD
  tools/extensions/generate_extension_db.py
  tools/extensions/generate_extension_rst.py
  tools/extensions/validate_extensions.py
  tools/protodoc/BUILD
  tools/protodoc/protodoc.py
Labels: deps

#16553 tls: future-proof Utility::getErrorDescription
  source/extensions/transport_sockets/tls/utility.cc
  source/extensions/transport_sockets/tls/utility.h
  test/extensions/transport_sockets/tls/utility_test.cc
Labels: area/tls, tech debt

#16294 dynamic_forward_proxy: adding dns_resolvers to dns_cache used by the proxy filter
  api/envoy/config/core/v3/resolver.proto
  api/envoy/config/core/v4alpha/resolver.proto
  api/envoy/extensions/common/dynamic_forward_proxy/v3/BUILD
  api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
  docs/root/api-v3/common_messages/common_messages.rst
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/core/v3/resolver.proto
  generated_api_shadow/envoy/config/core/v4alpha/resolver.proto
  generated_api_shadow/envoy/extensions/common/dynamic_forward_proxy/v3/BUILD
  generated_api_shadow/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
  test/extensions/common/dynamic_forward_proxy/BUILD
  test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
Labels: deps
