Repository envoyproxy/envoy, pull requests merged in 2021-10, with the labels that each got.

#18280 Add detailed X509 error message when validation fails.
  source/extensions/transport_sockets/tls/cert_validator/BUILD
  source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
  source/extensions/transport_sockets/tls/cert_validator/default_validator.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/utility.cc
  source/extensions/transport_sockets/tls/utility.h
  test/extensions/transport_sockets/tls/utility_test.cc
Labels: api, v2-freeze, deps

#18387 dependabot: Updates
  .github/actions/pr_notifier/requirements.txt
  test/extensions/filters/network/thrift_proxy/requirements.txt
  tools/base/requirements.txt
  tools/dependency/requirements.txt
Labels: deps

#18203 Add Windows Server 2022 based images
  .azure-pipelines/pipelines.yml
  ci/docker_ci.sh
  docs/root/version_history/current.rst
Labels: area/windows, area/docker, area/ci
