Repository envoyproxy/envoy, pull requests merged in 2021-09, with the labels that each got.

#17215 Add SXG filter extension
  CODEOWNERS
  api/BUILD
  api/contrib/envoy/extensions/filters/http/sxg/v3alpha/BUILD
  api/contrib/envoy/extensions/filters/http/sxg/v3alpha/sxg.proto
  api/versioning/BUILD
  bazel/foreign_cc/BUILD
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/sxg/filters/http/source/BUILD
  contrib/sxg/filters/http/source/config.cc
  contrib/sxg/filters/http/source/config.h
  contrib/sxg/filters/http/source/encoder.cc
  contrib/sxg/filters/http/source/encoder.h
  contrib/sxg/filters/http/source/filter.cc
  contrib/sxg/filters/http/source/filter.h
  contrib/sxg/filters/http/source/filter_config.cc
  contrib/sxg/filters/http/source/filter_config.h
  contrib/sxg/filters/http/test/BUILD
  contrib/sxg/filters/http/test/config_test.cc
  contrib/sxg/filters/http/test/filter_test.cc
  docs/root/configuration/http/http_filters/http_filters.rst
  docs/root/configuration/http/http_filters/squash_filter.rst
  docs/root/configuration/http/http_filters/sxg_filter.rst
  docs/root/faq/windows/win_not_supported_features.rst
  docs/root/version_history/current.rst
  generated_api_shadow/BUILD
  generated_api_shadow/contrib/envoy/extensions/filters/http/sxg/v3alpha/BUILD
  generated_api_shadow/contrib/envoy/extensions/filters/http/sxg/v3alpha/sxg.proto
  tools/spelling/spelling_dictionary.txt
Labels: api, deps

#11936 Kafka-mesh filter
  api/BUILD
  api/contrib/envoy/extensions/filters/network/kafka_mesh/v3alpha/BUILD
  api/contrib/envoy/extensions/filters/network/kafka_mesh/v3alpha/kafka_mesh.proto
  api/versioning/BUILD
  bazel/BUILD
  bazel/repository_locations.bzl
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/kafka/filters/network/source/mesh/BUILD
  contrib/kafka/filters/network/source/mesh/config.cc
  contrib/kafka/filters/network/source/mesh/config.h
  contrib/kafka/filters/network/source/mesh/upstream_config.cc
  contrib/kafka/filters/network/source/mesh/upstream_config.h
  contrib/kafka/filters/network/test/mesh/BUILD
  contrib/kafka/filters/network/test/mesh/config_unit_test.cc
  contrib/kafka/filters/network/test/mesh/integration_test/BUILD
  contrib/kafka/filters/network/test/mesh/integration_test/envoy_config_yaml.j2
  contrib/kafka/filters/network/test/mesh/integration_test/kafka_mesh_integration_test.py
  contrib/kafka/filters/network/test/mesh/integration_test/kafka_server_properties.j2
  contrib/kafka/filters/network/test/mesh/integration_test/zookeeper_properties.j2
  contrib/kafka/filters/network/test/mesh/upstream_config_unit_test.cc
  docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
  docs/root/configuration/listeners/network_filters/kafka_mesh_filter.rst
  docs/root/configuration/listeners/network_filters/network_filters.rst
  generated_api_shadow/BUILD
  generated_api_shadow/contrib/envoy/extensions/filters/network/kafka_mesh/v3alpha/BUILD
  generated_api_shadow/contrib/envoy/extensions/filters/network/kafka_mesh/v3alpha/kafka_mesh.proto
  tools/code_format/check_format.py
Labels: api, v2-freeze, deps

#18070 cve: Suppress false +ves
  tools/dependency/cve_scan.py
Labels: deps

#18046 bazel: Switch `py_script` -> `rules_python.entry_point`
  tools/base/BUILD
  tools/base/base_command.py
  tools/base/envoy_python.bzl
  tools/distribution/BUILD
Labels: deps

#17995 router: Added alt_header_name to set an arbitrary header for populating SNI
  api/envoy/config/core/v3/protocol.proto
  docs/root/faq/configuration/sni.rst
  docs/root/version_history/current.rst
  source/common/router/router.cc
  test/common/router/router_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/filters/http/router/auto_sni_integration_test.cc
Labels: api, v2-freeze

#18078 router: add per_try_idle_timeout configuration
  api/envoy/config/route/v3/route_components.proto
  docs/root/faq/configuration/timeouts.rst
  docs/root/version_history/current.rst
  envoy/router/router.h
  envoy/stream_info/stream_info.h
  envoy/upstream/cluster_manager.h
  envoy/upstream/upstream.h
  source/common/http/async_client_impl.h
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/common/router/router.cc
  source/common/router/router.h
  source/common/router/upstream_request.cc
  source/common/router/upstream_request.h
  test/common/router/config_impl_test.cc
  test/common/router/router_test.cc
  test/common/router/router_test_base.cc
  test/common/router/router_test_base.h
  test/integration/idle_timeout_integration_test.cc
  test/mocks/router/mocks.h
  test/mocks/router/router_filter_interface.h
Labels: api

#18136 Quiche merge
  bazel/repository_locations.bzl
  source/common/quic/platform/quiche_flags_impl.cc
  test/common/quic/envoy_quic_client_session_test.cc
  test/common/quic/envoy_quic_server_session_test.cc
Labels: deps

#18021 bazel: Add implementation of ABazelQuery
  tools/base/BUILD
  tools/base/bazel_query.py
Labels: deps

#18133 dependabot: Updates
  .github/actions/pr_notifier/requirements.txt
  tools/base/requirements.txt
  tools/dependency/requirements.txt
Labels: deps

#17981 tooling: Shift `api_proto_breaking_change_detector` to bazel
  ci/do_ci.sh
  tools/api_proto_breaking_change_detector/BUILD
  tools/api_proto_breaking_change_detector/buf_utils.py
  tools/api_proto_breaking_change_detector/detector.py
  tools/api_proto_breaking_change_detector/detector_ci.py
  tools/api_proto_breaking_change_detector/detector_ci.sh
  tools/api_proto_breaking_change_detector/detector_test.py
Labels: deps

#17816 Add support to allow routing to the weighted cluster specified in the request_header
  docs/root/version_history/current.rst
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  test/common/router/config_impl_test.cc
  test/extensions/clusters/redis/redis_cluster_integration_test.cc
  test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc
  test/extensions/filters/udp/dns_filter/dns_filter_integration_test.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
  test/extensions/retry/host/previous_hosts/integration_test.cc
  test/integration/BUILD
  test/integration/base_integration_test.cc
  test/integration/base_integration_test.h
  test/integration/filters/BUILD
  test/integration/filters/repick_cluster_filter.cc
  test/integration/filters/repick_cluster_filter.h
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/load_stats_integration_test.cc
  test/integration/server.cc
  test/integration/server.h
  test/integration/weighted_cluster_integration_test.cc
  test/mocks/common.cc
  test/mocks/common.h
  tools/spelling/spelling_dictionary.txt
Labels: api

#18002 ext_authz: Honor append field of OkHttpResponse.response_headers_to_add
  docs/root/version_history/current.rst
  source/extensions/filters/common/ext_authz/ext_authz.h
  source/extensions/filters/common/ext_authz/ext_authz_grpc_impl.cc
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_authz/ext_authz.h
  test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
  test/extensions/filters/common/ext_authz/test_common.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_test.cc
Labels: area/ext_authz

#18163 Fix issue where EnvoyUsers password expires
  ci/Dockerfile-envoy-windows
Labels: area/windows, area/docker

#18074 kafka: upgrade kafka source code and server dependencies to 2.8.1
  bazel/external/kafka_int32.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  contrib/kafka/filters/network/source/kafka_response.h
  contrib/kafka/filters/network/source/kafka_types.h
  contrib/kafka/filters/network/source/mesh/command_handlers/api_versions.cc
  contrib/kafka/filters/network/source/mesh/command_handlers/metadata.cc
  contrib/kafka/filters/network/source/mesh/command_handlers/produce.cc
  contrib/kafka/filters/network/source/mesh/command_handlers/produce_record_extractor.cc
  contrib/kafka/filters/network/source/protocol/generator.py
  contrib/kafka/filters/network/source/serialization.cc
  contrib/kafka/filters/network/source/serialization.h
  contrib/kafka/filters/network/source/tagged_fields.h
  contrib/kafka/filters/network/test/broker/filter_protocol_test.cc
  contrib/kafka/filters/network/test/mesh/command_handlers/metadata_unit_test.cc
  contrib/kafka/filters/network/test/mesh/command_handlers/produce_unit_test.cc
  contrib/kafka/filters/network/test/mesh/request_processor_unit_test.cc
  contrib/kafka/filters/network/test/message_utilities.h
  contrib/kafka/filters/network/test/metrics_integration_test.cc
  contrib/kafka/filters/network/test/protocol/request_utilities_cc.j2
  contrib/kafka/filters/network/test/protocol/response_utilities_cc.j2
  contrib/kafka/filters/network/test/serialization_test.cc
  docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
  docs/root/configuration/listeners/network_filters/kafka_mesh_filter.rst
Labels: deps

#17902 filter: add ratelimit log
  source/extensions/filters/common/ratelimit/ratelimit_impl.cc
  source/extensions/filters/http/ratelimit/ratelimit.cc
Labels: waiting

#18273 bazel: Fix rules_go release date
  bazel/repository_locations.bzl
Labels: deps

#18039 sip_proxy: SIP protocol support in envoy
  CODEOWNERS
  api/BUILD
  api/contrib/envoy/extensions/filters/network/sip_proxy/router/v3alpha/BUILD
  api/contrib/envoy/extensions/filters/network/sip_proxy/router/v3alpha/router.proto
  api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/BUILD
  api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/route.proto
  api/contrib/envoy/extensions/filters/network/sip_proxy/v3alpha/sip_proxy.proto
  api/versioning/BUILD
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/sip_proxy/filters/network/source/BUILD
  contrib/sip_proxy/filters/network/source/app_exception_impl.cc
  contrib/sip_proxy/filters/network/source/app_exception_impl.h
  contrib/sip_proxy/filters/network/source/config.cc
  contrib/sip_proxy/filters/network/source/config.h
  contrib/sip_proxy/filters/network/source/conn_manager.cc
  contrib/sip_proxy/filters/network/source/conn_manager.h
  contrib/sip_proxy/filters/network/source/conn_state.h
  contrib/sip_proxy/filters/network/source/decoder.cc
  contrib/sip_proxy/filters/network/source/decoder.h
  contrib/sip_proxy/filters/network/source/decoder_events.h
  contrib/sip_proxy/filters/network/source/encoder.cc
  contrib/sip_proxy/filters/network/source/encoder.h
  contrib/sip_proxy/filters/network/source/filters/BUILD
  contrib/sip_proxy/filters/network/source/filters/factory_base.h
  contrib/sip_proxy/filters/network/source/filters/filter.h
  contrib/sip_proxy/filters/network/source/filters/filter_config.h
  contrib/sip_proxy/filters/network/source/filters/pass_through_filter.h
  contrib/sip_proxy/filters/network/source/filters/well_known_names.h
  contrib/sip_proxy/filters/network/source/metadata.h
  contrib/sip_proxy/filters/network/source/operation.h
  contrib/sip_proxy/filters/network/source/protocol.h
  contrib/sip_proxy/filters/network/source/router/BUILD
  contrib/sip_proxy/filters/network/source/router/config.cc
  contrib/sip_proxy/filters/network/source/router/config.h
  contrib/sip_proxy/filters/network/source/router/router.h
  contrib/sip_proxy/filters/network/source/router/router_impl.cc
  contrib/sip_proxy/filters/network/source/router/router_impl.h
  contrib/sip_proxy/filters/network/source/sip.h
  contrib/sip_proxy/filters/network/source/stats.h
  contrib/sip_proxy/filters/network/test/BUILD
  contrib/sip_proxy/filters/network/test/app_exception_impl_test.cc
  contrib/sip_proxy/filters/network/test/config_test.cc
  contrib/sip_proxy/filters/network/test/conn_manager_test.cc
  contrib/sip_proxy/filters/network/test/decoder_test.cc
  contrib/sip_proxy/filters/network/test/mocks.cc
  contrib/sip_proxy/filters/network/test/mocks.h
  contrib/sip_proxy/filters/network/test/router_test.cc
  contrib/sip_proxy/filters/network/test/utility.h
  docs/root/api-v3/config/contrib/contrib.rst
  docs/root/api-v3/config/contrib/cryptomb/cryptomb.rst
  docs/root/api-v3/config/contrib/sip/sip.rst
  tools/extensions/extensions_check.py
  tools/spelling/spelling_dictionary.txt
Labels: deps

#18220 use clang 12
  .bazelrc
  .devcontainer/Dockerfile
  api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto
  api/envoy/extensions/filters/http/jwt_authn/v3/config.proto
  bazel/dependency_imports.bzl
  bazel/external/envoy_build_tools.patch
  bazel/external/rules_cc.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  examples/wasm-cc/docker-compose-wasm.yaml
  test/common/http/header_map_impl_test.cc
  test/per_file_coverage.sh
  test/run_envoy_bazel_coverage.sh
Labels: api, v2-freeze

#17645 rbac: add support for upstream ip policy.
  CODEOWNERS
  api/BUILD
  api/envoy/config/rbac/v3/rbac.proto
  api/envoy/extensions/filters/http/dynamic_forward_proxy/v3/dynamic_forward_proxy.proto
  api/envoy/extensions/rbac/matchers/upstream_ip_port/v3/BUILD
  api/envoy/extensions/rbac/matchers/upstream_ip_port/v3/upstream_ip_port_matcher.proto
  api/versioning/BUILD
  bazel/repository_locations.bzl
  docs/root/api-v3/config/config.rst
  docs/root/api-v3/config/rbac/matchers.rst
  docs/root/api-v3/config/rbac/matchers/matchers.rst
  docs/root/api-v3/config/rbac/matchers/upstream/upstream.rst
  docs/root/version_history/current.rst
  source/common/stream_info/BUILD
  source/common/stream_info/upstream_address.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/filters/common/rbac/BUILD
  source/extensions/filters/common/rbac/engine_impl.cc
  source/extensions/filters/common/rbac/engine_impl.h
  source/extensions/filters/common/rbac/matcher_extension.h
  source/extensions/filters/common/rbac/matchers.cc
  source/extensions/filters/common/rbac/matchers.h
  source/extensions/filters/common/rbac/matchers/BUILD
  source/extensions/filters/common/rbac/matchers/upstream_ip_port.cc
  source/extensions/filters/common/rbac/matchers/upstream_ip_port.h
  source/extensions/filters/common/rbac/utility.h
  source/extensions/filters/http/dynamic_forward_proxy/BUILD
  source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
  source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.h
  source/extensions/filters/http/rbac/BUILD
  source/extensions/filters/http/rbac/config.cc
  source/extensions/filters/http/rbac/rbac_filter.cc
  source/extensions/filters/http/rbac/rbac_filter.h
  source/extensions/filters/network/rbac/config.cc
  source/extensions/filters/network/rbac/rbac_filter.cc
  source/extensions/filters/network/rbac/rbac_filter.h
  test/extensions/filters/common/rbac/engine_impl_test.cc
  test/extensions/filters/common/rbac/matchers_test.cc
  test/extensions/filters/common/rbac/mocks.h
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_test.cc
  test/extensions/filters/http/rbac/BUILD
  test/extensions/filters/http/rbac/mocks.h
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_test.cc
  test/extensions/filters/network/rbac/filter_test.cc
  tools/extensions/extensions_check.py
Labels: deps

#13176 Support slow Start mode in Envoy
  api/envoy/config/cluster/v3/cluster.proto
  docs/root/_static/slow_start_aggression.svg
  docs/root/_static/slow_start_example.svg
  docs/root/intro/arch_overview/upstream/load_balancing/load_balancing.rst
  docs/root/intro/arch_overview/upstream/load_balancing/slow_start.rst
  docs/root/version_history/current.rst
  envoy/upstream/upstream.h
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/load_balancer_impl.cc
  source/common/upstream/load_balancer_impl.h
  source/common/upstream/subset_lb.cc
  source/common/upstream/subset_lb.h
  source/common/upstream/upstream_impl.h
  test/common/upstream/BUILD
  test/common/upstream/least_request_load_balancer_fuzz_test.cc
  test/common/upstream/load_balancer_benchmark.cc
  test/common/upstream/load_balancer_impl_test.cc
  test/common/upstream/load_balancer_simulation_test.cc
  test/common/upstream/round_robin_load_balancer_fuzz.proto
  test/common/upstream/round_robin_load_balancer_fuzz_test.cc
  test/common/upstream/subset_lb_test.cc
  test/common/upstream/zone_aware_load_balancer_fuzz_base.h
  test/integration/stats_integration_test.cc
  test/mocks/upstream/cluster_info.cc
  test/mocks/upstream/cluster_info.h
Labels: deps

#18249 bazel: Update googleurl
  bazel/external/googleurl.patch
  bazel/repository_locations.bzl
  envoy/common/platform.h
Labels: deps
