Repository envoyproxy/envoy, pull requests merged in 2021-04, with the labels that each got.

#15810 [build] bump fuzzing dependencies
  bazel/envoy_test.bzl
  bazel/repository_locations.bzl
Labels: deps

#15753 http3: support Http3Options for downstream
  api/envoy/config/core/v3/protocol.proto
  api/envoy/config/core/v4alpha/protocol.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  api/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  docs/root/configuration/http/http_conn_man/response_code_details.rst
  generated_api_shadow/envoy/config/core/v3/protocol.proto
  generated_api_shadow/envoy/config/core/v4alpha/protocol.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  generated_api_shadow/envoy/extensions/filters/network/http_connection_manager/v4alpha/http_connection_manager.proto
  include/envoy/http/codec.h
  include/envoy/upstream/upstream.h
  source/common/http/BUILD
  source/common/http/codec_client.cc
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http2/codec_impl.cc
  source/common/http/http3/BUILD
  source/common/http/http3/codec_stats.h
  source/common/http/utility.cc
  source/common/http/utility.h
  source/common/quic/BUILD
  source/common/quic/codec_impl.cc
  source/common/quic/codec_impl.h
  source/common/quic/envoy_quic_client_session.cc
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_client_stream.h
  source/common/quic/envoy_quic_server_session.cc
  source/common/quic/envoy_quic_server_session.h
  source/common/quic/envoy_quic_server_stream.cc
  source/common/quic/envoy_quic_server_stream.h
  source/common/quic/envoy_quic_stream.h
  source/common/quic/envoy_quic_utils.cc
  source/common/quic/envoy_quic_utils.h
  source/common/quic/quic_filter_manager_connection_impl.h
  source/common/upstream/BUILD
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/extensions/filters/network/http_connection_manager/BUILD
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  test/common/http/header_utility_test.cc
  test/common/quic/envoy_quic_client_session_test.cc
  test/common/quic/envoy_quic_client_stream_test.cc
  test/common/quic/envoy_quic_server_session_test.cc
  test/common/quic/envoy_quic_server_stream_test.cc
  test/common/quic/envoy_quic_utils_test.cc
  test/integration/BUILD
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/http_integration.cc
  test/integration/protocol_integration_test.cc
  test/mocks/upstream/cluster_info.cc
  test/mocks/upstream/cluster_info.h
Labels: api

#15844 [Windows] Remove `fails_on_windows` from `quic_protocol_integration_test`
  test/integration/BUILD
Labels: area/test flakes, area/windows

#15638 [Windows] Improve SCM error logging
  docs/root/start/quick-start/run-envoy.rst
  source/common/common/BUILD
  source/common/common/base_logger.h
  source/common/common/win32/event_logger_impl.cc
  source/common/common/win32/event_logger_impl.h
  source/exe/BUILD
  source/exe/win32/service_base.cc
  source/exe/win32/service_base.h
Labels: area/windows

#15594 repokitteh: support random assignment from teams via /assign-from.
  ci/repokitteh/modules/ownerscheck.star
  source/docs/repokitteh.md
Labels: rk:blessed

#15855 Revert "build(deps): bump docutils from 0.16 to 0.17 in /docs (#15835)"
  docs/requirements.txt
Labels: deps

#15812 test: changing waitForEndStream to fail if it takes 30s
  test/extensions/clusters/aggregate/cluster_integration_test.cc
  test/extensions/filters/http/adaptive_concurrency/adaptive_concurrency_filter_integration_test.cc
  test/extensions/filters/http/admission_control/admission_control_integration_test.cc
  test/extensions/filters/http/aws_lambda/aws_lambda_filter_integration_test.cc
  test/extensions/filters/http/buffer/buffer_filter_integration_test.cc
  test/extensions/filters/http/cache/cache_filter_integration_test.cc
  test/extensions/filters/http/cdn_loop/filter_integration_test.cc
  test/extensions/filters/http/cors/cors_filter_integration_test.cc
  test/extensions/filters/http/csrf/csrf_filter_integration_test.cc
  test/extensions/filters/http/decompressor/decompressor_filter_integration_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/fault/fault_filter_integration_test.cc
  test/extensions/filters/http/grpc_http1_reverse_bridge/reverse_bridge_integration_test.cc
  test/extensions/filters/http/grpc_json_transcoder/grpc_json_transcoder_integration_test.cc
  test/extensions/filters/http/grpc_web/grpc_web_filter_integration_test.cc
  test/extensions/filters/http/jwt_authn/filter_integration_test.cc
  test/extensions/filters/http/lua/lua_integration_test.cc
  test/extensions/filters/http/ratelimit/ratelimit_integration_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
  test/extensions/filters/http/squash/squash_filter_integration_test.cc
  test/extensions/filters/http/tap/tap_filter_integration_test.cc
  test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/retry/host/previous_hosts/integration_test.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
  test/integration/BUILD
  test/integration/alpn_integration_test.cc
  test/integration/alpn_selection_integration_test.cc
  test/integration/cluster_upstream_extension_integration_test.cc
  test/integration/direct_response_integration_test.cc
  test/integration/drain_close_integration_test.cc
  test/integration/extension_discovery_integration_test.cc
  test/integration/filter_manager_integration_test.cc
  test/integration/http2_flood_integration_test.cc
  test/integration/http2_integration_test.cc
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/http_subset_lb_integration_test.cc
  test/integration/http_timeout_integration_test.cc
  test/integration/idle_timeout_integration_test.cc
  test/integration/integration_stream_decoder.cc
  test/integration/integration_stream_decoder.h
  test/integration/integration_test.cc
  test/integration/load_stats_integration_test.cc
  test/integration/local_reply_integration_test.cc
  test/integration/multiplexed_upstream_integration_test.cc
  test/integration/overload_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/quic_http_integration_test.cc
  test/integration/redirect_integration_test.cc
  test/integration/scoped_rds_integration_test.cc
  test/integration/tcp_tunneling_integration_test.cc
  test/integration/transport_socket_match_integration_test.cc
  test/integration/uds_integration_test.cc
  test/integration/websocket_integration_test.cc
  test/integration/xds_integration_test.cc
  test/integration/xfcc_integration_test.cc
Labels: waiting

#15877 [Windows] build cleanups
  .bazelrc
  bazel/external/wee8.BUILD
  bazel/foreign_cc/BUILD
  ci/run_envoy_docker.sh
  ci/windows_ci_steps.sh
Labels: area/build, area/windows

#15820 Windows: Add note regarding the usage of `./ci/run_envoy_docker`
  bazel/README.md
Labels: area/docs, area/windows

#15972 test: making assert required
  bazel/repositories.bzl
  ci/filter_example_setup.sh
  test/extensions/filters/http/composite/composite_filter_integration_test.cc
  test/integration/extension_discovery_integration_test.cc
  test/integration/integration_stream_decoder.h
  test/integration/quic_http_integration_test.cc
Labels: deps

#15992 build-tools: Bump build tools in repository_locations.bzl
  bazel/repository_locations.bzl
Labels: deps

#16037 [delta xds]: remove cached nonces on reconnection
  source/common/config/new_grpc_mux_impl.cc
  source/common/config/new_grpc_mux_impl.h
  source/common/config/pausable_ack_queue.cc
  source/common/config/pausable_ack_queue.h
  test/common/config/new_grpc_mux_impl_test.cc
Labels: api

#15935 Enable header modifications with body in "buffered" mode
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/mutation_utils.cc
  source/extensions/filters/http/ext_proc/mutation_utils.h
  source/extensions/filters/http/ext_proc/processor_state.cc
  source/extensions/filters/http/ext_proc/processor_state.h
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/extensions/filters/http/ext_proc/ordering_test.cc
Labels: waiting

#16038 Bring parity to the docker images on the install docs pages
  docs/root/start/install.rst
Labels: area/docs, area/windows

#16097 api: Update xds_protocol doc to remove v2 and cleanup
  api/xds_protocol.rst
  docs/root/_include/ads.yaml
Labels: deps

#16163 docs: Update refs: v2 -> v3
  docs/root/api/client_features.rst
  docs/root/configuration/http/http_conn_man/stats.rst
  docs/root/configuration/http/http_filters/aws_lambda_filter.rst
  docs/root/configuration/http/http_filters/fault_filter.rst
  docs/root/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.rst
  docs/root/configuration/listeners/udp_filters/dns_filter.rst
  docs/root/configuration/observability/access_log/overview.rst
  docs/root/configuration/operations/tools/router_check.rst
  docs/root/configuration/overview/versioning.rst
  docs/root/configuration/overview/xds_api.rst
  docs/root/intro/arch_overview/advanced/attributes.rst
  docs/root/intro/arch_overview/http/http_routing.rst
  docs/root/intro/arch_overview/upstream/load_balancing/excluded.rst
  docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
  docs/root/operations/certificates.rst
  docs/root/operations/tools/config_generator.rst
  docs/root/operations/tools/route_table_check_tool.rst
Labels: api

#16156 python: Revert buggy gitpython version
  docs/requirements.txt
  tools/deprecate_version/requirements.txt
Labels: deps
