Repository envoyproxy/envoy, pull requests merged in 2021-08, with the labels that each got.

#17577 conn pool: default enable runtime feature `conn_pool_delete_when_idle`
  source/common/runtime/runtime_features.cc
Labels: waiting

#17380 dist: Add distro verify tool
  tools/base/checker.py
  tools/distribution/BUILD
  tools/distribution/tests/test_verify.py
  tools/distribution/verify.py
Labels: deps

#14681 upstream: Implement WRSQ Scheduler
  envoy/upstream/BUILD
  envoy/upstream/scheduler.h
  source/common/upstream/BUILD
  source/common/upstream/edf_scheduler.h
  source/common/upstream/wrsq_scheduler.h
  test/common/upstream/BUILD
  test/common/upstream/scheduler_benchmark.cc
  test/common/upstream/wrsq_scheduler_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: no stalebot

#17400 Enable load balancing policy extensions
  api/envoy/config/cluster/v3/cluster.proto
  api/envoy/config/cluster/v4alpha/cluster.proto
  envoy/upstream/load_balancer.h
  envoy/upstream/load_balancer_type.h
  envoy/upstream/upstream.h
  generated_api_shadow/envoy/config/cluster/v3/cluster.proto
  generated_api_shadow/envoy/config/cluster/v4alpha/cluster.proto
  source/common/upstream/BUILD
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/load_balancer_factory_base.h
  source/common/upstream/subset_lb.cc
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  test/common/upstream/BUILD
  test/common/upstream/cluster_manager_impl_test.cc
  test/integration/http_subset_lb_integration_test.cc
  test/mocks/upstream/cluster_info.h
Labels: v2-freeze

#17741 tooling: Add Github release manager
  tools/github/release/BUILD
  tools/github/release/manager.py
  tools/github/release/tests/test_manager.py
Labels: deps

#17887 kafka: add librdkafka dependency, provide upstream kafka client imple…
  bazel/foreign_cc/BUILD
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  contrib/kafka/filters/network/source/mesh/BUILD
  contrib/kafka/filters/network/source/mesh/command_handlers/produce.h
  contrib/kafka/filters/network/source/mesh/filter.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_client.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.cc
  contrib/kafka/filters/network/source/mesh/upstream_kafka_client_impl.h
  contrib/kafka/filters/network/source/mesh/upstream_kafka_facade.cc
  contrib/kafka/filters/network/test/mesh/BUILD
  contrib/kafka/filters/network/test/mesh/kafka_mocks.h
  contrib/kafka/filters/network/test/mesh/upstream_kafka_client_impl_unit_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: deps

#17813 [Backport 1.19] Enable Windows workers (#17555)
  docs/root/intro/arch_overview/intro/threading_model.rst
  docs/root/version_history/current.rst
  source/server/listener_impl.cc
  test/integration/integration_test.cc
Labels: area/windows, backport/review

#17814 [Backport 1.18] Enable Windows workers (#17555)
  docs/root/intro/arch_overview/intro/threading_model.rst
  docs/root/version_history/current.rst
  source/server/listener_impl.cc
  test/integration/integration_test.cc
Labels: area/windows, backport/review
