Repository envoyproxy/envoy, pull requests merged in 2021-01, with the labels that each got.

#14405 [gzip]: allow gzip to work w/ http2 backend w/o content-length
  docs/root/version_history/current.rst
  source/common/runtime/runtime_features.cc
  source/extensions/filters/http/common/compressor/compressor.cc
  test/extensions/filters/http/common/compressor/BUILD
  test/extensions/filters/http/common/compressor/compressor_filter_test.cc
Labels: api

#14134 Step 2: Bump bazel 3.7.2 in envoy build tree
  .bazelrc
  .bazelversion
  .devcontainer/Dockerfile
  bazel/repository_locations.bzl
  ci/flaky_test/requirements.txt
  examples/wasm-cc/docker-compose-wasm.yaml
Labels: deps

#14147 build: update grpc to 1.34.0
  bazel/dependency_imports.bzl
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  bazel/upb.patch
  source/common/grpc/async_client_impl.cc
  source/extensions/transport_sockets/alts/config.cc
  test/common/grpc/grpc_client_integration_test.cc
  test/extensions/transport_sockets/alts/alts_integration_test.cc
  test/extensions/transport_sockets/alts/tsi_handshaker_test.cc
  test/server/server_corpus/grpc_arg_pointer
Labels: deps

#14571 deps: update PGV
  api/bazel/repository_locations.bzl
  generated_api_shadow/bazel/repository_locations.bzl
Labels: deps

#14608 Bump envoy-build to current images
  .bazelrc
  .devcontainer/Dockerfile
  bazel/repository_locations.bzl
  examples/wasm-cc/docker-compose-wasm.yaml
Labels: deps

#14385 Implement request header processing in ext_proc
  api/envoy/service/ext_proc/v3alpha/external_processor.proto
  docs/root/configuration/http/http_filters/ext_proc_filter.rst
  generated_api_shadow/envoy/service/ext_proc/v3alpha/external_processor.proto
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/router/BUILD
  source/common/router/header_parser.cc
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_proc/BUILD
  source/extensions/filters/http/ext_proc/config.cc
  source/extensions/filters/http/ext_proc/config.h
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/mutation_utils.cc
  source/extensions/filters/http/ext_proc/mutation_utils.h
  test/common/http/header_utility_test.cc
  test/extensions/filters/http/ext_proc/BUILD
  test/extensions/filters/http/ext_proc/config_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/extensions/filters/http/ext_proc/mock_server.cc
  test/extensions/filters/http/ext_proc/mock_server.h
  test/extensions/filters/http/ext_proc/mutation_utils_test.cc
  test/extensions/filters/http/ext_proc/utils.cc
  test/extensions/filters/http/ext_proc/utils.h
Labels: no stalebot

#14624 1.17.0 release
  RELEASES.md
  VERSION
  api/envoy/config/filter/http/ext_authz/v2/ext_authz.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/filter/http/ext_authz/v2/ext_authz.proto
  tools/code_format/check_format.py
Labels: api, v2-freeze

#14653 ci: fix docs tag build
  .azure-pipelines/pipelines.yml
Labels: backport/review

#13599 HTTP health checker: handle GOAWAY from HTTP2 upstreams
  docs/root/version_history/current.rst
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/health_checker_impl.cc
  source/common/upstream/health_checker_impl.h
  test/common/http/http2/codec_impl_test.cc
  test/common/upstream/health_check_fuzz_test_utils.cc
  test/common/upstream/health_check_fuzz_test_utils.h
  test/common/upstream/health_checker_impl_test.cc
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/health_check_integration_test.cc
Labels: api, deps

#14569 upstream: force a full rebuild on host weight changes
  docs/root/version_history/current.rst
  source/common/runtime/runtime_features.cc
  source/common/upstream/eds.cc
  source/common/upstream/upstream_impl.cc
  test/common/upstream/BUILD
  test/common/upstream/eds_test.cc
Labels: no stalebot

#14585 grpc-json-transcoder: support root path
  bazel/repository_locations.bzl
  test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
  test/proto/bookstore.proto
Labels: deps

#14117 v3 packages updates for omit_canary_hosts proto
  api/BUILD
  api/envoy/config/retry/omit_canary_hosts/v3/BUILD
  api/envoy/config/retry/omit_canary_hosts/v3/omit_canary_hosts.proto
  api/versioning/BUILD
  docs/root/api-v3/config/retry/retry.rst
  generated_api_shadow/envoy/config/retry/omit_canary_hosts/v3/BUILD
  generated_api_shadow/envoy/config/retry/omit_canary_hosts/v3/omit_canary_hosts.proto
Labels: stale

#14676 [tls] add missing built in cipher stat names
  source/extensions/transport_sockets/tls/context_impl.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: backport/review

#14703 tls: add missing stats for signature algorithms.
  source/extensions/transport_sockets/tls/context_impl.cc
Labels: backport/review

#14443 http2: Flip the upstream H2 frame flood and abuse checks to ON by default
  docs/root/version_history/current.rst
  source/common/runtime/runtime_features.cc
  test/integration/http2_flood_integration_test.cc
  test/integration/http2_integration_test.cc
Labels: no stalebot

#14673 Fix the emsdk patching.
  bazel/repositories.bzl
Labels: deps

#14689 Add error_state to all config dump resources
  api/envoy/admin/v3/config_dump.proto
  api/envoy/admin/v4alpha/config_dump.proto
  generated_api_shadow/envoy/admin/v3/config_dump.proto
  generated_api_shadow/envoy/admin/v4alpha/config_dump.proto
Labels: v2-freeze

#14750 filters: Add dependencies.proto
  api/BUILD
  api/envoy/extensions/filters/common/dependency/v3/BUILD
  api/envoy/extensions/filters/common/dependency/v3/dependency.proto
  api/versioning/BUILD
  docs/root/api-v3/common_messages/common_messages.rst
  generated_api_shadow/envoy/extensions/filters/common/dependency/v3/BUILD
  generated_api_shadow/envoy/extensions/filters/common/dependency/v3/dependency.proto
Labels: v2-freeze

#14799 scaled range timer: guard against queue deletion during timer fire
  source/common/event/scaled_range_timer_manager_impl.cc
  source/common/event/scaled_range_timer_manager_impl.h
  test/common/event/scaled_range_timer_manager_impl_test.cc
Labels: backport/review

#14731 Update flaky test script to print more details and detect flaky exceptions and timeouts
  ci/flaky_test/process_xml.py
  ci/run_envoy_docker.sh
Labels: area/build

#14858 Changes the link to download Kafka
  bazel/repository_locations.bzl
  tools/dependency/validate.py
Labels: deps

#14837 deps: update datadog tracer to v1.2.1
  bazel/repository_locations.bzl
  source/extensions/tracers/datadog/datadog_tracer_impl.cc
  source/extensions/tracers/datadog/datadog_tracer_impl.h
  test/extensions/tracers/datadog/datadog_tracer_impl_test.cc
Labels: deps
