Repository envoyproxy/envoy, pull requests merged in 2021-06, with the labels that each got.

#16750 tools: adding slackbot for PR notifications
  .github/actions/pr_notifier/pr_notifier.py
  .github/actions/pr_notifier/requirements.txt
  .github/dependabot.yml
  .github/workflows/pr_notifier.yml
Labels: deps

#16712 Tools: update release date checker to check for release date vs. last commit of release
  api/bazel/repository_locations.bzl
  bazel/repository_locations.bzl
  generated_api_shadow/bazel/repository_locations.bzl
  tools/dependency/release_dates.py
  tools/dependency/requirements.txt
Labels: deps

#16787 tools: hash fix
  .github/actions/pr_notifier/requirements.txt
Labels: deps

#16339 Add a windows sample
  ci/do_ci.sh
  ci/verify_examples.sh
  docs/root/start/sandboxes/index.rst
  docs/root/start/sandboxes/setup.rst
  docs/root/start/sandboxes/win32_front_proxy.rst
  examples/win32-front-proxy/Dockerfile-frontenvoy
  examples/win32-front-proxy/Dockerfile-service
  examples/win32-front-proxy/README.md
  examples/win32-front-proxy/docker-compose.yaml
  examples/win32-front-proxy/front-envoy.yaml
  examples/win32-front-proxy/service-envoy.yaml
  examples/win32-front-proxy/service.py
  examples/win32-front-proxy/setup_python.ps1
  examples/win32-front-proxy/start_envoy.ps1
  examples/win32-front-proxy/start_service.ps1
Labels: area/windows

#16643 Windows ci add bazel args
  bazel/README.md
  ci/README.md
  ci/windows_ci_steps.sh
  test/extensions/http/header_formatters/preserve_case/BUILD
  test/extensions/resource_monitors/injected_resource/BUILD
  test/extensions/transport_sockets/tls/cert_validator/spiffe/BUILD
Labels: area/build, area/windows, backport/review

#16029 abseil: force using non-std types
  bazel/abseil.patch
  bazel/repositories.bzl
  source/common/common/stl_helpers.h
  source/common/config/context_provider_impl.h
  source/common/formatter/substitution_formatter.cc
  source/common/formatter/substitution_formatter.h
  source/common/json/json_internal.cc
  source/common/local_info/local_info_impl.h
  source/common/stats/tag_extractor_impl.cc
  source/common/stream_info/stream_info_impl.h
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/foreign.cc
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/common/wasm/wasm_vm.cc
  source/extensions/common/wasm/wasm_vm.h
  source/extensions/filters/http/set_metadata/set_metadata_filter.cc
  source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
  test/common/config/context_provider_impl_test.cc
  test/common/http/path_utility_fuzz_test.cc
  test/common/router/config_impl_test.cc
  test/common/stream_info/test_util.h
  test/common/upstream/load_balancer_benchmark.cc
  test/common/upstream/upstream_impl_test.cc
  test/config_test/config_test.cc
  test/extensions/bootstrap/wasm/wasm_speed_test.cc
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/io_socket/user_space/io_handle_impl_test.cc
  test/extensions/stats_sinks/wasm/wasm_stat_sink_test.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  test/integration/sds_dynamic_integration_test.cc
  test/integration/upstreams/per_host_upstream_config.h
  test/mocks/stream_info/mocks.cc
  test/test_common/file_system_for_test.h
  test/test_common/wasm_base.h
  tools/code_format/check_format.py
  tools/code_format/check_format_test_helper.py
Labels: deps

#16806 quiche: update QUICHE tar ball
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
  source/common/quic/envoy_quic_client_connection.cc
  source/common/quic/envoy_quic_dispatcher.cc
  source/common/quic/envoy_quic_server_connection.cc
  source/common/quic/envoy_quic_server_connection.h
  source/common/quic/envoy_quic_utils.cc
  source/common/quic/envoy_quic_utils.h
  source/common/quic/platform/BUILD
  source/common/quic/platform/quic_containers_impl.h
  source/common/quic/platform/quic_prefetch_impl.h
  source/common/quic/platform/quiche_text_utils_impl.h
  source/common/quic/platform/spdy_containers_impl.h
  test/common/network/udp_listener_impl_batch_writer_test.cc
  test/common/quic/active_quic_listener_test.cc
  test/common/quic/envoy_quic_client_session_test.cc
  test/common/quic/envoy_quic_client_stream_test.cc
  test/common/quic/envoy_quic_dispatcher_test.cc
  test/common/quic/envoy_quic_server_session_test.cc
  test/common/quic/envoy_quic_server_stream_test.cc
  test/common/quic/platform/BUILD
  test/common/quic/platform/quic_platform_test.cc
  test/common/quic/platform/quic_sleep_impl.h
  test/config/utility.h
  test/integration/quic_http_integration_test.cc
Labels: waiting

#16361 protos: v2 squash.proto removal
  api/envoy/extensions/filters/http/squash/v3/BUILD
  generated_api_shadow/envoy/extensions/filters/http/squash/v3/BUILD
  tools/proto_format/proto_sync.py
Labels: v2-freeze

#16858 Adds a user to `envoy-windows` image
  ci/Dockerfile-envoy-windows
  docs/root/version_history/current.rst
Labels: area/docker, area/examples, area/windows

#16742 add rps_threshold & max_rejection_probability
  api/envoy/extensions/filters/http/admission_control/v3alpha/admission_control.proto
  docs/root/configuration/http/http_filters/admission_control_filter.rst
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/extensions/filters/http/admission_control/v3alpha/admission_control.proto
  source/common/runtime/runtime_protos.h
  source/extensions/filters/http/admission_control/admission_control.cc
  source/extensions/filters/http/admission_control/admission_control.h
  source/extensions/filters/http/admission_control/thread_local_controller.cc
  source/extensions/filters/http/admission_control/thread_local_controller.h
  test/extensions/filters/http/admission_control/admission_control_filter_test.cc
  test/extensions/filters/http/admission_control/admission_control_integration_test.cc
  test/extensions/filters/http/admission_control/config_test.cc
  test/extensions/filters/http/admission_control/controller_test.cc
Labels: waiting

#16687 deps: update abseil and grpc dependencies
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: deps

#15519 Connection Limit Filter
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/filters/network/connection_limit/v3/BUILD
  api/envoy/extensions/filters/network/connection_limit/v3/connection_limit.proto
  api/versioning/BUILD
  docs/root/configuration/listeners/network_filters/connection_limit_filter.rst
  docs/root/configuration/listeners/network_filters/network_filters.rst
  docs/root/intro/arch_overview/listeners/connection_limiting.rst
  docs/root/intro/arch_overview/listeners/listeners_toc.rst
  docs/root/version_history/current.rst
  generated_api_shadow/BUILD
  generated_api_shadow/envoy/extensions/filters/network/connection_limit/v3/BUILD
  generated_api_shadow/envoy/extensions/filters/network/connection_limit/v3/connection_limit.proto
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/filters/network/connection_limit/BUILD
  source/extensions/filters/network/connection_limit/config.cc
  source/extensions/filters/network/connection_limit/config.h
  source/extensions/filters/network/connection_limit/connection_limit.cc
  source/extensions/filters/network/connection_limit/connection_limit.h
  source/extensions/filters/network/well_known_names.h
  test/extensions/filters/network/connection_limit/BUILD
  test/extensions/filters/network/connection_limit/connection_limit_integration_test.cc
  test/extensions/filters/network/connection_limit/connection_limit_test.cc
Labels: deps

#16703 extensions: Graphite stats sink
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/stat_sinks/graphite_statsd/v3/BUILD
  api/envoy/extensions/stat_sinks/graphite_statsd/v3/graphite_statsd.proto
  api/versioning/BUILD
  docs/root/api-v3/config/config.rst
  docs/root/api-v3/config/stat_sinks/stat_sinks.rst
  docs/root/configuration/observability/observability.rst
  docs/root/configuration/observability/stat_sinks/graphite_statsd_stat_sink.rst
  docs/root/configuration/observability/stat_sinks/stat_sinks.rst
  docs/root/configuration/observability/stat_sinks/wasm_stat_sink.rst
  docs/root/configuration/other_features/other_features.rst
  docs/root/version_history/current.rst
  generated_api_shadow/BUILD
  generated_api_shadow/envoy/extensions/stat_sinks/graphite_statsd/v3/BUILD
  generated_api_shadow/envoy/extensions/stat_sinks/graphite_statsd/v3/graphite_statsd.proto
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/stat_sinks/common/statsd/BUILD
  source/extensions/stat_sinks/common/statsd/statsd.cc
  source/extensions/stat_sinks/common/statsd/statsd.h
  source/extensions/stat_sinks/common/statsd/tag_formats.cc
  source/extensions/stat_sinks/common/statsd/tag_formats.h
  source/extensions/stat_sinks/graphite_statsd/BUILD
  source/extensions/stat_sinks/graphite_statsd/config.cc
  source/extensions/stat_sinks/graphite_statsd/config.h
  source/extensions/stat_sinks/well_known_names.h
  test/extensions/stats_sinks/common/statsd/udp_statsd_test.cc
  test/extensions/stats_sinks/graphite_statsd/BUILD
  test/extensions/stats_sinks/graphite_statsd/config_test.cc
  test/per_file_coverage.sh
Labels: deps, v2-freeze

#13788 bazel: Add pre-compiled clang header poc
  .bazelrc
  bazel/BUILD
  bazel/envoy_build_system.bzl
  bazel/envoy_library.bzl
  bazel/envoy_pch.bzl
  bazel/envoy_test.bzl
  bazel/pch.bzl
  source/common/common/BUILD
  test/BUILD
  tools/code_format/envoy_build_fixer.py
Labels: area/build

#15229 docs: Move docs/build.sh to bazel
  docs/BUILD
  docs/build.sh
  tools/docs/BUILD
  tools/docs/sphinx_runner.py
  tools/docs/tests/test_sphinx_runner.py
Labels: api, deps
