Repository envoyproxy/envoy, pull requests merged in 2021-12, with the labels that each got.

#18363 accesslogs: add CEL-based extension filter
  CODEOWNERS
  api/BUILD
  api/envoy/config/accesslog/v3/accesslog.proto
  api/envoy/extensions/access_loggers/filters/cel/v3/BUILD
  api/envoy/extensions/access_loggers/filters/cel/v3/cel.proto
  api/versioning/BUILD
  bazel/repository_locations.bzl
  docs/root/api-v3/config/accesslog/accesslog.rst
  docs/root/api-v3/config/accesslog/filters.rst
  docs/root/api-v3/config/accesslog/filters/filters.rst
  docs/root/api-v3/config/config.rst
  docs/root/version_history/current.rst
  source/extensions/access_loggers/filters/cel/BUILD
  source/extensions/access_loggers/filters/cel/cel.cc
  source/extensions/access_loggers/filters/cel/cel.h
  source/extensions/access_loggers/filters/cel/config.cc
  source/extensions/access_loggers/filters/cel/config.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  test/common/access_log/BUILD
  test/common/access_log/access_log_impl_test.cc
  tools/extensions/extensions_check.py
Labels: deps

#17880 wasm: Fix potential segfault when reading filter_state
  source/extensions/common/wasm/context.cc
Labels: waiting

#18823 api: MetaProtocol Proxy
  api/BUILD
  api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/action/v3/BUILD
  api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/action/v3/action.proto
  api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/v3/BUILD
  api/envoy/extensions/filters/network/meta_protocol_proxy/matcher/v3/matcher.proto
  api/envoy/extensions/filters/network/meta_protocol_proxy/v3/BUILD
  api/envoy/extensions/filters/network/meta_protocol_proxy/v3/meta_protocol_proxy.proto
  api/envoy/extensions/filters/network/meta_protocol_proxy/v3/route.proto
  api/versioning/BUILD
Labels: api, v2-freeze

#19203 grpcJsonTranscoder: add match_unregistered_custom_verb
  api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto
  bazel/repository_locations.bzl
  docs/root/version_history/current.rst
  source/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter.cc
  test/extensions/filters/http/grpc_json_transcoder/json_transcoder_filter_test.cc
  test/proto/bookstore.proto
Labels: v2-freeze

#19259 dep: update com_github_google_perfetto: v22.1 (current: v21.0)
  bazel/repository_locations.bzl
Labels: deps

#18767 deps: Bump `com_github_c_ares_c_ares` -> 1.18.1
  bazel/repository_locations.bzl
Labels: waiting
