Repository envoyproxy/envoy, pull requests merged in 2021-11, with the labels that each got.

#18353 oauth2 filter: saving id_token and refresh_token in the cookie if they are provided
  docs/root/configuration/http/http_filters/oauth2_filter.rst
  docs/root/version_history/current.rst
  source/extensions/filters/http/oauth2/filter.cc
  source/extensions/filters/http/oauth2/filter.h
  source/extensions/filters/http/oauth2/oauth.h
  source/extensions/filters/http/oauth2/oauth_client.cc
  source/extensions/filters/http/oauth2/oauth_response.proto
  test/extensions/filters/http/oauth2/filter_test.cc
  test/extensions/filters/http/oauth2/oauth_test.cc
Labels: api

#18668 stats: Add universal stats tag from CLI
  api/envoy/admin/v3/server_info.proto
  docs/root/operations/cli.rst
  envoy/server/options.h
  source/common/config/utility.cc
  source/common/config/utility.h
  source/common/config/well_known_names.cc
  source/common/config/well_known_names.h
  source/common/stats/BUILD
  source/common/stats/tag_producer_impl.cc
  source/common/stats/tag_producer_impl.h
  source/common/stats/tag_utility.cc
  source/common/stats/tag_utility.h
  source/server/BUILD
  source/server/config_validation/server.cc
  source/server/options_impl.cc
  source/server/options_impl.h
  source/server/server.cc
  test/common/config/utility_test.cc
  test/common/stats/tag_producer_impl_test.cc
  test/mocks/server/options.cc
  test/mocks/server/options.h
  test/server/options_impl_test.cc
Labels: api

#18306 OpenTelemetry proto formatter for access logging
  source/common/formatter/substitution_formatter.cc
  source/extensions/access_loggers/open_telemetry/BUILD
  source/extensions/access_loggers/open_telemetry/access_log_impl.cc
  source/extensions/access_loggers/open_telemetry/access_log_impl.h
  source/extensions/access_loggers/open_telemetry/substitution_formatter.cc
  source/extensions/access_loggers/open_telemetry/substitution_formatter.h
  test/extensions/access_loggers/open_telemetry/BUILD
  test/extensions/access_loggers/open_telemetry/access_log_impl_test.cc
  test/extensions/access_loggers/open_telemetry/grpc_access_log_impl_test.cc
  test/extensions/access_loggers/open_telemetry/substitution_formatter_speed_test.cc
  test/extensions/access_loggers/open_telemetry/substitution_formatter_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: waiting

#19036 tcp: fix overenthusiastic bounds on the new pool
  api/envoy/config/cluster/v3/circuit_breaker.proto
  docs/root/version_history/current.rst
  source/common/conn_pool/conn_pool_base.cc
  source/common/conn_pool/conn_pool_base.h
  source/common/tcp/conn_pool.h
  test/integration/tcp_proxy_integration_test.cc
Labels: backport/review
