Repository envoyproxy/envoy, pull requests merged in 2021-03, with the labels that each got.

#15210 wasm: refactor common codes around configurations
  source/common/protobuf/utility.h
  source/extensions/access_loggers/wasm/config.cc
  source/extensions/bootstrap/wasm/config.cc
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/context.h
  source/extensions/common/wasm/plugin.cc
  source/extensions/common/wasm/plugin.h
  source/extensions/common/wasm/wasm.cc
  source/extensions/common/wasm/wasm.h
  source/extensions/common/wasm/wasm_extension.cc
  source/extensions/common/wasm/wasm_extension.h
  source/extensions/filters/http/wasm/wasm_filter.cc
  source/extensions/filters/http/wasm/wasm_filter.h
  source/extensions/filters/network/wasm/wasm_filter.cc
  source/extensions/stat_sinks/wasm/BUILD
  source/extensions/stat_sinks/wasm/config.cc
  source/extensions/stat_sinks/wasm/wasm_stat_sink_impl.h
  test/extensions/bootstrap/wasm/wasm_speed_test.cc
  test/extensions/bootstrap/wasm/wasm_test.cc
  test/extensions/common/wasm/wasm_speed_test.cc
  test/extensions/common/wasm/wasm_test.cc
  test/extensions/filters/network/wasm/wasm_filter_test.cc
  test/test_common/wasm_base.h
Labels: deps

#15022 ext_proc: Implement request and response body processing
  api/envoy/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto
  generated_api_shadow/envoy/extensions/filters/http/ext_proc/v3alpha/ext_proc.proto
  source/extensions/filters/http/ext_proc/BUILD
  source/extensions/filters/http/ext_proc/client.h
  source/extensions/filters/http/ext_proc/client_impl.cc
  source/extensions/filters/http/ext_proc/client_impl.h
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/mutation_utils.cc
  source/extensions/filters/http/ext_proc/mutation_utils.h
  test/extensions/filters/http/ext_proc/client_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/extensions/filters/http/ext_proc/mock_server.h
  test/extensions/filters/http/ext_proc/mutation_utils_test.cc
  test/extensions/filters/http/ext_proc/ordering_test.cc
Labels: api

#14352 [Windows] Onboard Envoy to SCM
  bazel/envoy_binary.bzl
  docs/root/start/quick-start/run-envoy.rst
  source/exe/BUILD
  source/exe/main.cc
  source/exe/main_common.cc
  source/exe/main_common.h
  source/exe/win32/service_base.cc
  source/exe/win32/service_base.h
  source/exe/win32/service_status.h
  test/exe/BUILD
  test/exe/main_common_test.cc
  test/exe/win32_scm_test.cc
Labels: area/windows, enhancement

#15311 wasm: fix crash on HTTP callout to a bad cluster.
  source/extensions/common/wasm/context.cc
  test/extensions/filters/http/wasm/test_data/async_call_rust.rs
  test/extensions/filters/http/wasm/test_data/test_async_call_cpp.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
Labels: backport/review

#15427 docs: (take 2) Move external deps rst generation and cve scan to bazel
  api/bazel/BUILD
  bazel/BUILD
  ci/do_ci.sh
  docs/build.sh
  generated_api_shadow/bazel/BUILD
  tools/dependency/BUILD
  tools/dependency/exports.py
  tools/dependency/generate_external_dep_rst.py
  tools/dependency/ossf_scorecard.py
  tools/dependency/release_dates.py
  tools/dependency/release_dates.sh
  tools/dependency/utils.py
  tools/extensions/generate_extension_rst.py
Labels: deps

#15452 repokitteh: use randint() for random assignment.
  ci/repokitteh/modules/ownerscheck.star
Labels: rk:blessed

#15508 protos: Remove -x from bash script
  tools/proto_format/proto_format.sh
Labels: waiting

#15186 api: Adding API major.minor.patch version
  API_VERSION
  BUILD
  source/common/version/BUILD
  source/common/version/api_version.h
  source/common/version/api_version_struct.h
  test/common/common/BUILD
  test/common/common/api_version_test.cc
  tools/api_versioning/BUILD
  tools/api_versioning/generate_api_version_header.py
  tools/api_versioning/generate_api_version_header_test.py
Labels: api

#13770 Macro wrapper for memcpy
  source/common/buffer/buffer_impl.cc
  source/common/buffer/buffer_impl.h
  source/common/chromium_url/BUILD
  source/common/chromium_url/url_canon.h
  source/common/common/BUILD
  source/common/common/hash.h
  source/common/common/mem_block_builder.h
  source/common/common/safe_memcpy.h
  source/common/common/utility.cc
  source/common/grpc/BUILD
  source/common/grpc/common.cc
  source/common/http/http2/codec_impl.cc
  source/common/network/BUILD
  source/common/network/address_impl.cc
  source/common/network/address_impl.h
  source/common/network/cidr_range.cc
  source/extensions/common/proxy_protocol/proxy_protocol_header.cc
  source/extensions/common/wasm/BUILD
  source/extensions/common/wasm/context.cc
  source/extensions/common/wasm/foreign.cc
  source/extensions/filters/listener/proxy_protocol/BUILD
  source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
  source/extensions/filters/network/dubbo_proxy/BUILD
  source/extensions/filters/network/dubbo_proxy/buffer_helper.cc
  source/extensions/filters/network/dubbo_proxy/buffer_helper.h
  source/extensions/filters/network/kafka/BUILD
  source/extensions/filters/network/kafka/serialization.cc
  source/extensions/filters/network/kafka/serialization.h
  source/extensions/filters/network/kafka/tagged_fields.h
  source/extensions/filters/network/mongo_proxy/bson_impl.cc
  source/extensions/filters/network/thrift_proxy/BUILD
  source/extensions/filters/network/thrift_proxy/buffer_helper.cc
  source/extensions/filters/udp/dns_filter/BUILD
  source/extensions/filters/udp/dns_filter/dns_parser.cc
  source/extensions/quic_listeners/quiche/platform/string_utils.cc
  source/extensions/stat_sinks/common/statsd/statsd.cc
  source/extensions/transport_sockets/tls/BUILD
  source/extensions/transport_sockets/tls/utility.cc
  source/server/BUILD
  source/server/hot_restarting_base.cc
  test/common/common/BUILD
  test/common/common/safe_memcpy_test.cc
  test/per_file_coverage.sh
  tools/code_format/check_format.py
Labels: api, deps, v2-freeze

#15529 udp: create common UDP socket config message
  api/envoy/config/core/v3/udp_socket_config.proto
  api/envoy/config/core/v4alpha/udp_socket_config.proto
  api/envoy/config/listener/v3/udp_listener_config.proto
  api/envoy/config/listener/v4alpha/udp_listener_config.proto
  api/envoy/extensions/filters/udp/udp_proxy/v3/BUILD
  api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  docs/root/api-v3/common_messages/common_messages.rst
  docs/root/configuration/listeners/udp_filters/_include/udp-proxy.yaml
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/core/v3/udp_socket_config.proto
  generated_api_shadow/envoy/config/core/v4alpha/udp_socket_config.proto
  generated_api_shadow/envoy/config/listener/v3/udp_listener_config.proto
  generated_api_shadow/envoy/config/listener/v4alpha/udp_listener_config.proto
  generated_api_shadow/envoy/extensions/filters/udp/udp_proxy/v3/BUILD
  generated_api_shadow/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
  source/server/active_udp_listener.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_integration_test.cc
  test/integration/fake_upstream.cc
Labels: api

#15222 backport 1.15: master -> main
  .azure-pipelines/pipelines.yml
  .bazelrc
  CONTRIBUTING.md
  DEVELOPER.md
  EXTENSION_POLICY.md
  GOVERNANCE.md
  ISSUES.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  RELEASES.md
  SECURITY.md
  api/API_VERSIONING.md
  api/CONTRIBUTING.md
  api/README.md
  api/envoy/api/v2/core/protocol.proto
  api/envoy/config/core/v3/protocol.proto
  api/envoy/config/core/v4alpha/protocol.proto
  bazel/EXTERNAL_DEPS.md
  bazel/PPROF.md
  bazel/README.md
  ci/README.md
  ci/api_mirror.sh
  ci/docker_ci.sh
  ci/filter_example_mirror.sh
  ci/go_mirror.sh
  docs/README.md
  docs/publish.sh
  docs/root/version_history/v1.11.0.rst
  docs/root/version_history/v1.14.0.rst
  docs/root/version_history/v1.4.0.rst
  docs/root/version_history/v1.8.0.rst
  docs/root/version_history/v1.9.0.rst
  docs/root/version_history/version_history.rst
  examples/grpc-bridge/docker-compose-protos.yaml
  generated_api_shadow/envoy/api/v2/core/protocol.proto
  generated_api_shadow/envoy/config/core/v3/protocol.proto
  generated_api_shadow/envoy/config/core/v4alpha/protocol.proto
  security/email-templates.md
  security/postmortems/cve-2019-15225.md
  security/postmortems/cve-2019-9900.md
  source/common/http/utility.cc
  source/common/stats/thread_local_store.h
  source/common/stats/utility.h
  source/docs/repokitteh.md
  source/docs/stats.md
  test/README.md
  test/integration/fake_upstream.h
  test/integration/stats_integration_test.cc
  tools/api/generate_go_protobuf.py
  tools/git/last_github_commit.sh
  tools/proto_format/proto_sync.py
Labels: v2-freeze

#15223 backport 1.14: master -> main
  .azure-pipelines/pipelines.yml
  .bazelrc
  CONTRIBUTING.md
  DEVELOPER.md
  EXTENSION_POLICY.md
  GOVERNANCE.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  RELEASES.md
  SECURITY.md
  api/API_VERSIONING.md
  api/CONTRIBUTING.md
  api/README.md
  api/envoy/api/v2/core/protocol.proto
  api/envoy/config/core/v3/protocol.proto
  api/envoy/config/core/v4alpha/protocol.proto
  bazel/EXTERNAL_DEPS.md
  bazel/PPROF.md
  bazel/README.md
  ci/README.md
  ci/api_mirror.sh
  ci/docker_ci.sh
  ci/filter_example_mirror.sh
  ci/go_mirror.sh
  docs/README.md
  docs/publish.sh
  docs/root/intro/deprecated.rst
  docs/root/intro/version_history.rst
  examples/grpc-bridge/docker-compose-protos.yaml
  generated_api_shadow/envoy/api/v2/core/protocol.proto
  generated_api_shadow/envoy/config/core/v3/protocol.proto
  generated_api_shadow/envoy/config/core/v4alpha/protocol.proto
  security/email-templates.md
  security/postmortems/cve-2019-15225.md
  security/postmortems/cve-2019-9900.md
  source/common/stats/thread_local_store.h
  source/docs/repokitteh.md
  source/docs/stats.md
  test/README.md
  test/integration/fake_upstream.h
  test/integration/stats_integration_test.cc
  tools/api/generate_go_protobuf.py
  tools/git/last_github_commit.sh
  tools/proto_format/proto_sync.py
Labels: v2-freeze

#15545 udp: add explicit config for GRO
  api/envoy/config/core/v3/udp_socket_config.proto
  api/envoy/config/core/v4alpha/udp_socket_config.proto
  api/envoy/config/listener/v3/udp_listener_config.proto
  api/envoy/config/listener/v4alpha/udp_listener_config.proto
  api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  docs/root/version_history/current.rst
  generated_api_shadow/envoy/config/core/v3/udp_socket_config.proto
  generated_api_shadow/envoy/config/core/v4alpha/udp_socket_config.proto
  generated_api_shadow/envoy/config/listener/v3/udp_listener_config.proto
  generated_api_shadow/envoy/config/listener/v4alpha/udp_listener_config.proto
  generated_api_shadow/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  include/envoy/event/BUILD
  include/envoy/event/dispatcher.h
  source/common/event/dispatcher_impl.cc
  source/common/event/dispatcher_impl.h
  source/common/network/udp_listener_impl.cc
  source/common/network/udp_listener_impl.h
  source/common/network/utility.cc
  source/common/network/utility.h
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
  source/extensions/quic_listeners/quiche/active_quic_listener.cc
  source/extensions/quic_listeners/quiche/envoy_quic_client_connection.cc
  source/server/active_udp_listener.cc
  source/server/active_udp_listener.h
  test/common/network/BUILD
  test/common/network/udp_listener_impl_batch_writer_test.cc
  test/common/network/udp_listener_impl_test.cc
  test/common/network/utility_test.cc
  test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
  test/mocks/event/mocks.h
  test/mocks/event/wrapped_dispatcher.h
  test/server/connection_handler_test.cc
  test/test_common/network_utility.cc
Labels: api

#15703 deps: Resolve conflicting python updates
  api/tools/generate_listeners.py
  ci/flaky_test/requirements.txt
  docs/requirements.txt
  tools/code_format/requirements.txt
Labels: deps

#15619 http: add HTTP/1.1 case preservation
  CODEOWNERS
  api/BUILD
  api/envoy/config/core/v3/protocol.proto
  api/envoy/config/core/v4alpha/protocol.proto
  api/envoy/extensions/http/header_formatters/preserve_case/v3/BUILD
  api/envoy/extensions/http/header_formatters/preserve_case/v3/preserve_case.proto
  api/versioning/BUILD
  bazel/envoy_library.bzl
  docs/root/api-v3/config/config.rst
  docs/root/api-v3/config/http/header_formatters.rst
  docs/root/configuration/http/http_conn_man/_include/preserve-case.yaml
  docs/root/configuration/http/http_conn_man/header_casing.rst
  docs/root/version_history/current.rst
  generated_api_shadow/BUILD
  generated_api_shadow/envoy/config/core/v3/protocol.proto
  generated_api_shadow/envoy/config/core/v4alpha/protocol.proto
  generated_api_shadow/envoy/extensions/http/header_formatters/preserve_case/v3/BUILD
  generated_api_shadow/envoy/extensions/http/header_formatters/preserve_case/v3/preserve_case.proto
  include/envoy/common/optref.h
  include/envoy/http/BUILD
  include/envoy/http/codec.h
  include/envoy/http/header_formatter.h
  include/envoy/http/header_map.h
  source/common/http/header_map_impl.h
  source/common/http/http1/BUILD
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/codec_impl.h
  source/common/http/http1/header_formatter.h
  source/common/http/http1/settings.cc
  source/common/http/http1/settings.h
  source/common/http/utility.cc
  source/common/http/utility.h
  source/common/upstream/upstream_impl.cc
  source/extensions/extensions_build_config.bzl
  source/extensions/filters/network/http_connection_manager/BUILD
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/http/header_formatters/preserve_case/BUILD
  source/extensions/http/header_formatters/preserve_case/preserve_case_formatter.cc
  source/extensions/http/header_formatters/preserve_case/preserve_case_formatter.h
  source/extensions/upstreams/http/BUILD
  source/extensions/upstreams/http/config.cc
  source/extensions/upstreams/http/config.h
  test/common/common/optref_test.cc
  test/common/http/utility_test.cc
  test/extensions/http/header_formatters/preserve_case/BUILD
  test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_integration_test.cc
  test/extensions/http/header_formatters/preserve_case/preserve_case_formatter_test.cc
  test/extensions/upstreams/http/BUILD
  test/extensions/upstreams/http/config_test.cc
  test/test_common/utility.h
Labels: api

#14522 lua: timestamp in millis
  docs/root/configuration/http/http_filters/lua_filter.rst
  docs/root/version_history/current.rst
  source/extensions/filters/common/lua/lua.cc
  source/extensions/filters/common/lua/lua.h
  source/extensions/filters/http/lua/config.cc
  source/extensions/filters/http/lua/lua_filter.cc
  source/extensions/filters/http/lua/lua_filter.h
  source/extensions/filters/http/lua/wrappers.h
  test/extensions/filters/common/lua/lua_test.cc
  test/extensions/filters/common/lua/lua_wrappers.h
  test/extensions/filters/http/lua/lua_filter_test.cc
Labels: deps

#15752 http3: further cleanup and extension removal
  api/envoy/extensions/transport_sockets/quic/v3/quic_transport.proto
  api/envoy/extensions/transport_sockets/quic/v4alpha/quic_transport.proto
  bazel/BUILD
  bazel/envoy_select.bzl
  generated_api_shadow/envoy/extensions/transport_sockets/quic/v3/quic_transport.proto
  generated_api_shadow/envoy/extensions/transport_sockets/quic/v4alpha/quic_transport.proto
  source/common/http/BUILD
  source/common/http/codec_client.cc
  source/common/http/http3/BUILD
  source/common/http/http3/conn_pool.cc
  source/common/http/http3/quic_client_connection_factory.h
  source/common/http/http3/quic_codec_factory.h
  source/common/http/http3/well_known_names.h
  source/common/quic/BUILD
  source/common/quic/client_connection_factory_impl.cc
  source/common/quic/client_connection_factory_impl.h
  source/common/quic/codec_impl.cc
  source/common/quic/codec_impl.h
  source/common/upstream/BUILD
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/upstream_impl.cc
  source/extensions/extensions_build_config.bzl
  source/extensions/filters/network/http_connection_manager/BUILD
  source/extensions/filters/network/http_connection_manager/config.cc
  test/common/http/BUILD
  test/common/quic/quic_upstream_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/extensions/filters/network/http_connection_manager/config_test.cc
  test/integration/BUILD
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/http_integration.cc
  test/integration/utility.cc
  test/server/BUILD
  test/server/listener_manager_impl_quic_only_test.cc
Labels: api
