Repository envoyproxy/envoy, pull requests merged in 2022-10, with the labels that each got.

#23297 Docs: tls minimum protocol version
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
Labels: api

#23320 tls: use X509_V_FLAG_NO_CHECK_TIME to implement allow_expired_certificate
  bazel/repository_locations.bzl
  source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
  source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
  source/extensions/transport_sockets/tls/cert_validator/utility.cc
  source/extensions/transport_sockets/tls/cert_validator/utility.h
  test/extensions/transport_sockets/tls/cert_validator/BUILD
  test/extensions/transport_sockets/tls/cert_validator/utility_test.cc
Labels: deps

#23329 build(deps): bump google/flatbuffers from 2.0.0 to 22.9.29
  bazel/repository_locations.bzl
Labels: deps

#23396 bazel: update abseil
  .bazelrc
  bazel/repository_locations.bzl
Labels: deps

#23612 removing envoy.reloadable_features.allow_upstream_inline_write
  changelogs/current.yaml
  source/common/router/router.cc
  source/common/runtime/runtime_features.cc
  test/integration/BUILD
Labels: deps

#23495 repo: Update `protoc-gen-validate` links -> bufbuild
  DEPENDENCY_POLICY.md
  api/API_VERSIONING.md
  api/STYLE.md
  api/envoy/api/v2/core/grpc_service.proto
  api/envoy/config/core/v3/grpc_service.proto
  bazel/dependency_imports.bzl
  docs/root/api-docs/xds_protocol.rst
  source/common/common/regex.cc
  source/common/protobuf/utility.h
  source/common/upstream/upstream_impl.cc
  test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc
Labels: v2-freeze

#23681 envoy_reloadable_features_override_request_timeout_by_gateway_timeout deprecation
  changelogs/current.yaml
  source/common/http/conn_manager_impl.cc
  source/common/http/utility.cc
  source/common/runtime/runtime_features.cc
  test/integration/protocol_integration_test.cc
Labels: api-review-required, api
