Repository envoyproxy/envoy, pull requests merged in 2022-07, with the labels that each got.

#22082 admin: return multiple addresses for `/listeners` API
  source/server/admin/listeners_handler.cc
  test/integration/integration_admin_test.cc
  test/integration/integration_admin_test.h
Labels: api, v2-freeze

#22080 dns: add a getaddrinfo based system resolver
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/network/dns_resolver/getaddrinfo/v3/BUILD
  api/envoy/extensions/network/dns_resolver/getaddrinfo/v3/getaddrinfo_dns_resolver.proto
  api/versioning/BUILD
  changelogs/current.yaml
  docs/root/intro/arch_overview/upstream/dns_resolution.rst
  envoy/api/os_sys_calls.h
  source/common/api/posix/os_sys_calls_impl.cc
  source/common/api/posix/os_sys_calls_impl.h
  source/common/api/win32/os_sys_calls_impl.cc
  source/common/api/win32/os_sys_calls_impl.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/network/dns_resolver/getaddrinfo/BUILD
  source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
  source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h
  test/extensions/filters/http/dynamic_forward_proxy/BUILD
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/network/dns_resolver/getaddrinfo/BUILD
  test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc
  test/mocks/api/mocks.h
  test/per_file_coverage.sh
Labels: api

#21892 make total weight optional
  api/envoy/api/v2/route/route_components.proto
  api/envoy/config/route/v3/route_components.proto
  changelogs/current.yaml
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  test/common/router/config_impl_test.cc
Labels: v2-freeze

#21859 Add "treat_missing_header_as_empty" API Field
  api/envoy/config/route/v3/route_components.proto
  changelogs/current.yaml
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  test/common/http/header_utility_test.cc
Labels: v2-freeze

#22098 fix coredump
  contrib/sip_proxy/filters/network/source/conn_manager.cc
  contrib/sip_proxy/filters/network/source/conn_manager.h
  contrib/sip_proxy/filters/network/source/router/router_impl.h
  contrib/sip_proxy/filters/network/source/tra/tra_impl.cc
  contrib/sip_proxy/filters/network/source/tra/tra_impl.h
Labels: deps

#22122 oauth: support authentication methods for client to oauth server requests
  api/envoy/extensions/filters/http/oauth2/v3/oauth.proto
  source/extensions/filters/http/oauth2/BUILD
  source/extensions/filters/http/oauth2/filter.cc
  source/extensions/filters/http/oauth2/filter.h
  source/extensions/filters/http/oauth2/oauth.h
  source/extensions/filters/http/oauth2/oauth_client.cc
  source/extensions/filters/http/oauth2/oauth_client.h
  test/extensions/filters/http/oauth2/BUILD
  test/extensions/filters/http/oauth2/config_test.cc
  test/extensions/filters/http/oauth2/filter_test.cc
  test/extensions/filters/http/oauth2/oauth_integration_test.cc
Labels: api, v2-freeze, deps

#19546 admin: Richer HTML home page with forms for params
  docs/root/operations/admin.rst
  envoy/server/admin.h
  source/server/admin/BUILD
  source/server/admin/admin.cc
  source/server/admin/admin.css
  source/server/admin/admin.h
  source/server/admin/admin_head_start.html
  source/server/admin/admin_html.cc
  source/server/admin/admin_no_html.cc
  source/server/admin/generate_admin_html.sh
  source/server/admin/stats_handler.cc
  source/server/admin/stats_handler.h
  source/server/admin/stats_html_render.cc
  source/server/admin/stats_html_render.h
  source/server/admin/stats_params.cc
  source/server/admin/stats_params.h
  source/server/admin/stats_render.cc
  source/server/admin/stats_render.h
  source/server/admin/stats_request.cc
  source/server/admin/stats_request.h
  source/server/admin/utils.cc
  source/server/config_validation/admin.cc
  source/server/config_validation/admin.h
  test/extensions/common/tap/admin_test.cc
  test/extensions/filters/http/common/fuzz/uber_per_filter.cc
  test/mocks/server/admin.cc
  test/mocks/server/admin.h
  test/server/admin/BUILD
  test/server/admin/admin_html_test.cc
  test/server/admin/admin_test.cc
  test/server/admin/stats_handler_test.cc
  test/server/admin/stats_html_render_test.cc
  test/server/admin/stats_params_test.cc
  test/server/admin/stats_render_test.cc
  test/server/admin/stats_render_test_base.cc
  test/server/admin/stats_render_test_base.h
  test/server/admin/stats_request_test.cc
  test/server/admin/utils_test.cc
Labels: no stalebot
