Repository envoyproxy/envoy, pull requests merged in 2022-01, with the labels that each got.

#19173 matchers: add an IP trie matcher
  api/bazel/repository_locations.bzl
  docs/root/version_history/current.rst
  envoy/matcher/BUILD
  envoy/matcher/matcher.h
  envoy/network/filter.h
  source/common/http/filter_manager.cc
  source/common/matcher/matcher.h
  source/common/network/cidr_range.cc
  source/common/network/cidr_range.h
  source/common/router/config_impl.cc
  source/extensions/common/matcher/BUILD
  source/extensions/common/matcher/trie_matcher.cc
  source/extensions/common/matcher/trie_matcher.h
  test/common/matcher/test_utility.h
  test/extensions/common/matcher/BUILD
  test/extensions/common/matcher/trie_matcher_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: api, deps

#16854 cache: Adds support for caching HTTP trailers.
  source/extensions/filters/http/cache/cache_filter.cc
  source/extensions/filters/http/cache/cache_filter.h
  source/extensions/filters/http/cache/http_cache.cc
  source/extensions/filters/http/cache/http_cache.h
  source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.cc
  source/extensions/filters/http/cache/simple_http_cache/simple_http_cache.h
  test/extensions/filters/http/cache/cache_filter_integration_test.cc
  test/extensions/filters/http/cache/http_cache_test.cc
  test/extensions/filters/http/cache/simple_http_cache/simple_http_cache_test.cc
Labels: api, deps

#18090 docs: Remove custom intersphinx extension
  docs/_ext/intersphinx_custom.py
  docs/conf.py
Labels: no stalebot, deps

#19449 ext_proc: Add code to check mutation rules
  CODEOWNERS
  api/envoy/config/common/mutation_rules/v3/mutation_rules.proto
  source/extensions/filters/common/mutation_rules/BUILD
  source/extensions/filters/common/mutation_rules/mutation_rules.cc
  source/extensions/filters/common/mutation_rules/mutation_rules.h
  test/extensions/filters/common/mutation_rules/BUILD
  test/extensions/filters/common/mutation_rules/mutation_rules_test.cc
Labels: api

#19442 bazel: Shift dependency validate tool to bazel
  ci/do_ci.sh
  tools/dependency/BUILD
  tools/dependency/validate.py
  tools/dependency/validate_test.py
Labels: deps

#19291 Windows: Emulate MSG_PEEK by read
  contrib/postgres_proxy/filters/network/test/postgres_decoder_test.cc
  envoy/buffer/buffer.h
  source/common/buffer/buffer_impl.cc
  source/common/buffer/buffer_impl.h
  source/common/network/BUILD
  source/common/network/win32_socket_handle_impl.cc
  source/common/network/win32_socket_handle_impl.h
  test/common/buffer/buffer_corpus/basic
  test/common/buffer/buffer_fuzz.cc
  test/common/buffer/buffer_fuzz.proto
  test/common/buffer/owned_impl_test.cc
  test/common/network/BUILD
  test/common/network/win32_socket_handle_impl_test.cc
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc
Labels: area/windows

#19691 xray: make Unknown as the default SamplingDecision
  CODEOWNERS
  docs/root/version_history/current.rst
  source/extensions/tracers/xray/xray_configuration.h
  test/extensions/tracers/xray/xray_tracer_impl_test.cc
Labels: waiting
