Repository envoyproxy/envoy, pull requests merged in 2022-08, with the labels that each got.

#22270 Add gRPC status into LocalReplyData
  envoy/http/filter.h
  source/common/http/filter_manager.cc
  test/common/http/filter_manager_test.cc
Labels: api, v2-freeze, deps

#22165 http health check: add http method configuration
  api/envoy/config/core/v3/health_check.proto
  changelogs/current.yaml
  source/common/upstream/health_checker_impl.cc
  source/common/upstream/health_checker_impl.h
  test/common/upstream/health_checker_impl_test.cc
Labels: v2-freeze

#22540 test: allowing many test filters to be upstream filters
  test/extensions/filters/http/common/empty_http_filter_config.h
  test/integration/filters/add_body_filter.cc
  test/integration/filters/add_invalid_data_filter.cc
  test/integration/filters/add_trailers_filter.cc
  test/integration/filters/buffer_continue_filter.cc
  test/integration/filters/call_decodedata_once_filter.cc
  test/integration/filters/common.h
  test/integration/filters/continue_headers_only_inject_body_filter.cc
  test/integration/filters/crash_filter.cc
  test/integration/filters/decode_headers_return_stop_all_filter.cc
  test/integration/filters/encode_headers_return_stop_all_filter.cc
  test/integration/filters/encoder_decoder_buffer_filter.cc
  test/integration/filters/invalid_header_filter.cc
  test/integration/filters/local_reply_during_encoding_data_filter.cc
  test/integration/filters/local_reply_during_encoding_filter.cc
  test/integration/filters/local_reply_with_metadata_filter.cc
  test/integration/filters/on_local_reply_filter.cc
  test/integration/filters/passthrough_filter.cc
  test/integration/filters/remove_response_headers.cc
  test/integration/filters/stop_iteration_headers_inject_body_filter.cc
  test/integration/filters/wait_for_whole_request_and_response.cc
Labels: waiting

#22274 api: mark internal listener as implemented and change internal listener binding
  api/envoy/config/core/v3/address.proto
  api/envoy/config/listener/v3/listener.proto
  changelogs/current.yaml
  configs/encapsulate_http_in_http2_connect.yaml
  configs/internal_listener_proxy.yaml
  configs/terminate_http_in_http2_connect.yaml
  docs/root/configuration/other_features/internal_listener.rst
  docs/root/intro/arch_overview/http/upgrades.rst
  envoy/network/address.h
  source/common/network/address_impl.cc
  source/common/network/address_impl.h
  source/common/network/resolver_impl.cc
  source/common/network/utility.cc
  source/server/connection_handler_impl.cc
  source/server/listener_impl.cc
  source/server/listener_impl.h
  source/server/listener_manager_impl.cc
  test/common/network/address_impl_test.cc
  test/common/network/connection_impl_test.cc
  test/common/network/resolver_impl_test.cc
  test/common/network/utility_test.cc
  test/config_test/config_test.cc
  test/extensions/bootstrap/internal_listener/internal_listener_integration_test.cc
  test/extensions/transport_sockets/internal_upstream/internal_upstream_integration_test.cc
  test/integration/socket_interface_integration_test.cc
  test/server/listener_manager_impl_test.cc
Labels: v2-freeze

#22586 gcp_authn: Stop the filter chain iteration for headers as well as data and trailers
  source/extensions/filters/http/gcp_authn/gcp_authn_filter.cc
  test/extensions/filters/http/gcp_authn/gcp_authn_filter_integration_test.cc
  test/extensions/filters/http/gcp_authn/gcp_authn_filter_test.cc
Labels: deps

#22635 deps: update Ragel
  bazel/foreign_cc/BUILD
  bazel/repositories.bzl
  bazel/repository_locations.bzl
Labels: deps

#22753 deps: Bump com_google_cel_cpp release date to 2022-07-21
  bazel/repository_locations.bzl
Labels: deps

#22553 http: implementing upstream filters
  changelogs/current.yaml
  source/common/http/conn_manager_impl.h
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/router/BUILD
  source/common/router/config_utility.cc
  source/common/router/router.cc
  source/common/router/upstream_request.cc
  source/common/router/upstream_request.h
  source/common/runtime/runtime_features.cc
  test/common/router/router_2_test.cc
  test/common/router/router_test.cc
  test/common/router/upstream_request_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/config/utility.cc
  test/config/utility.h
  test/extensions/filters/http/buffer/BUILD
  test/extensions/filters/http/buffer/buffer_filter_integration_test.cc
  test/integration/BUILD
  test/integration/filter_integration_test.cc
  test/integration/filters/BUILD
  test/integration/filters/reset_stream_filter.cc
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/http_protocol_integration.cc
  test/integration/http_protocol_integration.h
  test/integration/multiplexed_integration_test.cc
  test/mocks/router/mocks.h
  test/mocks/router/router_filter_interface.h
Labels: api

#22601 network: try getOriginalDst from transparent socket's local_address
  changelogs/current.yaml
  source/common/network/BUILD
  source/common/network/socket_option_impl.h
  source/common/network/utility.cc
  test/common/network/utility_test.cc
  test/server/listener_manager_impl_test.cc
Labels: api, deps

#22703 URL Rewrite: Match and Rewrite Library
  CODEOWNERS
  source/extensions/path/uri_template_lib/BUILD
  source/extensions/path/uri_template_lib/proto/BUILD
  source/extensions/path/uri_template_lib/proto/rewrite_segments.proto
  source/extensions/path/uri_template_lib/uri_template.cc
  source/extensions/path/uri_template_lib/uri_template.h
  source/extensions/path/uri_template_lib/uri_template_internal.cc
  source/extensions/path/uri_template_lib/uri_template_internal.h
  test/extensions/path/uri_template_lib/BUILD
  test/extensions/path/uri_template_lib/uri_template_internal_test.cc
  test/extensions/path/uri_template_lib/uri_template_test.cc
  tools/code_format/config.yaml
  tools/spelling/spelling_dictionary.txt
Labels: api, deps
