Repository envoyproxy/envoy, pull requests merged in 2022-04, with the labels that each got.

#20145 router: add new path-splitting prefix matcher
  api/envoy/config/route/v3/route_components.proto
  docs/root/version_history/current.rst
  envoy/router/router.h
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/extensions/filters/http/jwt_authn/matcher.cc
  test/common/router/config_impl_test.cc
  test/extensions/filters/http/jwt_authn/matcher_test.cc
Labels: v2-freeze

#19467 bootstrap extension: internal listener
  CODEOWNERS
  api/BUILD
  api/envoy/config/core/v3/address.proto
  api/envoy/extensions/bootstrap/internal_listener/v3/BUILD
  api/envoy/extensions/bootstrap/internal_listener/v3/internal_listener.proto
  api/versioning/BUILD
  docs/root/api-v3/bootstrap/bootstrap.rst
  docs/root/configuration/other_features/internal_listener.rst
  docs/root/configuration/other_features/other_features.rst
  envoy/network/BUILD
  envoy/network/address.h
  envoy/network/client_connection_factory.h
  envoy/network/listener.h
  source/common/event/BUILD
  source/common/event/dispatcher_impl.cc
  source/common/network/BUILD
  source/common/network/address_impl.h
  source/common/network/default_client_connection_factory.cc
  source/common/network/default_client_connection_factory.h
  source/extensions/bootstrap/internal_listener/BUILD
  source/extensions/bootstrap/internal_listener/client_connection_factory.cc
  source/extensions/bootstrap/internal_listener/client_connection_factory.h
  source/extensions/bootstrap/internal_listener/internal_listener_registry.cc
  source/extensions/bootstrap/internal_listener/internal_listener_registry.h
  source/extensions/bootstrap/internal_listener/thread_local_registry.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/io_socket/user_space/BUILD
  source/extensions/io_socket/user_space/io_handle_impl.h
  source/server/BUILD
  source/server/connection_handler_impl.cc
  source/server/listener_impl.cc
  source/server/listener_impl.h
  test/common/event/BUILD
  test/common/event/dispatcher_impl_test.cc
  test/common/network/connection_impl_test.cc
  test/extensions/bootstrap/internal_listener/BUILD
  test/extensions/bootstrap/internal_listener/client_connection_factory_test.cc
  test/extensions/bootstrap/internal_listener/internal_listener_integration_test.cc
  test/extensions/bootstrap/internal_listener/internal_listener_registry_test.cc
  test/extensions/network/dns_resolver/cares/dns_impl_test.cc
  test/integration/BUILD
  test/integration/socket_interface_integration_test.cc
  test/mocks/network/mocks.h
  test/server/connection_handler_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
Labels: v2-freeze

#20115 TLS Certvalidator: Add config option max_verify_depth to CertificateValidationContext
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
  envoy/ssl/certificate_validation_context_config.h
  source/common/ssl/certificate_validation_context_config_impl.cc
  source/common/ssl/certificate_validation_context_config_impl.h
  source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
  test/config/integration/certs/certs.sh
  test/config/integration/certs/client2cert.cfg
  test/config/integration/certs/client2cert.pem
  test/config/integration/certs/client2cert_hash.h
  test/config/integration/certs/client2key.pem
  test/config/integration/certs/intermediate_ca_2cert.cfg
  test/config/integration/certs/intermediate_ca_cert_chain.pem
  test/config/integration/certs/intermediate_cacert.cfg
  test/config/utility.cc
  test/config/utility.h
  test/extensions/transport_sockets/tls/cert_validator/BUILD
  test/extensions/transport_sockets/tls/cert_validator/default_validator_integration_test.cc
  test/extensions/transport_sockets/tls/cert_validator/default_validator_integration_test.h
  test/extensions/transport_sockets/tls/cert_validator/default_validator_test.cc
  test/extensions/transport_sockets/tls/cert_validator/test_common.h
  test/extensions/transport_sockets/tls/ssl_test_utility.h
  test/extensions/transport_sockets/tls/test_data/certs.sh
  test/extensions/transport_sockets/tls/test_data/i1_cert.cfg
  test/extensions/transport_sockets/tls/test_data/i2_cert.cfg
  test/extensions/transport_sockets/tls/test_data/i3_cert.cfg
  test/extensions/transport_sockets/tls/test_data/i4_cert.cfg
  test/extensions/transport_sockets/tls/test_data/test_long_cert_chain.pem
  test/extensions/transport_sockets/tls/test_data/test_random_cert.pem
  test/integration/ssl_utility.cc
  test/integration/ssl_utility.h
  test/mocks/ssl/mocks.h
Labels: api

#20548 http conn manager: configure cidr_ranges for internal address
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  docs/root/version_history/current.rst
  source/extensions/filters/network/http_connection_manager/BUILD
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  test/extensions/filters/network/http_connection_manager/config_test.cc
Labels: api

#20224 http2: Adds a runtime feature that controls use of a new HTTP/2 implementation in Envoy
  docs/root/version_history/current.rst
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl.h
  source/common/runtime/runtime_features.cc
  test/common/http/http2/codec_impl_test.cc
  test/common/http/http2/codec_impl_test_util.h
  test/extensions/filters/http/buffer/BUILD
  test/extensions/filters/http/cache/BUILD
  test/extensions/filters/http/jwt_authn/BUILD
  test/extensions/filters/http/kill_request/BUILD
  test/extensions/filters/http/rbac/BUILD
  test/integration/BUILD
  test/integration/buffer_accounting_integration_test.cc
  test/integration/http_integration.cc
  test/integration/http_integration.h
  test/integration/http_protocol_integration.cc
  test/integration/http_protocol_integration.h
  test/integration/multiplexed_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/integration/redirect_integration_test.cc
Labels: deps

#19339 io: add io_uring wrapper
  bazel/foreign_cc/BUILD
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  source/common/io/BUILD
  source/common/io/io_uring.h
  source/common/io/io_uring_impl.cc
  source/common/io/io_uring_impl.h
  source/exe/BUILD
  test/common/io/BUILD
  test/common/io/io_uring_impl_test.cc
Labels: api

#20740 bazel: Add rustc source files
  bazel/dependency_imports.bzl
Labels: deps

#20110 listeners: add unified matcher for filter chains
  api/envoy/config/listener/v3/BUILD
  api/envoy/config/listener/v3/listener.proto
  api/envoy/config/listener/v3/listener_components.proto
  docs/root/intro/arch_overview/advanced/matching/_include/listener_complicated.yaml
  docs/root/intro/arch_overview/advanced/matching/_include/listener_tls.yaml
  docs/root/intro/arch_overview/advanced/matching/_include/listener_vip.yaml
  docs/root/intro/arch_overview/advanced/matching/matching.rst
  docs/root/intro/arch_overview/advanced/matching/matching_listener.rst
  source/server/BUILD
  source/server/filter_chain_manager_impl.cc
  source/server/filter_chain_manager_impl.h
  source/server/listener_impl.cc
  test/integration/xds_integration_test.cc
  test/server/BUILD
  test/server/filter_chain_benchmark_test.cc
  test/server/filter_chain_manager_impl_test.cc
  test/server/listener_manager_impl_quic_only_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
Labels: api

#20143 filter: add language http filter "accept-language"
  CODEOWNERS
  api/BUILD
  api/contrib/envoy/extensions/filters/http/language/v3alpha/BUILD
  api/contrib/envoy/extensions/filters/http/language/v3alpha/language.proto
  api/versioning/BUILD
  bazel/foreign_cc/BUILD
  bazel/foreign_cc/icu.patch
  bazel/foreign_cc/icu_data_filter.json
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/language/filters/http/source/BUILD
  contrib/language/filters/http/source/config.cc
  contrib/language/filters/http/source/config.h
  contrib/language/filters/http/source/language_filter.cc
  contrib/language/filters/http/source/language_filter.h
  contrib/language/filters/http/test/BUILD
  contrib/language/filters/http/test/language_config_test.cc
  contrib/language/filters/http/test/language_integration_test.cc
  docs/root/configuration/http/http_filters/http_filters.rst
  docs/root/configuration/http/http_filters/language_filter.rst
Labels: api, v2-freeze, deps

#19875 [19685] network rate limit: allow limiting by client IP
  docs/root/configuration/listeners/network_filters/rate_limit_filter.rst
  docs/root/version_history/current.rst
  source/extensions/filters/network/ratelimit/ratelimit.cc
  source/extensions/filters/network/ratelimit/ratelimit.h
  test/extensions/filters/network/ratelimit/config_test.cc
  test/extensions/filters/network/ratelimit/ratelimit_test.cc
Labels: api

#20830 bazel: add temporary rules_rust patch
  bazel/repositories.bzl
  bazel/rules_rust.patch
Labels: deps

#17979 dist: Add debian packaging
  .azure-pipelines/pipelines.yml
  ci/do_ci.sh
Labels: deps

#20332 Add async_files library to support filesystem buffering and filesystem caching
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/common/async_files/v3/BUILD
  api/envoy/extensions/common/async_files/v3/async_file_manager.proto
  api/versioning/BUILD
  docs/root/api-v3/common_messages/common_messages.rst
  source/extensions/common/async_files/BUILD
  source/extensions/common/async_files/README.md
  source/extensions/common/async_files/async_file_action.cc
  source/extensions/common/async_files/async_file_action.h
  source/extensions/common/async_files/async_file_context_base.cc
  source/extensions/common/async_files/async_file_context_base.h
  source/extensions/common/async_files/async_file_context_thread_pool.cc
  source/extensions/common/async_files/async_file_context_thread_pool.h
  source/extensions/common/async_files/async_file_handle.h
  source/extensions/common/async_files/async_file_manager.cc
  source/extensions/common/async_files/async_file_manager.h
  source/extensions/common/async_files/async_file_manager_factory.cc
  source/extensions/common/async_files/async_file_manager_factory.h
  source/extensions/common/async_files/async_file_manager_thread_pool.cc
  source/extensions/common/async_files/async_file_manager_thread_pool.h
  source/extensions/common/async_files/status_after_file_error.cc
  source/extensions/common/async_files/status_after_file_error.h
  test/extensions/common/async_files/BUILD
  test/extensions/common/async_files/async_file_handle_thread_pool_test.cc
  test/extensions/common/async_files/async_file_manager_factory_test.cc
  test/extensions/common/async_files/async_file_manager_thread_pool_test.cc
  test/extensions/common/async_files/async_file_manager_thread_pool_with_mocks_test.cc
  test/extensions/common/async_files/status_after_file_error_test.cc
  test/per_file_coverage.sh
  test/test_common/status_utility.h
  tools/spelling/spelling_dictionary.txt
Labels: deps

#20899 Revert "bazel: enable rules_foreign_cc vendored tools"
  .bazelrc
  bazel/README.md
  bazel/dependency_imports.bzl
  bazel/setup_clang.sh
Labels: deps

#20645 tracing: Move custom-tag application after common tags
  source/common/tracing/http_tracer_impl.cc
  test/common/tracing/http_tracer_impl_test.cc
Labels: api, deps

#20788 Add config proto for FileSystemBuffer filter
  api/BUILD
  api/envoy/extensions/filters/http/file_system_buffer/v3/BUILD
  api/envoy/extensions/filters/http/file_system_buffer/v3/file_system_buffer.proto
  api/versioning/BUILD
Labels: deps

#20941 fuzz test: Prevent use of negative durations.
  test/extensions/filters/network/common/fuzz/uber_per_readfilter.cc
Labels: waiting

#20529 TLS: Allow specification of both typed and non-typed san matchers in config
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
  docs/root/version_history/current.rst
  source/common/ssl/certificate_validation_context_config_impl.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
Labels: backport/review

#20756 thrift: keep downstream connection on routing error
  api/envoy/extensions/filters/network/thrift_proxy/router/v3/router.proto
  docs/root/version_history/current.rst
  source/extensions/filters/network/thrift_proxy/conn_manager.cc
  source/extensions/filters/network/thrift_proxy/conn_manager.h
  source/extensions/filters/network/thrift_proxy/filters/filter.h
  source/extensions/filters/network/thrift_proxy/router/config.cc
  source/extensions/filters/network/thrift_proxy/router/router.h
  source/extensions/filters/network/thrift_proxy/router/router_impl.cc
  source/extensions/filters/network/thrift_proxy/router/router_impl.h
  source/extensions/filters/network/thrift_proxy/router/shadow_writer_impl.cc
  source/extensions/filters/network/thrift_proxy/router/upstream_request.cc
  source/extensions/filters/network/thrift_proxy/router/upstream_request.h
  test/extensions/filters/network/thrift_proxy/conn_manager_test.cc
  test/extensions/filters/network/thrift_proxy/mocks.h
  test/extensions/filters/network/thrift_proxy/router_test.cc
Labels: api

#21081 bazel: add arm64 iOS simulator rust support
  bazel/dependency_imports.bzl
Labels: deps

#20872 uhv: add http-parser permissive parsing for h1 codec
  bazel/external/http_parser/BUILD
  test/common/http/http1/codec_impl_test.cc
  test/extensions/filters/listener/http_inspector/http_inspector_test.cc
  test/integration/protocol_integration_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: waiting
