Repository envoyproxy/envoy, pull requests merged in 2022-11, with the labels that each got.

#23782 fixing OSS filter_fuzz_test OOM issue when thread_count is 800 million.
  api/envoy/extensions/common/async_files/v3/async_file_manager.proto
Labels: waiting, api

#23832 improve the run_envoy_docker.sh compatibility on mac.
  ci/run_envoy_docker.sh
Labels: backport/review

#23669 matching: expose stream info to filter chain matching
  envoy/network/filter.h
  source/common/quic/BUILD
  source/common/quic/active_quic_listener.cc
  source/common/quic/envoy_quic_client_session.cc
  source/common/quic/envoy_quic_dispatcher.cc
  source/common/quic/envoy_quic_proof_source.cc
  source/common/quic/envoy_quic_proof_source.h
  source/common/quic/envoy_quic_proof_source_factory_interface.h
  source/common/quic/envoy_quic_server_session.cc
  source/common/quic/envoy_quic_server_session.h
  source/common/quic/quic_filter_manager_connection_impl.cc
  source/common/quic/quic_filter_manager_connection_impl.h
  source/extensions/quic/proof_source/envoy_quic_proof_source_factory_impl.cc
  source/extensions/quic/proof_source/envoy_quic_proof_source_factory_impl.h
  source/server/active_stream_listener_base.cc
  source/server/admin/admin.h
  source/server/filter_chain_manager_impl.cc
  source/server/filter_chain_manager_impl.h
  test/common/quic/active_quic_listener_test.cc
  test/common/quic/envoy_quic_dispatcher_test.cc
  test/common/quic/envoy_quic_proof_source_test.cc
  test/common/quic/envoy_quic_server_session_test.cc
  test/common/quic/quic_filter_manager_connection_impl_test.cc
  test/common/quic/test_utils.h
  test/extensions/bootstrap/internal_listener/active_internal_listener_test.cc
  test/extensions/common/proxy_protocol/proxy_protocol_regression_test.cc
  test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.h
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc
  test/integration/fake_upstream.h
  test/mocks/network/mocks.h
  test/server/BUILD
  test/server/active_tcp_listener_test.cc
  test/server/connection_handler_test.cc
  test/server/filter_chain_benchmark_test.cc
  test/server/filter_chain_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
Labels: waiting

#23189 listener: support update socket_options
  api/envoy/config/listener/v3/listener.proto
  changelogs/current.yaml
  docs/root/intro/arch_overview/operations/hot_restart.rst
  source/common/runtime/runtime_features.cc
  source/server/listener_impl.cc
  source/server/listener_impl.h
  source/server/listener_manager_impl.cc
  source/server/listener_manager_impl.h
  test/integration/base_integration_test.cc
  test/integration/base_integration_test.h
  test/integration/listener_lds_integration_test.cc
  test/integration/xds_integration_test.cc
  test/server/listener_manager_impl_test.cc
  test/server/listener_manager_impl_test.h
  tools/spelling/spelling_dictionary.txt
Labels: api

#23922 Revert "bazel: update tcmalloc (#23671)"
  bazel/repository_locations.bzl
  test/common/stats/thread_local_store_test.cc
  test/integration/stats_integration_test.cc
Labels: deps

#24009 [backport/1.23] api/deps: Fix bufbuild links
  api/bazel/repository_locations.bzl
Labels: deps

#23951 [backport/1.22] Release 1.22 build fix
  source/common/config/grpc_mux_impl.cc
  source/common/config/watch_map.cc
Labels: deps

#23617 jwt_authn: upgrade its security status to stable
  source/extensions/extensions_metadata.yaml
Labels: waiting

#24144 mobile: Remove parent link to `envoy` workspace
  mobile/.bazelrc
  mobile/.bazelversion
  mobile/WORKSPACE
  mobile/bazel/platform_mappings
  mobile/envoy
  mobile/tools/check_format.sh
Labels: deps

#24062 Reduce VHDS overhead in RDS update
  source/common/router/route_config_update_receiver_impl.cc
  source/common/router/route_config_update_receiver_impl.h
Labels: deps

#22539 rate_limit_quota: [Doc] add the docs for rate limit quota feature
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/filters/http/rate_limit_quota/v3/rate_limit_quota.proto
  api/envoy/service/rate_limit_quota/v3/rlqs.proto
  api/envoy/type/v3/ratelimit_strategy.proto
  docs/root/api-v3/service/service.rst
  docs/root/api-v3/types/types.rst
  docs/root/configuration/http/http_filters/_include/rate-limit-quota-filter-configuration.yaml
  docs/root/configuration/http/http_filters/http_filters.rst
  docs/root/configuration/http/http_filters/rate_limit_quota_filter.rst
  docs/root/configuration/other_features/rate_limit.rst
  docs/root/intro/arch_overview/other_features/global_rate_limiting.rst
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/filters/http/rate_limit_quota/BUILD
Labels: api

#22253 deps: Bump `rules_rust` -> 0.8.1
  bazel/repository_locations.bzl
  bazel/rules_rust.patch
Labels: no stalebot, deps

#24190 Correct example SPIFFE URIs in the doc
  api/envoy/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto
Labels: api

#22877 Support allowlisting request headers for both gRPC and HTTP authorization servers
  api/envoy/extensions/filters/http/ext_authz/v3/BUILD
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
  changelogs/current.yaml
  source/extensions/filters/common/ext_authz/check_request_utils.cc
  source/extensions/filters/common/ext_authz/check_request_utils.h
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.cc
  source/extensions/filters/common/ext_authz/ext_authz_http_impl.h
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_authz/ext_authz.h
  test/extensions/filters/common/ext_authz/BUILD
  test/extensions/filters/common/ext_authz/check_request_utils_test.cc
  test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
  test/extensions/filters/http/ext_authz/config_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_integration_test.cc
  test/extensions/filters/http/ext_authz/ext_authz_test.cc
Labels: no stalebot, api

#24227 Bumping protoc-gen-validate deps.
  api/bazel/repository_locations.bzl
  mobile/library/common/extensions/cert_validator/platform_bridge/config.h
Labels: deps

#23835 http: append the x-forwarded-port header
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  docs/root/configuration/http/http_conn_man/headers.rst
  envoy/http/header_map.h
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_utility.cc
  source/common/http/headers.h
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/server/admin/admin.h
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/http/conn_manager_impl_test_base.h
  test/common/http/conn_manager_utility_test.cc
  test/integration/integration_test.cc
  test/mocks/http/mocks.h
Labels: api

#22707 uhv: path normalization
  source/extensions/http/header_validators/envoy_default/BUILD
  source/extensions/http/header_validators/envoy_default/header_validator.cc
  source/extensions/http/header_validators/envoy_default/header_validator.h
  source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
  source/extensions/http/header_validators/envoy_default/http2_header_validator.cc
  source/extensions/http/header_validators/envoy_default/path_normalizer.cc
  source/extensions/http/header_validators/envoy_default/path_normalizer.h
  test/extensions/http/header_validators/envoy_default/BUILD
  test/extensions/http/header_validators/envoy_default/header_validator_test.h
  test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc
  test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc
  test/extensions/http/header_validators/envoy_default/path_normalizer_test.cc
  test/integration/header_integration_test.cc
Labels: api
