Repository envoyproxy/envoy, pull requests merged in 2022-03, with the labels that each got.

#20186 vcl: update to vpp fe6d8a370
  bazel/repository_locations.bzl
Labels: waiting

#20090 update tracing error tag for grpc status codes
  docs/root/intro/arch_overview/observability/tracing.rst
  docs/root/version_history/current.rst
  source/common/runtime/runtime_features.cc
  source/common/tracing/http_tracer_impl.cc
  test/common/tracing/BUILD
  test/common/tracing/http_tracer_impl_test.cc
Labels: waiting

#20235 bazel: Add rules for debian packaging
  distribution/BUILD
  distribution/debian/BUILD
  distribution/debian/copyright
  distribution/debian/packages.bzl
  distribution/debian/postinst
  distribution/debian/preinst
  distribution/distros.yaml
  distribution/distrotest.sh
  distribution/packages.bzl
  tools/distribution/BUILD
Labels: deps

#20170 xray tracer: correctly annotate child spans as xray subsegments
  docs/root/version_history/current.rst
  source/extensions/tracers/xray/daemon.proto
  source/extensions/tracers/xray/tracer.cc
  source/extensions/tracers/xray/tracer.h
  test/extensions/tracers/xray/tracer_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: deps

#20223 Fix CI for release/v1.18
  .github/workflows/codeql-daily.yml
  .github/workflows/codeql-push.yml
  examples/cache/Dockerfile-service
  examples/cors/backend/Dockerfile-service
  examples/cors/frontend/Dockerfile-service
  examples/csrf/crosssite/Dockerfile-service
  examples/csrf/samesite/Dockerfile-service
  examples/double-proxy/Dockerfile-app
  examples/dynamic-config-cp/Dockerfile-control-plane
  examples/ext_authz/upstream/service/Dockerfile
  examples/front-proxy/Dockerfile-jaeger-service
  examples/front-proxy/Dockerfile-service
  examples/load-reporting-service/Dockerfile-http-server
Labels: waiting

#20327 wasm: update Wasmtime to v0.35.1.
  bazel/repository_locations.bzl
Labels: deps

#19182 TLS key log feature
  api/envoy/extensions/transport_sockets/tls/v3/tls.proto
  docs/root/version_history/current.rst
  envoy/server/transport_socket_config.h
  envoy/ssl/BUILD
  envoy/ssl/context_config.h
  envoy/upstream/cluster_manager.h
  source/common/filesystem/win32/filesystem_impl.cc
  source/common/network/BUILD
  source/common/network/cidr_range.h
  source/common/upstream/cluster_factory_impl.cc
  source/common/upstream/health_discovery_service.cc
  source/common/upstream/health_discovery_service.h
  source/extensions/transport_sockets/tls/BUILD
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/context_impl.h
  source/extensions/transport_sockets/tls/ssl_socket.cc
  source/server/listener_impl.cc
  source/server/transport_socket_config_impl.h
  test/common/upstream/eds_speed_test.cc
  test/common/upstream/eds_test.cc
  test/common/upstream/hds_test.cc
  test/common/upstream/leds_test.cc
  test/common/upstream/logical_dns_cluster_test.cc
  test/common/upstream/original_dst_cluster_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/config/utility.cc
  test/config/utility.h
  test/extensions/clusters/aggregate/cluster_test.cc
  test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
  test/extensions/clusters/redis/redis_cluster_test.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.h
  test/mocks/server/BUILD
  test/mocks/server/transport_socket_factory_context.cc
  test/mocks/server/transport_socket_factory_context.h
  test/mocks/ssl/mocks.cc
  test/mocks/ssl/mocks.h
  tools/spelling/spelling_dictionary.txt
Labels: v2-freeze

#19473 contrib: add Hyperscan matcher
  CODEOWNERS
  api/BUILD
  api/contrib/envoy/extensions/matching/input_matchers/hyperscan/v3alpha/BUILD
  api/contrib/envoy/extensions/matching/input_matchers/hyperscan/v3alpha/hyperscan.proto
  api/versioning/BUILD
  bazel/foreign_cc/BUILD
  bazel/foreign_cc/hyperscan.patch
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  contrib/all_contrib_extensions.bzl
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/hyperscan/matching/input_matchers/source/BUILD
  contrib/hyperscan/matching/input_matchers/source/config.cc
  contrib/hyperscan/matching/input_matchers/source/config.h
  contrib/hyperscan/matching/input_matchers/source/matcher.cc
  contrib/hyperscan/matching/input_matchers/source/matcher.h
  contrib/hyperscan/matching/input_matchers/test/BUILD
  contrib/hyperscan/matching/input_matchers/test/config_test.cc
  contrib/hyperscan/matching/input_matchers/test/hyperscan_speed_test.cc
  contrib/hyperscan/matching/input_matchers/test/matcher_speed_test.cc
  contrib/hyperscan/matching/input_matchers/test/matcher_test.cc
  docs/root/api-v3/config/contrib/contrib.rst
  docs/root/api-v3/config/contrib/hyperscan/hyperscan.rst
  tools/spelling/spelling_dictionary.txt
Labels: deps

#20340 local_ratelimit: allow sharing token bucket between filter chains
  api/envoy/extensions/filters/network/local_ratelimit/v3/local_rate_limit.proto
  docs/root/version_history/current.rst
  source/extensions/filters/network/local_ratelimit/BUILD
  source/extensions/filters/network/local_ratelimit/config.cc
  source/extensions/filters/network/local_ratelimit/local_ratelimit.cc
  source/extensions/filters/network/local_ratelimit/local_ratelimit.h
  test/extensions/filters/network/local_ratelimit/BUILD
  test/extensions/filters/network/local_ratelimit/local_ratelimit_fuzz_test.cc
  test/extensions/filters/network/local_ratelimit/local_ratelimit_integration_test.cc
  test/extensions/filters/network/local_ratelimit/local_ratelimit_test.cc
Labels: api

#20418 dns cache: add dns_min_refresh_rate configuration
  api/envoy/extensions/common/dynamic_forward_proxy/v3/dns_cache.proto
  docs/root/version_history/current.rst
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
  test/extensions/common/dynamic_forward_proxy/dns_cache_impl_test.cc
Labels: api

#20301 route.proto: add is_optional field to ClusterSpecifierPlugin
  api/envoy/config/route/v3/route.proto
Labels: waiting

#17395 listener: remove the peek from the listener filters
  docs/root/configuration/listeners/listener_filters/tls_inspector.rst
  docs/root/configuration/listeners/stats.rst
  docs/root/version_history/current.rst
  envoy/buffer/buffer.h
  envoy/network/BUILD
  envoy/network/filter.h
  envoy/network/listener_filter_buffer.h
  source/common/network/BUILD
  source/common/network/listener_filter_buffer_impl.cc
  source/common/network/listener_filter_buffer_impl.h
  source/extensions/filters/listener/http_inspector/http_inspector.cc
  source/extensions/filters/listener/http_inspector/http_inspector.h
  source/extensions/filters/listener/original_dst/original_dst.h
  source/extensions/filters/listener/original_src/original_src.h
  source/extensions/filters/listener/proxy_protocol/BUILD
  source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc
  source/extensions/filters/listener/proxy_protocol/proxy_protocol.h
  source/extensions/filters/listener/proxy_protocol/proxy_protocol_header.h
  source/extensions/filters/listener/tls_inspector/BUILD
  source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  source/extensions/filters/listener/tls_inspector/tls_inspector.h
  source/server/BUILD
  source/server/active_listener_base.h
  source/server/active_tcp_socket.cc
  source/server/active_tcp_socket.h
  test/common/network/BUILD
  test/common/network/listener_filter_buffer_corpus/basic
  test/common/network/listener_filter_buffer_fuzz.proto
  test/common/network/listener_filter_buffer_fuzz_test.cc
  test/common/network/listener_filter_buffer_impl_test.cc
  test/extensions/filters/listener/common/fuzz/BUILD
  test/extensions/filters/listener/common/fuzz/fuzzed_input_test.cc
  test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.cc
  test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.h
  test/extensions/filters/listener/common/fuzz/listener_filter_fuzzer.proto
  test/extensions/filters/listener/http_inspector/BUILD
  test/extensions/filters/listener/http_inspector/http_inspector_fuzz_test.cc
  test/extensions/filters/listener/http_inspector/http_inspector_test.cc
  test/extensions/filters/listener/original_src/original_src_test.cc
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_fuzz_test.cc
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_fuzz_test.proto
  test/extensions/filters/listener/proxy_protocol/proxy_protocol_test.cc
  test/extensions/filters/listener/tls_inspector/BUILD
  test/extensions/filters/listener/tls_inspector/tls_inspector_benchmark.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_fuzz_test.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_fuzz_test.proto
  test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
  test/integration/filters/address_restore_listener_filter.cc
  test/mocks/network/mocks.cc
  test/mocks/network/mocks.h
  test/per_file_coverage.sh
  test/server/BUILD
  test/server/active_internal_listener_test.cc
  test/server/active_tcp_listener_test.cc
  test/server/connection_handler_test.cc
  tools/spelling/spelling_dictionary.txt
Labels: api, v2-freeze

#20290 oauth2: disable chunked transfer for token request
  docs/root/version_history/current.rst
  source/extensions/filters/http/oauth2/oauth_client.cc
  test/extensions/filters/http/oauth2/oauth_test.cc
Labels: api
