Repository envoyproxy/envoy, pull requests merged in 2022-05, with the labels that each got.

#21069 regex: restoring regex behavior prior to runtime load
  source/common/common/regex.cc
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  source/common/runtime/runtime_impl.cc
  test/integration/stats_integration_test.cc
Labels: backport/review

#21027 DNS: allow propagating DNS responses with no records back to caller (#20890)
  changelogs/1.23.0.yaml
  source/common/runtime/runtime_features.cc
  source/extensions/network/dns_resolver/cares/BUILD
  source/extensions/network/dns_resolver/cares/dns_impl.cc
  source/extensions/network/dns_resolver/cares/dns_impl.h
  test/extensions/network/dns_resolver/cares/BUILD
  test/extensions/network/dns_resolver/cares/dns_impl_test.cc
Labels: api

#21135 build: update LLVM to 14.0.0
  .bazelrc
  .bazelversion
  .devcontainer/Dockerfile
  bazel/README.md
  bazel/foreign_cc/BUILD
  bazel/repository_locations.bzl
  bazel/setup_clang.sh
  changelogs/current.yaml
  ci/README.md
  contrib/hyperscan/matching/input_matchers/source/BUILD
  examples/wasm-cc/docker-compose-wasm.yaml
  test/common/http/header_map_impl_test.cc
  test/per_file_coverage.sh
  test/run_envoy_bazel_coverage.sh
  tools/code_format/check_format.py
Labels: deps

#21062 docs: Shift `intersphinx_mapping` to yaml
  docs/BUILD
  docs/conf.py
  docs/versions.yaml
  tools/base/requirements.in
Labels: deps

#20581 tls: fix daysUntilFirstCertExpires
  changelogs/current.yaml
  envoy/ssl/context.h
  envoy/ssl/context_manager.h
  source/extensions/transport_sockets/tls/cert_validator/cert_validator.h
  source/extensions/transport_sockets/tls/cert_validator/default_validator.cc
  source/extensions/transport_sockets/tls/cert_validator/default_validator.h
  source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.cc
  source/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/context_impl.h
  source/extensions/transport_sockets/tls/context_manager_impl.cc
  source/extensions/transport_sockets/tls/context_manager_impl.h
  source/extensions/transport_sockets/tls/utility.cc
  source/extensions/transport_sockets/tls/utility.h
  source/server/server.cc
  source/server/ssl_context_manager.cc
  test/extensions/transport_sockets/tls/cert_validator/spiffe/spiffe_validator_test.cc
  test/extensions/transport_sockets/tls/context_impl_test.cc
  test/extensions/transport_sockets/tls/utility_test.cc
  test/mocks/ssl/mocks.h
  test/server/ssl_context_manager_test.cc
Labels: api

#21179 tooling: Add project release/dev/sync actions
  RELEASES.md
  tools/project/BUILD
  tools/project/README.md
Labels: deps

#21335 deps: Bump `rules_python` -> 0.8.1
  bazel/repository_locations.bzl
Labels: deps

#20167 quic: upstream sends early data requests
  api/BUILD
  api/envoy/config/route/v3/route_components.proto
  api/envoy/extensions/early_data/v3/BUILD
  api/envoy/extensions/early_data/v3/default_early_data_policy.proto
  api/versioning/BUILD
  changelogs/current.yaml
  docs/root/api-v3/common_messages/common_messages.rst
  envoy/router/router.h
  envoy/upstream/upstream.h
  source/common/conn_pool/conn_pool_base.cc
  source/common/conn_pool/conn_pool_base.h
  source/common/http/async_client_impl.h
  source/common/http/conn_pool_grid.cc
  source/common/http/http3/conn_pool.cc
  source/common/http/http3/conn_pool.h
  source/common/http/utility.cc
  source/common/http/utility.h
  source/common/quic/envoy_quic_client_session.cc
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_server_stream.cc
  source/common/quic/envoy_quic_utils.cc
  source/common/quic/envoy_quic_utils.h
  source/common/router/BUILD
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/common/router/delegating_route_impl.cc
  source/common/router/delegating_route_impl.h
  source/common/router/router.cc
  source/common/runtime/runtime_features.cc
  source/extensions/early_data/BUILD
  source/extensions/early_data/default_early_data_policy.cc
  source/extensions/early_data/default_early_data_policy.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  test/common/conn_pool/conn_pool_base_test.cc
  test/common/router/config_impl_test.cc
  test/common/router/router_test_base.cc
  test/extensions/filters/http/alternate_protocols_cache/filter_integration_test.cc
  test/integration/multiplexed_upstream_integration_test.cc
  test/mocks/router/mocks.cc
  test/mocks/router/mocks.h
  tools/code_format/check_format.py
  tools/extensions/extensions_schema.yaml
Labels: api, v2-freeze

#21291 Empty custom header default
  api/envoy/config/core/v3/base.proto
  changelogs/current.yaml
  source/common/router/header_parser.cc
  source/common/router/header_parser.h
  test/common/router/header_formatter_test.cc
  test/integration/BUILD
  test/integration/header_integration_test.cc
Labels: v2-freeze

#21428 tls: fix daysUntilFirstCertExpires() return nil when expired
  source/server/server.cc
  test/config/integration/certs/BUILD
  test/config/integration/certs/certs.sh
  test/config/integration/certs/expired_cert.cfg
  test/config/integration/certs/expired_cert.pem
  test/config/integration/certs/expired_cert_hash.h
  test/config/integration/certs/expired_key.pem
  test/config/integration/certs/servercert_info.h
  test/integration/BUILD
  test/integration/stats_integration_test.cc
Labels: waiting

#21324 Adds QUICHE HTTP/2 test targets to CI.
  bazel/external/quiche.BUILD
Labels: waiting
