Repository envoyproxy/envoy, pull requests merged in 2022-09, with the labels that each got.

#22862 bazel: update bazel-toolchains to 5.1.2
  .bazelrc
  .devcontainer/Dockerfile
  bazel/repository_locations.bzl
  examples/wasm-cc/docker-compose-wasm.yaml
Labels: deps

#22962 repo: Dev `1.23.2`
  VERSION.txt
  changelogs/1.23.1.yaml
  changelogs/current.yaml
Labels: waiting, deps

#23140 bazel: Add temporary patch for googletest
  bazel/googletest.patch
  bazel/repositories.bzl
Labels: deps

#22673 sipproxy code optimization for performance
  contrib/sip_proxy/filters/network/source/conn_manager.cc
  contrib/sip_proxy/filters/network/source/decoder.cc
  contrib/sip_proxy/filters/network/source/decoder.h
  contrib/sip_proxy/filters/network/source/metadata.cc
  contrib/sip_proxy/filters/network/source/metadata.h
  contrib/sip_proxy/filters/network/source/router/router_impl.cc
  contrib/sip_proxy/filters/network/test/decoder_test.cc
  contrib/sip_proxy/filters/network/test/router_test.cc
Labels: api, deps

#21932 router: unified header formatters
  changelogs/current.yaml
  docs/root/configuration/http/http_conn_man/_include/header_formatters.yaml
  docs/root/configuration/http/http_conn_man/headers.rst
  envoy/http/header_evaluator.h
  source/common/grpc/async_client_impl.cc
  source/common/grpc/google_async_client_impl.cc
  source/common/local_reply/local_reply.cc
  source/common/router/BUILD
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/common/router/header_formatter.h
  source/common/router/header_parser.cc
  source/common/router/header_parser.h
  source/common/router/header_parser_utils.cc
  source/common/runtime/runtime_features.cc
  source/common/tcp_proxy/upstream.cc
  source/extensions/filters/http/ratelimit/ratelimit.cc
  test/common/local_reply/local_reply_test.cc
  test/common/router/config_impl_test.cc
  test/common/router/header_formatter_test.cc
  test/common/router/header_parser_fuzz_test.cc
  test/common/upstream/health_checker_impl_test.cc
  test/extensions/filters/common/ext_authz/ext_authz_http_impl_test.cc
  test/extensions/filters/http/local_ratelimit/config_test.cc
  test/extensions/filters/http/local_ratelimit/filter_test.cc
  tools/code_format/config.yaml
Labels: no-stalebot

#23248 doc: auto_host_rewrite works with STATIC clusters if hostname is provided
  api/envoy/api/v2/route/route_components.proto
Labels: api, v2-freeze
