Repository envoyproxy/envoy, pull requests merged in 2023-12, with the labels that each got.

#30772 contrib: add qatzip compressor
  api/BUILD
  api/contrib/envoy/extensions/compression/qatzip/compressor/v3alpha/BUILD
  api/contrib/envoy/extensions/compression/qatzip/compressor/v3alpha/qatzip.proto
  api/versioning/BUILD
  bazel/foreign_cc/BUILD
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  changelogs/current.yaml
  contrib/all_contrib_extensions.bzl
  contrib/contrib_build_config.bzl
  contrib/extensions_metadata.yaml
  contrib/qat/compression/qatzip/compressor/source/BUILD
  contrib/qat/compression/qatzip/compressor/source/config.cc
  contrib/qat/compression/qatzip/compressor/source/config.h
  contrib/qat/compression/qatzip/compressor/source/qatzip_compressor_impl.cc
  contrib/qat/compression/qatzip/compressor/source/qatzip_compressor_impl.h
  contrib/qat/compression/qatzip/compressor/test/BUILD
  contrib/qat/compression/qatzip/compressor/test/qatzip_compressor_impl_test.cc
  docs/BUILD
  docs/root/api-v3/config/contrib/qat/qat.rst
  docs/root/configuration/other_features/_include/qatzip.yaml
  docs/root/configuration/other_features/other_features.rst
  docs/root/configuration/other_features/qatzip.rst
  tools/spelling/spelling_dictionary.txt
Labels: deps

#31032 Refactoring: Collapse Http1Upstream and Http2Upstream into single HttpUpstream
  source/common/tcp_proxy/upstream.cc
  source/common/tcp_proxy/upstream.h
  test/common/tcp_proxy/upstream_test.cc
Labels: waiting

#31334 verify/examples: Expect/allow failure for locality-load-balancing
  ci/verify_examples.sh
Labels: backport/review

#30818 test: Add a LB simulation test to validate selection probabilities
  docs/root/intro/arch_overview/upstream/load_balancing/load_balancers.rst
  test/common/upstream/load_balancer_simulation_test.cc
Labels: api

#31393 bazel/deps: Shift edenhill/kakfa dep -> confluentinc
  bazel/repository_locations.bzl
  tools/dependency/BUILD
Labels: deps

#31474 deps: Bump build images/toolchains -> fd9ec00/157af2c
  .bazelrc
  .devcontainer/Dockerfile
  .github/config.yml
  bazel/repository_locations.bzl
  examples/shared/build/Dockerfile
  mobile/third_party/rbe_configs/config/BUILD
  test/common/quic/envoy_quic_client_stream_test.cc
  test/common/quic/envoy_quic_utils_test.cc
  test/common/router/config_impl_test.cc
Labels: deps

#31034 lua support cluster specifier extension
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/router/cluster_specifiers/lua/v3/BUILD
  api/envoy/extensions/router/cluster_specifiers/lua/v3/lua.proto
  api/versioning/BUILD
  bazel/repository_locations.bzl
  changelogs/current.yaml
  docs/root/api-v3/config/cluster_specifier/cluster_specifier.rst
  docs/root/api-v3/config/config.rst
  docs/root/configuration/http/cluster_specifier/cluster_specifier.rst
  docs/root/configuration/http/cluster_specifier/lua.rst
  docs/root/start/sandboxes/index.rst
  docs/root/start/sandboxes/lua-cluster-specifier.rst
  examples/lua-cluster-specifier/README.md
  examples/lua-cluster-specifier/docker-compose.yaml
  examples/lua-cluster-specifier/envoy.yaml
  examples/lua-cluster-specifier/verify.sh
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/router/cluster_specifiers/lua/BUILD
  source/extensions/router/cluster_specifiers/lua/config.cc
  source/extensions/router/cluster_specifiers/lua/config.h
  source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.cc
  source/extensions/router/cluster_specifiers/lua/lua_cluster_specifier.h
  test/extensions/router/cluster_specifiers/lua/BUILD
  test/extensions/router/cluster_specifiers/lua/config_test.cc
  test/extensions/router/cluster_specifiers/lua/lua_cluster_specifier_test.cc
Labels: deps, wait:review
