Repository envoyproxy/envoy, pull requests merged in 2023-10, with the labels that each got.

#29887 docs: Improve builds for Envoy and mobile (stamping)
  api/CONTRIBUTING.md
  bazel/BUILD
  bazel/get_workspace_status
  ci/do_ci.sh
  docs/BUILD
  docs/README.md
  docs/build.sh
  mobile/BUILD
  mobile/docs/BUILD
  mobile/docs/build.sh
  mobile/docs/conf.py
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: api, deps

#29899 ci/tools: Add tarball unpacker
  api/bazel/repository_locations.bzl
  ci/do_ci.sh
  mobile/docs/build.sh
  mobile/docs/publish.sh
  tools/tarball/BUILD
Labels: deps

#29927 ci/deps: Fix ci failure due to upstream repo issues
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#29939 [quic]fix default config for port migration
  api/envoy/config/core/v3/protocol.proto
  source/common/quic/envoy_quic_client_session.cc
  test/integration/quic_http_integration_test.cc
Labels: api

#29837 build: Move cc_proto_descriptor_library into api/
  api/bazel/api_build_system.bzl
  api/bazel/cc_proto_descriptor_library/BUILD
  api/bazel/cc_proto_descriptor_library/builddefs.bzl
  api/bazel/cc_proto_descriptor_library/create_dynamic_message.cc
  api/bazel/cc_proto_descriptor_library/create_dynamic_message.h
  api/bazel/cc_proto_descriptor_library/file_descriptor_generator.cc
  api/bazel/cc_proto_descriptor_library/file_descriptor_generator.h
  api/bazel/cc_proto_descriptor_library/file_descriptor_generator_main.cc
  api/bazel/cc_proto_descriptor_library/file_descriptor_info.cc
  api/bazel/cc_proto_descriptor_library/file_descriptor_info.h
  api/bazel/cc_proto_descriptor_library/testdata/BUILD
  api/bazel/cc_proto_descriptor_library/testdata/create_dynamic_message_test.cc
  api/bazel/cc_proto_descriptor_library/testdata/global_fallback_test.cc
  api/bazel/cc_proto_descriptor_library/testdata/test-extension.proto
  api/bazel/cc_proto_descriptor_library/testdata/test.proto
  api/bazel/cc_proto_descriptor_library/testdata/test1.proto
  api/bazel/cc_proto_descriptor_library/testdata/text_format_transcoder_test.cc
  api/bazel/cc_proto_descriptor_library/text_format_transcoder.cc
  api/bazel/cc_proto_descriptor_library/text_format_transcoder.h
  source/common/protobuf/BUILD
  test/common/protobuf/BUILD
  tools/code_format/config.yaml
  tools/spelling/spelling_dictionary.txt
Labels: deps

#29839 udp_tunneling: add udp tunneling
  api/envoy/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto
  configs/raw_udp_tunneling_http2.yaml
  docs/root/configuration/listeners/udp_filters/udp_proxy.rst
  docs/root/intro/arch_overview/http/upgrades.rst
  source/common/http/conn_manager_impl.cc
  source/common/http/header_utility.cc
  source/common/http/header_utility.h
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_server_stream.cc
  source/common/router/config_impl.cc
  source/common/router/router.cc
  source/extensions/filters/udp/udp_proxy/BUILD
  source/extensions/filters/udp/udp_proxy/config.cc
  source/extensions/filters/udp/udp_proxy/config.h
  source/extensions/filters/udp/udp_proxy/hash_policy_impl.cc
  source/extensions/filters/udp/udp_proxy/session_filters/http_capsule/BUILD
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc
  source/extensions/filters/udp/udp_proxy/udp_proxy_filter.h
  test/common/http/header_utility_test.cc
  test/extensions/filters/udp/udp_proxy/BUILD
  test/extensions/filters/udp/udp_proxy/hash_policy_impl_test.cc
  test/extensions/filters/udp/udp_proxy/mocks.h
  test/extensions/filters/udp/udp_proxy/session_filters/BUILD
  test/extensions/filters/udp/udp_proxy/session_filters/buffer_filter.h
  test/extensions/filters/udp/udp_proxy/udp_proxy_filter_test.cc
  test/integration/BUILD
  test/integration/http_protocol_integration.h
  test/integration/udp_tunneling_integration_test.cc
Labels: api

#29699 [release/1.24] repo: Release v1.24.11
  VERSION.txt
  changelogs/current.yaml
  docs/inventories/v1.24/objects.inv
  docs/versions.yaml
Labels: version-change

#30054 pr/notifier: Switch to bazel and update
  .github/actions/pr_notifier/pr_notifier.py
  .github/actions/pr_notifier/requirements.in
  .github/actions/pr_notifier/requirements.txt
  .github/dependabot.yml
  .github/workflows/pr_notifier.yml
  tools/base/requirements.in
  tools/base/requirements.txt
  tools/repo/BUILD
  tools/repo/notify.py
Labels: deps

#30094 [dev/1.27] repo: Dev v1.27.2
  VERSION.txt
  changelogs/1.27.1.yaml
  changelogs/current.yaml
Labels: version-change

#30104 [bp/1.25] Backport stack (0)
  ci/Dockerfile-envoy
Labels: release

#30105 [bp/1.26] Backport stack (0)
  ci/Dockerfile-envoy
Labels: release

#30106 [bp/1.27] Backport stack (0)
  ci/Dockerfile-envoy
Labels: release

#30108 [1.25] docs/publishing: Remove postsubmit build
  .azure-pipelines/pipelines.yml
Labels: release

#30111 [dev/1.24] repo: Dev v1.24.12
  VERSION.txt
  changelogs/1.24.11.yaml
  changelogs/current.yaml
Labels: version-change, release

#30120 ci/release: Dont run release tests/prechecks during actual release
  .azure-pipelines/env.yml
  .azure-pipelines/stage/linux.yml
  .azure-pipelines/stage/prechecks.yml
  .azure-pipelines/stages.yml
Labels: release

#30126 github/ci: Switch prechecks to pull_request_target and fix
  .github/actions/env/action.yml
  .github/workflows/_env.yml
  .github/workflows/envoy-prechecks.yml
Labels: release

#30096 repo: Sync version histories
  changelogs/1.24.11.yaml
  changelogs/1.25.10.yaml
  changelogs/1.26.5.yaml
  changelogs/1.27.1.yaml
  docs/inventories/v1.24/objects.inv
  docs/inventories/v1.25/objects.inv
  docs/inventories/v1.26/objects.inv
  docs/inventories/v1.27/objects.inv
  docs/versions.yaml
Labels: release

#30143 ci/publishing: Improve/automate release messaging
  .github/workflows/_stage_publish.yml
  .github/workflows/envoy-publish.yml
  ci/do_ci.sh
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps, release

#29932 tracing: fix Datadog span name
  changelogs/current.yaml
  source/extensions/tracers/datadog/tracer.cc
  test/extensions/tracers/datadog/tracer_test.cc
Labels: backport/review

#30154 pr/notifier: Use async lib and escape messages
  tools/base/requirements.in
  tools/base/requirements.txt
  tools/repo/notify.py
Labels: deps

#30153 ci/publishing: Assorted fixes/cleanups for gh wfs
  .github/workflows/_ci.yml
  .github/workflows/_env.yml
  .github/workflows/_stage_publish.yml
  .github/workflows/envoy-prechecks.yml
  .github/workflows/envoy-publish.yml
  .github/workflows/mobile-android_build.yml
  .github/workflows/mobile-android_tests.yml
  .github/workflows/mobile-asan.yml
  .github/workflows/mobile-cc_tests.yml
  .github/workflows/mobile-compile_time_options.yml
  .github/workflows/mobile-core.yml
  .github/workflows/mobile-coverage.yml
  .github/workflows/mobile-docs.yml
  .github/workflows/mobile-format.yml
  .github/workflows/mobile-ios_build.yml
  .github/workflows/mobile-ios_tests.yml
  .github/workflows/mobile-release.yml
  .github/workflows/mobile-release_validation.yml
  .github/workflows/mobile-tsan.yml
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#30183 ci/publishing: Bump `envoy.base.utils` and fix fail
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#29904 HCM: prevent scoped-route invalid HeaderValueExtractor key config
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  test/extensions/filters/network/common/fuzz/network_readfilter_corpus/hcm_header_value_extractor_key_name
Labels: api

#29425 build(deps): fix v8 missing include for numeric_t types
  bazel/repositories.bzl
  bazel/v8_include.patch
Labels: deps

#30211 bazel/ci: Cleanup flags and env vars
  .azure-pipelines/ci.yml
  .azure-pipelines/stage/checks.yml
  .azure-pipelines/stage/macos.yml
  .azure-pipelines/stage/prechecks.yml
  .azure-pipelines/stage/publish.yml
  .bazelrc
  ci/build_setup.sh
  ci/run_envoy_docker.sh
  ci/setup_cache.sh
  ci/upload_gcs_artifact.sh
Labels: release

#20983 deps/pip: Update `rules_python` -> 0.26.0 (+add pip-compile)
  bazel/repositories_extra.bzl
  bazel/repository_locations.bzl
  ci/do_ci.sh
  tools/base/BUILD
  tools/base/requirements.txt
Labels: no stalebot, release

#30229 build/image: Bump to `fdd65c6`
  .bazelrc
  .devcontainer/Dockerfile
  .github/workflows/_env.yml
  bazel/repository_locations.bzl
  ci/run_envoy_docker.sh
  examples/shared/build/Dockerfile
  mobile/third_party/rbe_configs/config/BUILD
Labels: backport/review, deps, release

#30122 [release/1.24] repo: Release v1.24.12
  VERSION.txt
  changelogs/current.yaml
  docs/inventories/v1.24/objects.inv
  docs/versions.yaml
Labels: version-change

#30117 [release/1.26] repo: Release v1.26.6
  VERSION.txt
  changelogs/1.24.12.yaml
  changelogs/1.25.11.yaml
  changelogs/current.yaml
  docs/inventories/v1.24/objects.inv
  docs/inventories/v1.25/objects.inv
  docs/inventories/v1.26/objects.inv
  docs/versions.yaml
Labels: version-change

#30260 [dev/1.25] repo: Dev v1.25.12
  VERSION.txt
  changelogs/1.25.11.yaml
  changelogs/current.yaml
Labels: version-change, release

#30263 [dev/1.26] repo: Dev v1.26.7
  VERSION.txt
  changelogs/1.26.6.yaml
  changelogs/current.yaml
Labels: version-change, release

#30262 ci/github: Fix app auth publishing token
  .github/workflows/_ci.yml
Labels: release

#29207 opentelemetry tracer: add OTLP/HTTP exporter
  api/envoy/config/core/v3/http_service.proto
  api/envoy/config/trace/v3/opentelemetry.proto
  changelogs/current.yaml
  docs/root/api-v3/common_messages/common_messages.rst
  source/extensions/tracers/opentelemetry/BUILD
  source/extensions/tracers/opentelemetry/grpc_trace_exporter.cc
  source/extensions/tracers/opentelemetry/grpc_trace_exporter.h
  source/extensions/tracers/opentelemetry/http_trace_exporter.cc
  source/extensions/tracers/opentelemetry/http_trace_exporter.h
  source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.cc
  source/extensions/tracers/opentelemetry/opentelemetry_tracer_impl.h
  source/extensions/tracers/opentelemetry/span_context_extractor.cc
  source/extensions/tracers/opentelemetry/span_context_extractor.h
  source/extensions/tracers/opentelemetry/trace_exporter.h
  source/extensions/tracers/opentelemetry/tracer.cc
  source/extensions/tracers/opentelemetry/tracer.h
  test/extensions/tracers/opentelemetry/BUILD
  test/extensions/tracers/opentelemetry/config_test.cc
  test/extensions/tracers/opentelemetry/http_trace_exporter_test.cc
  test/extensions/tracers/opentelemetry/opentelemetry_tracer_impl_test.cc
Labels: api

#30141 http: new disable flag to disable a filter in the filter chain by default
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  envoy/http/filter_factory.h
  envoy/router/router.h
  source/common/http/filter_chain_helper.cc
  source/common/http/filter_chain_helper.h
  source/common/http/filter_manager.h
  source/common/http/null_route_impl.h
  source/common/router/config_impl.cc
  source/common/router/config_impl.h
  source/common/router/delegating_route_impl.h
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  test/common/http/filter_chain_helper_test.cc
  test/common/router/config_impl_test.cc
  test/extensions/filters/http/header_mutation/header_mutation_integration_test.cc
  test/extensions/filters/network/http_connection_manager/config_filter_chain_test.cc
  test/mocks/router/mocks.h
Labels: api

#29776 [release/1.28] repo: Release v1.28.0
  VERSION.txt
  changelogs/current.yaml
Labels: version-change

#30312 repo: Dev v1.29.0
  VERSION.txt
  changelogs/1.28.0.yaml
  changelogs/current.yaml
Labels: version-change

#30334 Separate envoy_py_namespace to avoid cascading dependencies
  BUILD
  distribution/dockerhub/BUILD
  mobile/BUILD
  mobile/docs/BUILD
  tools/BUILD
  tools/base/envoy_python.bzl
  tools/code/BUILD
  tools/dependency/BUILD
  tools/distribution/BUILD
  tools/docs/BUILD
  tools/h3_request/BUILD
  tools/proto_format/BUILD
  tools/protodoc/BUILD
  tools/protoprint/BUILD
  tools/python/BUILD
  tools/python/namespace.bzl
  tools/repo/BUILD
Labels: backport/review

#30402 deps: Fix jq version
  bazel/dependency_imports.bzl
Labels: deps

#30411 Revert "deps: Bump `bazel_gazelle` -> 0.33.0 (#30395)"
  bazel/repository_locations.bzl
Labels: deps

#30370 deps: Bump `com_github_grpc_grpc` -> 1.59.1
  bazel/grpc.patch
  bazel/repository_locations.bzl
Labels: deps

#30377 jwt_authn: Allow to extract keys from jwt struct claims
  changelogs/current.yaml
  docs/root/configuration/http/http_filters/jwt_authn_filter.rst
  source/extensions/filters/http/jwt_authn/authenticator.cc
  test/extensions/filters/http/jwt_authn/authenticator_test.cc
  test/extensions/filters/http/jwt_authn/test_common.h
Labels: api

#30465 Make config_validation not have hot_restart panics
  source/server/config_validation/BUILD
  source/server/config_validation/server.h
Labels: backport/review

#29460 add json to metadata response side support
  api/envoy/extensions/filters/http/json_to_metadata/v3/json_to_metadata.proto
  source/extensions/filters/http/json_to_metadata/filter.cc
  source/extensions/filters/http/json_to_metadata/filter.h
  test/extensions/filters/http/json_to_metadata/config_test.cc
  test/extensions/filters/http/json_to_metadata/filter_test.cc
  test/extensions/filters/http/json_to_metadata/integration_test.cc
Labels: api

#30578 kafka: add ability to force response rewrite in broker filter
  api/contrib/envoy/extensions/filters/network/kafka_broker/v3/kafka_broker.proto
  api/envoy/config/filter/network/kafka_broker/v2alpha1/kafka_broker.proto
  contrib/kafka/filters/network/source/broker/BUILD
  contrib/kafka/filters/network/source/broker/filter.cc
  contrib/kafka/filters/network/source/broker/filter.h
  contrib/kafka/filters/network/source/broker/filter_config.h
  contrib/kafka/filters/network/source/broker/rewriter.cc
  contrib/kafka/filters/network/source/broker/rewriter.h
  contrib/kafka/filters/network/test/broker/BUILD
  contrib/kafka/filters/network/test/broker/filter_protocol_test.cc
  contrib/kafka/filters/network/test/broker/filter_unit_test.cc
  contrib/kafka/filters/network/test/broker/integration_test/envoy_config_yaml.j2
  contrib/kafka/filters/network/test/broker/rewriter_unit_test.cc
  contrib/kafka/filters/network/test/mesh/integration_test/envoy_config_yaml.j2
Labels: v2-freeze
