Repository envoyproxy/envoy, pull requests merged in 2023-11, with the labels that each got.

#30571 ext_authz: add an option to allow buffering requests on per-route filer
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
  changelogs/current.yaml
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_authz/ext_authz.h
  test/extensions/filters/http/ext_authz/ext_authz_test.cc
Labels: api

#30744 docs/comments: to distinguish between upstream HTTP filters and upstream network filters
  api/envoy/config/cluster/v3/filter.proto
  api/envoy/extensions/filters/http/router/v3/router.proto
  api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto
  changelogs/1.24.0.yaml
  changelogs/1.28.0.yaml
  docs/root/configuration/http/http_filters/cdn_loop_filter.rst
  docs/root/configuration/http/http_filters/header_mutation_filter.rst
  docs/root/configuration/http/http_filters/upstream_codec_filter.rst
  docs/root/intro/arch_overview/http/http_filters.rst
  docs/root/intro/arch_overview/upstream/upstream_filters.rst
  docs/root/intro/life_of_a_request.rst
  envoy/http/filter.h
  envoy/network/connection.h
  envoy/server/factory_context.h
  source/common/http/filter_manager.cc
  source/common/http/filter_manager.h
  source/common/router/router.h
  source/common/router/upstream_codec_filter.h
  source/common/router/upstream_request.cc
  source/common/router/upstream_request.h
  source/common/upstream/upstream_factory_context_impl.h
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/docs/upstream_filters.md
  test/common/filter/config_discovery_impl_test.cc
  test/common/upstream/cluster_manager_impl_test.cc
  test/config/utility.h
  test/extensions/transport_sockets/starttls/upstream_starttls_integration_test.cc
  test/integration/cluster_filter_integration_test.cc
  test/integration/filter_integration_test.cc
  test/integration/shadow_policy_integration_test.cc
  test/integration/tcp_proxy_integration_test.cc
  test/integration/upstream_access_log_integration_test.cc
Labels: api

#30645 kafka: make broker filter rewrite metadata, find-coordinator responses
  api/contrib/envoy/extensions/filters/network/kafka_broker/v3/kafka_broker.proto
  api/envoy/config/filter/network/kafka_broker/v2alpha1/kafka_broker.proto
  contrib/kafka/filters/network/source/broker/BUILD
  contrib/kafka/filters/network/source/broker/config.cc
  contrib/kafka/filters/network/source/broker/filter.cc
  contrib/kafka/filters/network/source/broker/filter_config.cc
  contrib/kafka/filters/network/source/broker/filter_config.h
  contrib/kafka/filters/network/source/broker/rewriter.cc
  contrib/kafka/filters/network/source/broker/rewriter.h
  contrib/kafka/filters/network/source/kafka_response.h
  contrib/kafka/filters/network/source/protocol/complex_type_template.j2
  contrib/kafka/filters/network/test/broker/BUILD
  contrib/kafka/filters/network/test/broker/filter_protocol_test.cc
  contrib/kafka/filters/network/test/broker/integration_test/envoy_config_yaml.j2
  contrib/kafka/filters/network/test/broker/integration_test/kafka_server_properties.j2
  contrib/kafka/filters/network/test/broker/mock_filter_config.h
  contrib/kafka/filters/network/test/broker/rewriter_unit_test.cc
  docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
Labels: v2-freeze

#30834 bazel: Migrate py_proto_library to `@com_github_grpc_grpc`
  api/bazel/BUILD
  api/bazel/api_build_system.bzl
  api/bazel/external_proto_deps.bzl
  api/bazel/repository_locations.bzl
  bazel/repositories.bzl
  tools/protodoc/BUILD
  tools/protoprint/BUILD
  tools/protoxform/BUILD
Labels: deps

#29803 alts: Major rewrite of the ALTS transport socket to fix concurrent connection establishment bugs (version 2).
  CODEOWNERS
  bazel/repositories.bzl
  bazel/repositories_extra.bzl
  bazel/repository_locations.bzl
  source/extensions/transport_sockets/alts/BUILD
  source/extensions/transport_sockets/alts/alts_channel_pool.cc
  source/extensions/transport_sockets/alts/alts_channel_pool.h
  source/extensions/transport_sockets/alts/alts_proxy.cc
  source/extensions/transport_sockets/alts/alts_proxy.h
  source/extensions/transport_sockets/alts/alts_tsi_handshaker.cc
  source/extensions/transport_sockets/alts/alts_tsi_handshaker.h
  source/extensions/transport_sockets/alts/config.cc
  source/extensions/transport_sockets/alts/tsi_frame_protector.cc
  source/extensions/transport_sockets/alts/tsi_handshaker.cc
  source/extensions/transport_sockets/alts/tsi_handshaker.h
  source/extensions/transport_sockets/alts/tsi_socket.cc
  source/extensions/transport_sockets/alts/tsi_socket.h
  test/extensions/transport_sockets/alts/BUILD
  test/extensions/transport_sockets/alts/alts_channel_pool_test.cc
  test/extensions/transport_sockets/alts/alts_integration_test.cc
  test/extensions/transport_sockets/alts/alts_proxy_test.cc
  test/extensions/transport_sockets/alts/alts_tsi_handshaker_test.cc
  test/extensions/transport_sockets/alts/tsi_frame_protector_test.cc
  test/extensions/transport_sockets/alts/tsi_handshaker_test.cc
  test/extensions/transport_sockets/alts/tsi_socket_test.cc
  test/test_common/status_utility.h
Labels: deps

#30919 ext_authz: fix allowed_upstream_headers_to_append doc
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
Labels: api

#28700 overload: don't print empty messages
  source/common/buffer/watermark_buffer.cc
  test/common/buffer/buffer_memory_account_test.cc
Labels: no stalebot

#31017 Revert ext_proc: send attributes #30781
  api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
  changelogs/current.yaml
  source/extensions/filters/http/ext_proc/BUILD
  source/extensions/filters/http/ext_proc/config.cc
  source/extensions/filters/http/ext_proc/config.h
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/processor_state.h
  test/extensions/filters/http/ext_proc/BUILD
  test/extensions/filters/http/ext_proc/config_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/extensions/filters/http/ext_proc/ordering_test.cc
  test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_corpus/clusterfuzz-testcase-minimized-ext_proc_unit_test_fuzz-5854655254757376
  test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_corpus/clusterfuzz-testcase-minimized-ext_proc_unit_test_fuzz-6492125776445440.fuzz
  test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc
Labels: waiting

#31061 Update QUICHE from 45374cbe5 to 7df7521b0
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
  source/common/quic/platform/BUILD
  source/common/quic/platform/quiche_flags_impl.cc
  source/common/quic/platform/quiche_mem_slice_impl.cc
  source/common/quic/platform/quiche_mem_slice_impl.h
Labels: deps
