Repository envoyproxy/envoy, pull requests merged in 2023-02, with the labels that each got.

#25270 Quiche roll 20230130190834
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
Labels: deps

#24860 Add RTDS and ADS apis to mobile engine builder
  mobile/.bazelrc
  mobile/library/cc/engine_builder.cc
  mobile/library/cc/engine_builder.h
  mobile/library/common/config/config.cc
  mobile/library/common/config/templates.h
  mobile/test/cc/unit/envoy_config_test.cc
  mobile/test/common/integration/base_client_integration_test.cc
  mobile/test/common/integration/rtds_integration_test.cc
  mobile/test/common/integration/sds_integration_test.cc
  mobile/test/common/integration/xds_integration_test.cc
  source/common/grpc/google_grpc_creds_impl.cc
  source/common/grpc/google_grpc_creds_impl.h
Labels: deps, mobile

#25363 repokitteh: Add `/milestone` command
  repokitteh.star
Labels: rk:blessed, milestone/review

#25267 Fix flaky QUIC test for deferred logging
  test/integration/quic_http_integration_test.cc
Labels: backport/review

#25406 boringssl: Patch CVE-2023-0286
  bazel/boringssl_CVE-2023-0286.patch
  bazel/repositories.bzl
  changelogs/current.yaml
Labels: deps

#25310 [backport/1.25] repo: Release `1.25.1`
  VERSION.txt
  bazel/boringssl_CVE-2023-0286.patch
  bazel/repositories.bzl
  changelogs/1.22.7.yaml
  changelogs/1.23.4.yaml
  changelogs/1.24.2.yaml
  changelogs/current.yaml
Labels: deps

#25309 [backport/1.24] repo: Release `1.24.2`
  VERSION.txt
  bazel/boringssl_CVE-2023-0286.patch
  bazel/repositories.bzl
  changelogs/1.22.7.yaml
  changelogs/1.23.4.yaml
  changelogs/current.yaml
Labels: deps

#24364 mobile: consistently compiling out admin code
  .github/workflows/android_build.yml
  .github/workflows/ios_build.yml
  .github/workflows/ios_tests.yml
  mobile/.bazelrc
Labels: no stalebot, mobile

#25298 Remove option java_generic_services from proto files
  api/contrib/envoy/extensions/filters/network/sip_proxy/tra/v3alpha/tra.proto
  api/envoy/api/v2/cds.proto
  api/envoy/api/v2/eds.proto
  api/envoy/api/v2/lds.proto
  api/envoy/api/v2/rds.proto
  api/envoy/api/v2/srds.proto
  api/envoy/service/accesslog/v2/als.proto
  api/envoy/service/accesslog/v3/als.proto
  api/envoy/service/auth/v2/external_auth.proto
  api/envoy/service/auth/v2alpha/external_auth.proto
  api/envoy/service/auth/v3/external_auth.proto
  api/envoy/service/cluster/v3/cds.proto
  api/envoy/service/discovery/v2/ads.proto
  api/envoy/service/discovery/v2/hds.proto
  api/envoy/service/discovery/v2/rtds.proto
  api/envoy/service/discovery/v2/sds.proto
  api/envoy/service/discovery/v3/ads.proto
  api/envoy/service/endpoint/v3/eds.proto
  api/envoy/service/endpoint/v3/leds.proto
  api/envoy/service/event_reporting/v2alpha/event_reporting_service.proto
  api/envoy/service/event_reporting/v3/event_reporting_service.proto
  api/envoy/service/ext_proc/v3/external_processor.proto
  api/envoy/service/extension/v3/config_discovery.proto
  api/envoy/service/health/v3/hds.proto
  api/envoy/service/listener/v3/lds.proto
  api/envoy/service/load_stats/v2/lrs.proto
  api/envoy/service/load_stats/v3/lrs.proto
  api/envoy/service/metrics/v2/metrics_service.proto
  api/envoy/service/metrics/v3/metrics_service.proto
  api/envoy/service/rate_limit_quota/v3/rlqs.proto
  api/envoy/service/ratelimit/v2/rls.proto
  api/envoy/service/ratelimit/v3/rls.proto
  api/envoy/service/route/v3/rds.proto
  api/envoy/service/route/v3/srds.proto
  api/envoy/service/runtime/v3/rtds.proto
  api/envoy/service/secret/v3/sds.proto
  api/envoy/service/status/v2/csds.proto
  api/envoy/service/status/v3/csds.proto
  api/envoy/service/tap/v2alpha/tap.proto
  api/envoy/service/tap/v3/tap.proto
  api/envoy/service/trace/v2/trace_service.proto
  api/envoy/service/trace/v3/trace_service.proto
  tools/protoprint/protoprint.py
  tools/testdata/protoxform/envoy/v2/discovery_service.proto.active_or_frozen.gold
Labels: v2-freeze

#25023 TCP Tunneling: Optionally propagate response trailers to downstream info
  api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
  changelogs/current.yaml
  envoy/tcp/upstream.h
  source/common/tcp_proxy/tcp_proxy.cc
  source/common/tcp_proxy/tcp_proxy.h
  source/common/tcp_proxy/upstream.h
  test/integration/tcp_tunneling_integration_test.cc
Labels: api

#25234 Host override in SNI dynamic forward proxy
  changelogs/current.yaml
  docs/root/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter.rst
  source/extensions/clusters/dynamic_forward_proxy/BUILD
  source/extensions/clusters/dynamic_forward_proxy/cluster.cc
  source/extensions/filters/network/sni_dynamic_forward_proxy/BUILD
  source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc
  test/extensions/clusters/dynamic_forward_proxy/BUILD
  test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
  test/extensions/filters/network/sni_dynamic_forward_proxy/BUILD
  test/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter_test.cc
Labels: api

#25453 deps: Bump `com_github_bufbuild_buf` -> 1.13.1
  api/bazel/repository_locations.bzl
  api/buf.lock
  api/buf.yaml
  test/extensions/http/header_validators/envoy_default/path_normalizer_fuzz.proto
Labels: api, v2-freeze

#25350 proxy protocol: add release note for PPv2 TLV pass through
  api/envoy/config/core/v3/proxy_protocol.proto
  api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto
  changelogs/current.yaml
Labels: api

#25492 deps: bump `rules_rust` -> `0.18.0`
  bazel/repository_locations.bzl
Labels: deps

#25493 mobile: update rules_xcodeproj to 1.1.0
  mobile/bazel/envoy_mobile_repositories.bzl
Labels: deps

#25534 mobile: add `EngineBuilder.useLegacyBuilder()` to Swift
  mobile/library/objective-c/BUILD
  mobile/library/objective-c/EnvoyConfiguration.h
  mobile/library/objective-c/EnvoyConfiguration.mm
  mobile/library/objective-c/EnvoyEngineImpl.mm
  mobile/library/swift/EngineBuilder.swift
  mobile/test/swift/EngineBuilderTests.swift
  mobile/test/swift/apps/experimental/ViewController.swift
  mobile/test/swift/integration/DirectResponseContainsHeadersMatchIntegrationTest.swift
  mobile/test/swift/integration/DirectResponseExactHeadersMatchIntegrationTest.swift
  mobile/test/swift/integration/DirectResponseExactPathMatchIntegrationTest.swift
  mobile/test/swift/integration/DirectResponseFilterMutationIntegrationTest.swift
  mobile/test/swift/integration/DirectResponsePrefixHeadersMatchIntegrationTest.swift
  mobile/test/swift/integration/DirectResponsePrefixPathMatchIntegrationTest.swift
  mobile/test/swift/integration/DirectResponseSuffixHeadersMatchIntegrationTest.swift
Labels: deps

#24848 add a sandbox for go extension
  contrib/golang/filters/http/test/test_data/dummy/BUILD
  docs/root/configuration/http/http_filters/golang_filter.rst
  docs/root/start/sandboxes/golang.rst
  docs/root/start/sandboxes/index.rst
  examples/BUILD
  examples/golang/Dockerfile-proxy
  examples/golang/README.md
  examples/golang/docker-compose-go.yaml
  examples/golang/docker-compose.yaml
  examples/golang/envoy.yaml
  examples/golang/service.py
  examples/golang/simple/BUILD
  examples/golang/simple/config.go
  examples/golang/simple/filter.go
  examples/golang/verify.sh
Labels: area/golang

#25328 Simplify function calls in base_client_integration_test.cc
  mobile/test/common/integration/base_client_integration_test.cc
  mobile/test/common/integration/base_client_integration_test.h
  mobile/test/common/integration/client_integration_test.cc
  mobile/test/common/integration/xds_integration_test.cc
  mobile/test/common/integration/xds_integration_test.h
Labels: api, deps

#25108 Make ABSL use STL types.
  bazel/abseil.patch
  bazel/cel-cpp.patch
  bazel/repositories.bzl
  envoy/common/hashable.h
  mobile/.bazelrc
  source/extensions/access_loggers/grpc/grpc_access_log_utils.cc
  source/extensions/http/header_validators/envoy_default/header_validator.cc
  test/common/api/os_sys_calls_test.cc
  test/extensions/filters/http/kill_request/kill_request_filter_integration_test.cc
Labels: no stalebot

#25719 mobile: update rules_xcodeproj to 1.2.0
  mobile/BUILD
  mobile/bazel/envoy_mobile_repositories.bzl
Labels: deps

#25711 docker: Publish images from release branches/commits
  ci/docker_ci.sh
Labels: backport/review

#25715 docs: Publish versioned docs on release branches/commits
  docs/build.sh
  docs/publish.sh
Labels: backport/review

#25739 deps: Bump `ubuntu-build-image:base` -> 458cb49ca
  .bazelrc
  .devcontainer/Dockerfile
  .github/workflows/android_build.yml
  .github/workflows/android_tests.yml
  .github/workflows/asan.yml
  .github/workflows/cc_tests.yml
  .github/workflows/core.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/perf.yml
  .github/workflows/tsan.yml
  bazel/repository_locations.bzl
  examples/shared/build/Dockerfile
  mobile/third_party/rbe_configs/config/BUILD
Labels: deps

#25659 listener: make address field required
  source/extensions/listener_managers/listener_manager/listener_manager_impl.cc
  test/extensions/listener_managers/listener_manager/listener_manager_impl_test.cc
Labels: api

#25718 assets: Publish immediately on release
  .azure-pipelines/pipelines.yml
Labels: backport/review

#25764 ci: Shift dev/release detection to env stage
  .azure-pipelines/pipelines.yml
Labels: backport/review

#25781 docker: Refactor `docker_ci.sh`
  .azure-pipelines/pipelines.yml
  ci/Dockerfile-envoy
  ci/docker_ci.sh
  ci/test/docker/linux/dev/main
  ci/test/docker/linux/dev/other
  ci/test/docker/linux/dev/release
  ci/test/docker/linux/dev/tag
  ci/test/docker/linux/nondev/main
  ci/test/docker/linux/nondev/other
  ci/test/docker/linux/nondev/release
  ci/test/docker/linux/nondev/tag
  ci/test/docker/windows/dev/main
  ci/test/docker/windows/dev/other
  ci/test/docker/windows/dev/release
  ci/test/docker/windows/dev/tag
  ci/test/docker/windows/nondev/main
  ci/test/docker/windows/nondev/other
  ci/test/docker/windows/nondev/release
  ci/test/docker/windows/nondev/tag
  ci/test_docker_ci.sh
Labels: backport/review

#25605 tooling: Shift project tools to `@envoy_repo`
  bazel/repositories.bzl
  maintainer/RELEASE.md
  tools/project/BUILD
Labels: deps

#25797 Fix changelog and API docs
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
  changelogs/current.yaml
Labels: api, backport/review
