Repository envoyproxy/envoy, pull requests merged in 2023-08, with the labels that each got.

#28748 deps: Bump `com_envoyproxy_protoc_gen_validate` -> 1.0.2
  api/bazel/repository_locations.bzl
Labels: deps

#28830 deps: Bump `com_github_curl` -> 8.2.1
  bazel/repository_locations.bzl
Labels: deps

#28016 Allow Envoy Mobile to build with Lite Protos
  .github/workflows/mobile-compile_time_options.yml
  bazel/BUILD
  bazel/envoy_mobile_defines.bzl
  bazel/envoy_select.bzl
  envoy/config/typed_config.h
  envoy/server/filter_config.h
  mobile/examples/cc/fetch_client/BUILD
  mobile/examples/cc/fetch_client/fetch_client.cc
  source/common/common/logger.cc
  source/common/config/BUILD
  source/common/config/resource_name.h
  source/common/config/utility.cc
  source/common/config/utility.h
  source/common/filter/config_discovery_impl.h
  source/common/formatter/substitution_formatter.cc
  source/common/protobuf/BUILD
  source/common/protobuf/create_reflectable_message.cc
  source/common/protobuf/protobuf.h
  source/common/protobuf/utility.cc
  source/common/protobuf/utility.h
  source/common/protobuf/visitor.cc
  source/common/rds/rds_route_config_subscription.cc
  source/common/rds/route_config_provider_manager.cc
  source/common/rds/util.cc
  source/common/router/config_impl.cc
  source/common/router/route_config_update_receiver_impl.cc
  source/exe/process_wide.cc
  source/server/api_listener_impl.cc
  test/mocks/grpc/mocks.h
  test/test_common/utility.h
  tools/code_format/config.yaml
Labels: deps

#26841 Add watermarking and buffering to cache filter
  source/extensions/filters/http/cache/BUILD
  source/extensions/filters/http/cache/cache_filter.cc
  source/extensions/filters/http/cache/cache_filter.h
  source/extensions/filters/http/cache/cache_insert_queue.cc
  source/extensions/filters/http/cache/cache_insert_queue.h
  source/extensions/filters/http/cache/http_cache.h
  test/extensions/filters/http/cache/BUILD
  test/extensions/filters/http/cache/cache_filter_integration_test.cc
  test/extensions/filters/http/cache/cache_filter_test.cc
  test/extensions/filters/http/cache/mocks.h
Labels: no stalebot

#28907 Adding API to disable ext_proc immedate response
  api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
Labels: api

#28802 coverage: Use upstream coverage collect script
  .bazelrc
  bazel/coverage/BUILD
  bazel/coverage/collect_cc_coverage.sh
  mobile/.bazelrc
  test/extensions/tracers/dynamic_ot/BUILD
  test/integration/BUILD
  test/run_envoy_bazel_coverage.sh
  test/server/config_validation/BUILD
Labels: api, deps

#28638 Refactor NullRouteImpl out of async client
  source/common/http/BUILD
  source/common/http/async_client_impl.cc
  source/common/http/async_client_impl.h
  source/common/http/null_route_impl.cc
  source/common/http/null_route_impl.h
  source/extensions/early_data/default_early_data_policy.h
  test/common/http/async_client_impl_test.cc
Labels: waiting

#28989 Implementaion of ext_proc filter disable immediate response
  api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
  changelogs/current.yaml
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  test/extensions/filters/http/ext_proc/filter_test.cc
Labels: api

#28932 kafka: upgrade dependencies to 3.5.1
  bazel/repository_locations.bzl
  contrib/kafka/filters/network/source/protocol/generator.py
  docs/root/configuration/listeners/network_filters/kafka_broker_filter.rst
  docs/root/configuration/listeners/network_filters/kafka_mesh_filter.rst
Labels: backport/review

#29068 bazel: update rules_rust
  bazel/repository_locations.bzl
Labels: backport/review

#29065 opentracing/deprecation: Minor changelog cleanup
  changelogs/current.yaml
Labels: api

#29063 tracing: Deprecate Opencensus (@1.30)
  api/envoy/config/trace/v3/opencensus.proto
  changelogs/current.yaml
  source/extensions/extensions_metadata.yaml
  test/extensions/tracers/opencensus/config_test.cc
Labels: api

#29195 RLQS: Fix CEL dep in bzl
  bazel/repository_locations.bzl
Labels: deps

#29110 Update QUICHE from 36975b02b to 229b04537
  bazel/repository_locations.bzl
Labels: waiting

#29200 fix issue 29168: add the real api.h file into the include path
  contrib/golang/filters/network/source/go/pkg/network/capi.go
  contrib/golang/router/cluster_specifier/source/go/pkg/cluster_specifier/capi_impl.go
Labels: area/golang

#29210 deps: Bump `com_github_bufbuild_buf` -> 1.26.1
  api/bazel/repository_locations.bzl
Labels: deps

#29208 deps: Bump `rules_python` -> 0.25.0
  bazel/repository_locations.bzl
Labels: deps

#29184 api: revert the private_key_provider_list and add fallback field to ProviderKeyProvider api
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
Labels: api

#28472 Add caught time stamp for http tap filter
  api/envoy/data/tap/v3/http.proto
  api/envoy/extensions/filters/http/tap/v3/tap.proto
  changelogs/current.yaml
  source/extensions/common/tap/BUILD
  source/extensions/common/tap/tap.h
  source/extensions/filters/http/tap/BUILD
  source/extensions/filters/http/tap/tap_config.h
  source/extensions/filters/http/tap/tap_config_impl.cc
  source/extensions/filters/http/tap/tap_config_impl.h
  source/extensions/filters/http/tap/tap_filter.cc
  source/extensions/filters/http/tap/tap_filter.h
  test/extensions/filters/http/tap/BUILD
  test/extensions/filters/http/tap/common.h
  test/extensions/filters/http/tap/tap_config_impl_test.cc
  test/extensions/filters/http/tap/tap_filter_integration_test.cc
  test/extensions/filters/http/tap/tap_filter_test.cc
Labels: api

#28992 RLQS: Quota based global rate limiting, part 4
  source/extensions/filters/http/rate_limit_quota/BUILD
  source/extensions/filters/http/rate_limit_quota/client.h
  source/extensions/filters/http/rate_limit_quota/client_impl.cc
  source/extensions/filters/http/rate_limit_quota/client_impl.h
  source/extensions/filters/http/rate_limit_quota/config.cc
  source/extensions/filters/http/rate_limit_quota/filter.cc
  source/extensions/filters/http/rate_limit_quota/filter.h
  source/extensions/filters/http/rate_limit_quota/matcher.h
  source/extensions/filters/http/rate_limit_quota/quota_bucket_cache.h
  test/extensions/filters/http/rate_limit_quota/BUILD
  test/extensions/filters/http/rate_limit_quota/client_test.cc
  test/extensions/filters/http/rate_limit_quota/client_test_utils.h
  test/extensions/filters/http/rate_limit_quota/filter_test.cc
  test/extensions/filters/http/rate_limit_quota/integration_test.cc
  test/extensions/filters/http/rate_limit_quota/mocks.h
  test/extensions/filters/http/rate_limit_quota/test_utils.h
Labels: waiting:any

#28874 upstream subset lb: add redundant keys support
  api/envoy/extensions/load_balancing_policies/subset/v3/subset.proto
  changelogs/current.yaml
  envoy/upstream/load_balancer_type.h
  source/common/upstream/load_balancer_impl.h
  source/extensions/load_balancing_policies/subset/subset_lb.cc
  source/extensions/load_balancing_policies/subset/subset_lb.h
  test/common/upstream/subset_lb_test.cc
  test/mocks/upstream/cluster_info.h
Labels: api

#29240 ecds: support for upstream network filter
  api/envoy/config/cluster/v3/filter.proto
  api/envoy/service/extension/v3/config_discovery.proto
  changelogs/current.yaml
  docs/root/configuration/overview/extension.rst
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  test/common/upstream/upstream_impl_test.cc
  test/integration/BUILD
  test/integration/filters/test_network_filter.cc
  test/integration/filters/test_network_filter.proto
  test/integration/upstream_network_filter_integration_test.cc
Labels: api

#29124 generic proxy: new codec callback methods to access connection
  contrib/generic_proxy/filters/network/source/interface/codec_callbacks.h
  contrib/generic_proxy/filters/network/source/proxy.cc
  contrib/generic_proxy/filters/network/source/proxy.h
  contrib/generic_proxy/filters/network/source/router/router.cc
  contrib/generic_proxy/filters/network/source/router/router.h
  contrib/generic_proxy/filters/network/test/integration_test.cc
  contrib/generic_proxy/filters/network/test/mocks/codec.h
  contrib/generic_proxy/filters/network/test/mocks/filter.h
  contrib/generic_proxy/filters/network/test/proxy_test.cc
Labels: contrib
