Repository envoyproxy/envoy, pull requests merged in 2023-04, with the labels that each got.

#26504 ci: Improve display names
  .azure-pipelines/stages.yml
Labels: ci/required

#26488 ci: Only run dependency checker when dependencies change
  .azure-pipelines/stages.yml
Labels: deps, ci/required

#26496 proto_format: Optimize and cleanup
  .azure-pipelines/stages.yml
  .bazelrc
  api/versioning/BUILD
  bazel/get_workspace_status
  ci/do_ci.sh
  tools/proto_format/BUILD
  tools/proto_format/active_protos_gen.py
  tools/proto_format/fetch_normalized_changes.py
  tools/proto_format/format_api.py
  tools/proto_format/proto_format.sh
  tools/proto_format/proto_sync.py
  tools/protoprint/BUILD
  tools/protoprint/protoprint_test.py
Labels: api, v2-freeze

#26568 ci: Fix local cache key
  .azure-pipelines/bazel.yml
  ci/run_envoy_docker.sh
  ci/setup_cache.sh
Labels: backport/review

#26521 build: moving filesystem subscription
  api/envoy/config/core/v3/config_source.proto
  changelogs/current.yaml
  docs/root/api-docs/xds_protocol.rst
  source/common/config/BUILD
  source/common/config/subscription_factory_impl.cc
  source/extensions/config_subscription/filesystem/BUILD
  source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc
  source/extensions/config_subscription/filesystem/filesystem_subscription_impl.h
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  test/common/config/BUILD
  test/common/secret/BUILD
  test/common/secret/sds_api_test.cc
  test/extensions/config_subscription/common/BUILD
  test/extensions/config_subscription/common/subscription_impl_test.cc
  test/extensions/config_subscription/filesystem/BUILD
  test/extensions/config_subscription/filesystem/filesystem_subscription_impl_test.cc
  test/extensions/config_subscription/filesystem/filesystem_subscription_test_harness.h
  test/integration/BUILD
  test/per_file_coverage.sh
  tools/code_format/config.yaml
Labels: api

#25812 metrics service: allow only histogram summaries
  api/envoy/config/metrics/v3/metrics_service.proto
  changelogs/current.yaml
  source/extensions/stat_sinks/metrics_service/BUILD
  source/extensions/stat_sinks/metrics_service/config.cc
  source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.cc
  source/extensions/stat_sinks/metrics_service/grpc_metrics_service_impl.h
  test/extensions/stats_sinks/metrics_service/grpc_metrics_service_impl_test.cc
Labels: api, v2-freeze, deps

#26625 python: Update `frozendict` dep to resolve missing
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#26649 Allow upstream to receive x-envoy-original-path headers
  changelogs/current.yaml
  source/common/http/conn_manager_utility.cc
  test/common/http/conn_manager_utility_test.cc
Labels: backport/review

#26660 deps: Bump `@com_github_curl` -> 8.0.1
  bazel/foreign_cc/curl.patch
  bazel/repository_locations.bzl
Labels: backport/review

#25849 ci: Automate creation of release branch from `main`
  .github/workflows/release_branch.yml
  ci/create_release_branch.sh
  ci/reopen_branch.sh
Labels: no stalebot

#26751 fix client sampling annotation
  api/envoy/api/v2/route/route_components.proto
  api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto
  api/envoy/config/route/v3/route_components.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
Labels: v2-freeze

#26733 router: add periodic upstream access log option
  api/envoy/extensions/filters/http/router/v3/router.proto
  docs/root/intro/arch_overview/observability/access_logging.rst
  source/common/router/router.h
  source/common/router/upstream_request.cc
  source/common/router/upstream_request.h
  test/common/router/router_upstream_log_test.cc
Labels: api

#24701 config: Make gRPC xDS retry backoff configurable
  api/envoy/config/core/v3/grpc_service.proto
  changelogs/current.yaml
  envoy/config/subscription_factory.h
  source/common/common/backoff_strategy.h
  source/common/config/BUILD
  source/common/config/datasource.cc
  source/common/config/grpc_mux_impl.cc
  source/common/config/grpc_mux_impl.h
  source/common/config/grpc_stream.h
  source/common/config/new_grpc_mux_impl.cc
  source/common/config/new_grpc_mux_impl.h
  source/common/config/subscription_factory_impl.cc
  source/common/config/utility.cc
  source/common/config/utility.h
  source/common/config/xds_mux/grpc_mux_impl.cc
  source/common/config/xds_mux/grpc_mux_impl.h
  source/common/upstream/cluster_manager_impl.cc
  test/common/config/delta_subscription_impl_test.cc
  test/common/config/delta_subscription_test_harness.h
  test/common/config/grpc_mux_impl_test.cc
  test/common/config/grpc_stream_test.cc
  test/common/config/grpc_subscription_test_harness.h
  test/common/config/new_grpc_mux_impl_test.cc
  test/common/config/utility_test.cc
  test/common/config/xds_grpc_mux_impl_test.cc
  test/extensions/clusters/eds/eds_speed_test.cc
  test/extensions/config_subscription/common/subscription_factory_impl_test.cc
Labels: api

#26799 repo: Dev v1.27.0
  .azure-pipelines/stages.yml
  VERSION.txt
  changelogs/1.26.0.yaml
  changelogs/current.yaml
Labels: version-change

#26787 fix crl docs
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
Labels: api

#26881 release: Fix asset publishing
  .azure-pipelines/stages.yml
Labels: backport/review

#26882 build: include validation listener manager in the envoy exe build
  source/exe/BUILD
Labels: backport/review

#26897 deps: Bump `rules_rust` -> 0.20.0
  bazel/repository_locations.bzl
Labels: backport/review

#26895 deps: Bump `io_bazel_rules_go` -> 0.39.1
  bazel/repository_locations.bzl
Labels: deps

#25845 deps: Bump `rules_python` -> 0.21.0
  bazel/repository_locations.bzl
Labels: no stalebot

#26620 stat_sinks: add OpenTelemetry stats sink
  CODEOWNERS
  api/BUILD
  api/bazel/external_proto_deps.bzl
  api/bazel/repositories.bzl
  api/envoy/extensions/stat_sinks/open_telemetry/v3/BUILD
  api/envoy/extensions/stat_sinks/open_telemetry/v3/open_telemetry.proto
  api/versioning/BUILD
  changelogs/current.yaml
  docs/root/api-v3/config/stat_sinks/stat_sinks.rst
  docs/root/configuration/observability/stat_sinks/open_telemetry_stat_sink.rst
  docs/root/configuration/observability/stat_sinks/stat_sinks.rst
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/stat_sinks/open_telemetry/BUILD
  source/extensions/stat_sinks/open_telemetry/config.cc
  source/extensions/stat_sinks/open_telemetry/config.h
  source/extensions/stat_sinks/open_telemetry/open_telemetry_impl.cc
  source/extensions/stat_sinks/open_telemetry/open_telemetry_impl.h
  source/extensions/stat_sinks/open_telemetry/open_telemetry_proto_descriptors.cc
  source/extensions/stat_sinks/open_telemetry/open_telemetry_proto_descriptors.h
  test/extensions/stats_sinks/open_telemetry/BUILD
  test/extensions/stats_sinks/open_telemetry/config_test.cc
  test/extensions/stats_sinks/open_telemetry/open_telemetry_impl_test.cc
  test/extensions/stats_sinks/open_telemetry/open_telemetry_integration_test.cc
  test/mocks/stats/mocks.cc
  test/mocks/stats/mocks.h
  tools/spelling/spelling_dictionary.txt
Labels: api

#26946 [1.23] repo: Release v1.23.9
  VERSION.txt
  changelogs/current.yaml
  docs/inventories/v1.23/objects.inv
  docs/versions.yaml
Labels: version-change

#26989 [release/v1.24] fips: fix Wasm extensions to comply with FIPS
  bazel/proxy_wasm_cpp_host.patch
  bazel/repositories.bzl
  changelogs/current.yaml
  source/common/version/BUILD
  source/common/version/version.cc
Labels: deps

#26572 build: moving subset lb into extensions
  CODEOWNERS
  changelogs/current.yaml
  docs/root/intro/arch_overview/upstream/load_balancing/subsets.rst
  envoy/upstream/load_balancer.h
  source/common/upstream/BUILD
  source/common/upstream/cluster_manager_impl.cc
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/load_balancing_policies/subset/BUILD
  source/extensions/load_balancing_policies/subset/config.cc
  source/extensions/load_balancing_policies/subset/config.h
  source/extensions/load_balancing_policies/subset/subset_lb.cc
  source/extensions/load_balancing_policies/subset/subset_lb.h
  test/common/upstream/BUILD
  test/common/upstream/load_balancer_benchmark.cc
  test/common/upstream/subset_lb_test.cc
  test/common/upstream/test_cluster_manager.h
  test/integration/BUILD
  test/per_file_coverage.sh
  test/server/BUILD
  tools/code_format/config.yaml
Labels: api

#26958 matcher: Add RuntimeFraction input matcher
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/matching/input_matchers/runtime_fraction/v3/BUILD
  api/envoy/extensions/matching/input_matchers/runtime_fraction/v3/runtime_fraction.proto
  api/versioning/BUILD
  changelogs/current.yaml
  docs/root/api-v3/common_messages/common_messages.rst
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/matching/input_matchers/runtime_fraction/BUILD
  source/extensions/matching/input_matchers/runtime_fraction/config.cc
  source/extensions/matching/input_matchers/runtime_fraction/config.h
  source/extensions/matching/input_matchers/runtime_fraction/matcher.h
  test/extensions/matching/input_matchers/runtime_fraction/BUILD
  test/extensions/matching/input_matchers/runtime_fraction/config_test.cc
  test/extensions/matching/input_matchers/runtime_fraction/matcher_test.cc
Labels: api

#26526 UHV: Transform H/2 extended CONNECT to H/1 upgrade
  envoy/http/header_validator.h
  envoy/upstream/upstream.h
  source/common/http/codec_client.cc
  source/common/http/codec_client.h
  source/common/http/conn_manager_impl.cc
  source/common/http/http2/codec_impl.cc
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_server_stream.cc
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/extensions/filters/network/http_connection_manager/config.h
  source/extensions/http/header_validators/envoy_default/BUILD
  source/extensions/http/header_validators/envoy_default/header_validator.cc
  source/extensions/http/header_validators/envoy_default/header_validator.h
  source/extensions/http/header_validators/envoy_default/header_validator_factory.cc
  source/extensions/http/header_validators/envoy_default/header_validator_factory.h
  source/extensions/http/header_validators/envoy_default/http1_header_validator.cc
  source/extensions/http/header_validators/envoy_default/http1_header_validator.h
  source/extensions/http/header_validators/envoy_default/http2_header_validator.cc
  source/extensions/http/header_validators/envoy_default/http2_header_validator.h
  source/extensions/http/header_validators/envoy_default/path_normalizer.h
  test/common/http/BUILD
  test/common/http/codec_client_test.cc
  test/common/http/conn_manager_impl_test_2.cc
  test/common/http/conn_manager_impl_test_base.cc
  test/common/http/conn_manager_impl_test_base.h
  test/common/http/http1/codec_impl_test.cc
  test/common/http/http2/codec_impl_test.cc
  test/extensions/filters/http/compressor/compressor_integration_tests.cc
  test/extensions/filters/network/http_connection_manager/config_test.cc
  test/extensions/http/header_validators/envoy_default/header_validator_factory_test.cc
  test/extensions/http/header_validators/envoy_default/header_validator_test.cc
  test/extensions/http/header_validators/envoy_default/http1_header_validator_test.cc
  test/extensions/http/header_validators/envoy_default/http2_header_validator_test.cc
  test/extensions/http/header_validators/envoy_default/http_common_validation_test.cc
  test/extensions/upstreams/http/config_test.cc
  test/integration/BUILD
  test/integration/fake_upstream.cc
  test/integration/fake_upstream.h
  test/integration/http_integration.cc
  test/integration/tcp_tunneling_integration_test.cc
  test/integration/utility.cc
  test/integration/utility.h
  test/integration/websocket_integration_test.cc
  test/mocks/http/header_validator.h
  test/mocks/upstream/cluster_info.cc
  test/mocks/upstream/cluster_info.h
Labels: waiting

#26502 redis filter: Add rate limit for redis client reconnection
  api/envoy/extensions/filters/network/redis_proxy/v3/redis_proxy.proto
  changelogs/current.yaml
  source/extensions/clusters/redis/redis_cluster.h
  source/extensions/filters/network/common/redis/client.h
  source/extensions/filters/network/common/redis/client_impl.cc
  source/extensions/filters/network/common/redis/client_impl.h
  source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
  source/extensions/filters/network/redis_proxy/conn_pool_impl.h
  source/extensions/health_checkers/redis/redis.h
  test/extensions/filters/network/common/redis/client_impl_test.cc
  test/extensions/filters/network/common/redis/test_utils.h
  test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
Labels: api

#26448 [balsa] Add config field to enable custom methods.
  api/envoy/config/core/v3/protocol.proto
  envoy/http/codec.h
  source/common/http/http1/balsa_parser.cc
  source/common/http/http1/balsa_parser.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/settings.cc
  source/extensions/transport_sockets/http_11_proxy/connect.h
  test/common/http/http1/codec_impl_test.cc
  test/common/http/utility_test.cc
  test/integration/protocol_integration_test.cc
Labels: api
