Repository envoyproxy/envoy, pull requests merged in 2023-03, with the labels that each got.

#25854 docker/ci: Use a mock repo for regression test
  ci/test/docker/linux/dev/main
  ci/test/docker/linux/dev/other
  ci/test/docker/linux/dev/release
  ci/test/docker/linux/dev/tag
  ci/test/docker/linux/nondev/main
  ci/test/docker/linux/nondev/other
  ci/test/docker/linux/nondev/release
  ci/test/docker/linux/nondev/tag
  ci/test/docker/windows/dev/main
  ci/test/docker/windows/dev/other
  ci/test/docker/windows/dev/release
  ci/test/docker/windows/dev/tag
  ci/test/docker/windows/nondev/main
  ci/test/docker/windows/nondev/other
  ci/test/docker/windows/nondev/release
  ci/test/docker/windows/nondev/tag
  ci/test_docker_ci.sh
Labels: backport/review

#25829 ci: Use local (named) cache for non-RBE jobs
  .azure-pipelines/bazel.yml
Labels: backport/review

#25853 repokitteh: Label version change PRs
  ci/repokitteh/modules/versionchange.star
  repokitteh.star
Labels: rk:blessed

#25572 [http] Make proxy protocol filter state optional
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_impl.cc
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/server/admin/admin.h
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/conn_manager_impl_test_2.cc
  test/common/http/conn_manager_impl_test_base.h
  test/mocks/http/mocks.h
Labels: api

#25641 FileReadToEndNotReadable keeps failing
  test/common/filesystem/filesystem_impl_test.cc
  test/per_file_coverage.sh
Labels: backport/review

#25850 ci: Fail PRs if branch VERSION.txt is not open/dev
  .azure-pipelines/pipelines.yml
Labels: backport/review

#25831 ci/cache: Add cache key exclusions (mobile/generated docs)
  .azure-pipelines/bazel.yml
Labels: backport/review

#25824 http: periodic HCM access logs
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  docs/root/configuration/observability/access_log/usage.rst
  envoy/http/filter.h
  source/common/access_log/access_log_impl.cc
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_impl.cc
  source/common/http/conn_manager_impl.h
  source/common/http/filter_manager.h
  source/extensions/common/wasm/context.cc
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/server/admin/admin.h
  test/common/access_log/access_log_impl_test.cc
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/conn_manager_impl_test_base.h
  test/extensions/access_loggers/wasm/config_test.cc
  test/extensions/filters/http/wasm/wasm_filter_test.cc
  test/mocks/http/mocks.h
  tools/spelling/spelling_dictionary.txt
Labels: api

#25170 datadog: event scheduling portion of new tracing library
  source/extensions/tracers/datadog/BUILD
  source/extensions/tracers/datadog/event_scheduler.cc
  source/extensions/tracers/datadog/event_scheduler.h
  test/extensions/tracers/datadog/BUILD
  test/extensions/tracers/datadog/event_scheduler_test.cc
  test/extensions/tracers/datadog/logger_test.cc
Labels: deps

#25785 redis: add stat for exists redis health check failure
  changelogs/current.yaml
  docs/root/configuration/upstream/health_checkers/redis.rst
  source/extensions/health_checkers/redis/redis.cc
  source/extensions/health_checkers/redis/redis.h
  test/extensions/health_checkers/redis/redis_test.cc
Labels: api

#26094 tcp_proxy: add on-upstream-connected access log flush
  api/envoy/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
  changelogs/current.yaml
  docs/root/intro/arch_overview/observability/access_logging.rst
  source/common/tcp_proxy/tcp_proxy.cc
  source/common/tcp_proxy/tcp_proxy.h
  test/common/tcp_proxy/tcp_proxy_test.cc
  test/integration/tcp_proxy_integration_test.cc
Labels: api

#26001 api: audit_log api specific to RBAC http filters
  api/envoy/config/rbac/v3/rbac.proto
  tools/extensions/extensions_schema.yaml
Labels: deps

#24345 [1.22] ci: Bump ubuntu images and disable CodeQL
  .azure-pipelines/pipelines.yml
  .github/workflows/check-deps.yml
  .github/workflows/codeql-daily.yml
  .github/workflows/codeql-push.yml
  .github/workflows/stale.yml
Labels: no stalebot

#26098 test: waiting for the upstream connection disconnected before invoke EXPECT_LOG_CONTAINS
  test/integration/listener_lds_integration_test.cc
Labels: waiting

#26023 skywalking extension create new trace context if sw8 header invalid
  changelogs/current.yaml
  source/extensions/tracers/skywalking/skywalking_tracer_impl.cc
  test/extensions/tracers/skywalking/skywalking_tracer_impl_test.cc
Labels: area/tracing

#26234 [1.22] repo: Release v1.22.9
  VERSION.txt
  docs/root/version_history/current.rst
Labels: version-change

#26307 ci: Fix project publish command/docs
  RELEASES.md
  ci/do_ci.sh
Labels: backport/review

#26341 [1.25] repo: Dev v1.25.4
  VERSION.txt
  changelogs/1.25.3.yaml
  changelogs/current.yaml
  docs/versions.yaml
Labels: version-change

#26311 Add dynamic metadata to MatchingData
  changelogs/current.yaml
  envoy/network/filter.h
  source/common/network/matching/data_impl.h
  source/extensions/listener_managers/listener_manager/filter_chain_manager_impl.cc
  test/common/ssl/matching/inputs_integration_test.cc
  test/extensions/common/matcher/trie_matcher_test.cc
  test/extensions/matching/network/common/inputs_integration_test.cc
  test/extensions/matching/network/common/inputs_test.cc
Labels: api, deps

#25775 ext-authz: send SNI in CheckRequest to the authorization server
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
  api/envoy/service/auth/v3/attribute_context.proto
  changelogs/current.yaml
  source/extensions/filters/common/ext_authz/check_request_utils.cc
  source/extensions/filters/common/ext_authz/check_request_utils.h
  source/extensions/filters/http/ext_authz/ext_authz.cc
  source/extensions/filters/http/ext_authz/ext_authz.h
  test/extensions/filters/common/ext_authz/check_request_utils_test.cc
Labels: v2-freeze

#26155 http: add on-upstream-connected access log flush
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  docs/root/intro/arch_overview/observability/access_logging.rst
  source/common/http/conn_manager_config.h
  source/common/http/conn_manager_impl.cc
  source/extensions/filters/network/http_connection_manager/config.cc
  source/extensions/filters/network/http_connection_manager/config.h
  source/server/admin/admin.h
  test/common/http/conn_manager_impl_fuzz_test.cc
  test/common/http/conn_manager_impl_test.cc
  test/common/http/conn_manager_impl_test_base.h
  test/mocks/http/mocks.h
Labels: waiting

#26196 HCM: Extend Envoy stream lifetime
  changelogs/current.yaml
  envoy/http/codec.h
  mobile/library/common/http/client.cc
  mobile/library/common/http/client.h
  source/common/http/codec_helper.h
  source/common/http/conn_manager_impl.cc
  source/common/http/conn_manager_impl.h
  source/common/http/http1/codec_impl.cc
  source/common/http/http1/codec_impl.h
  source/common/http/http2/codec_impl.cc
  source/common/http/http2/codec_impl.h
  source/common/quic/envoy_quic_client_stream.cc
  source/common/quic/envoy_quic_server_stream.cc
  source/common/runtime/runtime_features.cc
  source/common/runtime/runtime_features.h
  test/common/http/conn_manager_impl_test.cc
  test/common/http/conn_manager_impl_test_2.cc
  test/common/http/conn_manager_impl_test_base.cc
  test/common/http/conn_manager_impl_test_base.h
  test/common/http/http2/codec_impl_test.cc
  test/common/http/http2/http2_frame.h
  test/integration/buffer_accounting_integration_test.cc
  test/integration/filter_integration_test.cc
  test/integration/multiplexed_integration_test.cc
  test/integration/protocol_integration_test.cc
  test/mocks/http/stream.cc
  test/mocks/http/stream.h
  test/mocks/http/stream_encoder.cc
Labels: waiting

#26421 Revert "ci: Temporarily disable dependency checker (#26389)"
  bazel/repository_locations.bzl
  ci/do_ci.sh
Labels: deps

#26167 tls: add option to set signature algorithms
  api/envoy/extensions/transport_sockets/tls/v3/common.proto
  changelogs/current.yaml
  envoy/ssl/context_config.h
  envoy/ssl/handshaker.h
  source/extensions/transport_sockets/tls/context_config_impl.cc
  source/extensions/transport_sockets/tls/context_config_impl.h
  source/extensions/transport_sockets/tls/context_impl.cc
  source/extensions/transport_sockets/tls/context_impl.h
  test/common/quic/envoy_quic_proof_source_test.cc
  test/common/quic/envoy_quic_proof_verifier_test.cc
  test/extensions/transport_sockets/tls/handshaker_factory_test.cc
  test/extensions/transport_sockets/tls/integration/ssl_integration_test.cc
  test/extensions/transport_sockets/tls/ssl_socket_test.cc
  test/integration/ssl_utility.cc
  test/integration/ssl_utility.h
  test/mocks/ssl/mocks.cc
  test/mocks/ssl/mocks.h
Labels: api

#26195 docs: warn against shared objects
  docs/root/intro/arch_overview/advanced/data_sharing_between_filters.rst
  docs/root/intro/arch_overview/upstream/connection_pooling.rst
  envoy/stream_info/filter_state.h
  source/common/stream_info/filter_state_impl.cc
  source/common/stream_info/filter_state_impl.h
  test/common/network/connection_impl_test.cc
  test/common/network/transport_socket_options_impl_test.cc
  test/common/stream_info/filter_state_impl_test.cc
  test/extensions/clusters/dynamic_forward_proxy/cluster_test.cc
  test/extensions/io_socket/user_space/io_handle_impl_test.cc
  test/extensions/transport_sockets/internal_upstream/internal_upstream_test.cc
  test/integration/filters/header_to_filter_state.cc
Labels: waiting

#26148 datadog: Tracer portion of new tracing library
  bazel/repository_locations.bzl
  source/extensions/tracers/datadog/BUILD
  source/extensions/tracers/datadog/tracer.cc
  source/extensions/tracers/datadog/tracer.h
  test/extensions/tracers/datadog/BUILD
  test/extensions/tracers/datadog/span_test.cc
  test/extensions/tracers/datadog/tracer_test.cc
Labels: deps

#26461 bazel/ci: Speed up compression with zstd
  ci/build_setup.sh
  test/run_envoy_bazel_coverage.sh
  tools/zstd/BUILD
  tools/zstd/zstd.bzl
Labels: deps
