Repository envoyproxy/envoy, pull requests merged in 2024-02, with the labels that each got.

#31447 rbac: add uri_template for path matching
  api/envoy/config/rbac/v3/rbac.proto
  changelogs/current.yaml
  source/extensions/filters/common/rbac/BUILD
  source/extensions/filters/common/rbac/matchers.cc
  source/extensions/filters/common/rbac/matchers.h
  source/extensions/path/match/uri_template/BUILD
  test/extensions/filters/common/rbac/matchers_test.cc
  test/extensions/filters/http/rbac/rbac_filter_integration_test.cc
Labels: deps

#30622 upstream: exclude draining hosts from eds
  changelogs/current.yaml
  envoy/upstream/upstream.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/host_utility.cc
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/server/admin/clusters_handler.cc
  test/common/upstream/host_utility_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/server/admin/clusters_handler_test.cc
Labels: api

#32005 Add host rewrite config to aws lambda
  api/envoy/extensions/filters/http/aws_lambda/v3/aws_lambda.proto
  changelogs/current.yaml
  source/extensions/filters/http/aws_lambda/aws_lambda_filter.cc
  source/extensions/filters/http/aws_lambda/aws_lambda_filter.h
  source/extensions/filters/http/aws_lambda/config.cc
  test/extensions/filters/http/aws_lambda/aws_lambda_filter_test.cc
Labels: api, v2-freeze

#32200 Quiche roll 20240205122544
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
  source/common/quic/platform/BUILD
  source/common/quic/platform/quiche_flags_impl.cc
  source/common/quic/platform/quiche_flags_impl.h
Labels: deps

#32148 macos: fix linker error from CEL library
  bazel/cel-cpp.patch
Labels: backport/review

#32230 Fix unbounded heap growth in ext_authz fuzzer
  test/extensions/filters/http/ext_authz/ext_authz_fuzz_test.cc
Labels: api

#32330 repo: Dev 1.27.4
  VERSION.txt
  changelogs/current.yaml
Labels: version-change

#32329 repo: Dev v1.28.2
  VERSION.txt
  changelogs/1.28.1.yaml
  changelogs/current.yaml
Labels: version-change

#32328 repo: Dev v1.29.2
  VERSION.txt
  changelogs/1.29.1.yaml
  changelogs/current.yaml
Labels: version-change

#32331 repo: Dev 1.26.8
  VERSION.txt
  changelogs/current.yaml
Labels: version-change

#32176 ext_proc: revise service api for attributes
  api/envoy/service/ext_proc/v3/BUILD
  api/envoy/service/ext_proc/v3/external_processor.proto
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/processor_state.h
  test/extensions/filters/http/ext_proc/BUILD
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
Labels: api

#32382 contrib: Fix build for fips arm
  bazel/BUILD
  contrib/all_contrib_extensions.bzl
  contrib/exe/BUILD
Labels: backport/review

#32093 cookie session: support 0 ttl
  api/envoy/type/http/v3/cookie.proto
  changelogs/current.yaml
  source/extensions/http/stateful_session/cookie/cookie.cc
  source/extensions/http/stateful_session/cookie/cookie.h
  test/extensions/http/stateful_session/cookie/cookie_test.cc
Labels: backport/review

#32453 Revert "Configurable heap memory release rate (#30353)"
  api/envoy/config/bootstrap/v3/bootstrap.proto
  source/common/memory/BUILD
  source/common/memory/stats.cc
  source/common/memory/stats.h
  source/server/server.cc
  source/server/server.h
  test/common/memory/BUILD
  test/common/memory/memory_release_test.cc
Labels: api

#27640 tooling: generate JSON schemas from protobuf definitions
  api/bazel/repositories.bzl
  api/bazel/repository_locations.bzl
  bazel/dependency_imports.bzl
  tools/api_proto_plugin/plugin.bzl
  tools/protojsonschema/BUILD
  tools/protojsonschema/generate.bzl
  tools/protojsonschema_with_aspects/BUILD
  tools/protojsonschema_with_aspects/protojsonschema.bzl
Labels: no stalebot

#32584 quic: Fix crash bug with QUIC upstream + X.509v1 certificates
  changelogs/current.yaml
  source/common/quic/envoy_quic_proof_verifier.cc
  test/common/quic/envoy_quic_proof_verifier_test.cc
Labels: waiting
