Repository envoyproxy/envoy, pull requests merged in 2024-05, with the labels that each got.

#33849 ci/linting: Update `envoy.code.check` for yamllint
  .azure-pipelines/cached.yml
  .azure-pipelines/gpg.yml
  .azure-pipelines/pipelines.yml
  .azure-pipelines/stage/checks.yml
  .azure-pipelines/stage/linux.yml
  .azure-pipelines/stage/prechecks.yml
  .azure-pipelines/stage/publish.yml
  .azure-pipelines/stage/verify.yml
  .azure-pipelines/stages.yml
  .clang-format
  .github/workflows/codeql-daily.yml
  .github/workflows/codeql-push.yml
  .github/workflows/envoy-dependency.yml
  .github/workflows/envoy-publish.yml
  .yamllint
  SECURITY-INSIGHTS.yml
  docs/root/configuration/http/http_filters/_include/aws-lambda-filter-upstream.yaml
  docs/root/configuration/http/http_filters/_include/aws-request-signing-filter-upstream.yaml
  docs/root/configuration/http/http_filters/_include/compressor-filter.yaml
  docs/root/configuration/http/http_filters/_include/gcp-authn-filter-configuration.yaml
  docs/root/configuration/http/http_filters/_include/grpc-transcoder-filter.yaml
  docs/root/configuration/http/http_filters/_include/rate-limit-quota-filter-configuration.yaml
  docs/root/configuration/http/http_filters/compressor_filter.rst
  docs/root/configuration/http/http_filters/grpc_json_transcoder_filter.rst
  docs/root/configuration/listeners/network_filters/_include/zookeeper-filter-proxy.yaml
  docs/root/configuration/listeners/network_filters/zookeeper_proxy_filter.rst
  docs/root/configuration/other_protocols/thrift_filters/_include/payload-to-metadata-filter.yaml
  docs/root/configuration/security/_include/sds-source-example.yaml
  examples/front-proxy/envoy.yaml
  examples/grpc-bridge/docker-compose-protos.yaml
  examples/route-mirror/envoy.yaml
  examples/single-page-app/docker-compose.yml
  examples/single-page-app/envoy.yml
  examples/single-page-app/myhub/data.yml
  examples/skywalking/docker-compose.yaml
  examples/tls/envoy-https-http.yaml
  examples/tls/envoy-https-https.yaml
  examples/wasm-cc/docker-compose-wasm.yaml
  examples/websocket/envoy-wss.yaml
  examples/win32-front-proxy/front-envoy.yaml
  mobile/.pre-commit-config.yaml
  source/extensions/tracers/datadog/demo/docker-compose.yaml
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#33746 runtime: remove envoy_reloadable_features_convert_legacy_lb_config flag
  changelogs/current.yaml
  envoy/upstream/load_balancer.h
  envoy/upstream/upstream.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/subset_lb_config.h
  source/common/upstream/upstream_impl.cc
  source/common/upstream/upstream_impl.h
  source/extensions/filters/network/redis_proxy/conn_pool_impl.cc
  source/extensions/load_balancing_policies/least_request/config.cc
  source/extensions/load_balancing_policies/maglev/config.cc
  source/extensions/load_balancing_policies/ring_hash/config.cc
  source/extensions/load_balancing_policies/round_robin/config.cc
  source/extensions/load_balancing_policies/subset/config.cc
  source/extensions/load_balancing_policies/subset/config.h
  source/extensions/load_balancing_policies/subset/subset_lb.h
  test/common/upstream/cluster_manager_impl_test.cc
  test/common/upstream/upstream_impl_test.cc
  test/extensions/clusters/eds/eds_test.cc
  test/extensions/filters/network/redis_proxy/BUILD
  test/extensions/filters/network/redis_proxy/conn_pool_impl_test.cc
  test/extensions/load_balancing_policies/cluster_provided/integration_test.cc
  test/extensions/load_balancing_policies/least_request/integration_test.cc
  test/extensions/load_balancing_policies/maglev/integration_test.cc
  test/extensions/load_balancing_policies/random/integration_test.cc
  test/extensions/load_balancing_policies/ring_hash/integration_test.cc
  test/extensions/load_balancing_policies/round_robin/integration_test.cc
  test/extensions/load_balancing_policies/subset/integration_test.cc
  test/mocks/upstream/BUILD
  test/mocks/upstream/cluster_info.cc
  test/mocks/upstream/cluster_info.h
Labels: api

#34140 [balsa] Delay resetting BalsaFrame.
  changelogs/current.yaml
  source/common/http/http1/balsa_parser.cc
  source/common/http/http1/balsa_parser.h
  source/common/runtime/runtime_features.cc
  test/extensions/transport_sockets/http_11_proxy/connect_test.cc
Labels: backport/review

#34271 [1.27] ci/tooling/examples: Update vulnerable deps
  contrib/golang/filters/http/test/test_data/basic/go.mod
  contrib/golang/filters/http/test/test_data/dummy/go.mod
  contrib/golang/filters/http/test/test_data/echo/go.mod
  contrib/golang/filters/http/test/test_data/passthrough/go.mod
  contrib/golang/filters/http/test/test_data/routeconfig/go.mod
  contrib/golang/filters/network/test/test_data/go.mod
  contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod
  examples/golang-http/simple/go.mod
  examples/golang-http/simple/go.sum
  examples/golang-network/simple/go.mod
  examples/golang-network/simple/go.sum
  examples/grpc-bridge/client/requirements.in
  examples/grpc-bridge/client/requirements.txt
  examples/grpc-bridge/server/go.mod
  examples/grpc-bridge/server/go.sum
  examples/shared/python/aiohttp/requirements.in
  examples/shared/python/aiohttp/requirements.txt
  go.mod
  go.sum
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#34273 [1.28] ci/tooling/examples: Update vulnerable deps
  contrib/golang/filters/http/test/test_data/access_log/go.mod
  contrib/golang/filters/http/test/test_data/basic/go.mod
  contrib/golang/filters/http/test/test_data/buffer/go.mod
  contrib/golang/filters/http/test/test_data/dummy/go.mod
  contrib/golang/filters/http/test/test_data/echo/go.mod
  contrib/golang/filters/http/test/test_data/metric/go.mod
  contrib/golang/filters/http/test/test_data/passthrough/go.mod
  contrib/golang/filters/http/test/test_data/property/go.mod
  contrib/golang/filters/http/test/test_data/routeconfig/go.mod
  contrib/golang/filters/network/test/test_data/go.mod
  contrib/golang/router/cluster_specifier/test/test_data/simple/go.mod
  examples/golang-http/simple/go.mod
  examples/golang-http/simple/go.sum
  examples/golang-network/simple/go.mod
  examples/golang-network/simple/go.sum
  examples/grpc-bridge/client/requirements.in
  examples/grpc-bridge/client/requirements.txt
  examples/grpc-bridge/server/go.mod
  examples/grpc-bridge/server/go.sum
  examples/shared/python/aiohttp/requirements.in
  examples/shared/python/aiohttp/requirements.txt
  go.mod
  go.sum
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#34277 [1.30] ci/tooling/examples: Update vulnerable deps
  examples/grpc-bridge/client/requirements.in
  examples/grpc-bridge/client/requirements.txt
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#34144 mobile: pulling server ssl context out of mobile build
  mobile/test/common/integration/client_integration_test.cc
  mobile/test/common/integration/test_server.cc
  mobile/test/common/integration/xds_test_server.cc
  mobile/test/performance/files_em_does_not_use
  source/common/quic/BUILD
  source/common/tls/BUILD
  source/common/tls/context_config_impl.cc
  source/common/tls/context_impl.h
  source/common/tls/context_manager_impl.cc
  source/common/tls/server_context_impl.cc
  source/common/tls/server_context_impl.h
  source/common/tls/utility.cc
  source/exe/BUILD
  test/common/listener_manager/BUILD
  test/common/tls/BUILD
  test/integration/BUILD
Labels: waiting

#34328 docs: clarify Windows build status
  ci/README.md
  docs/root/_include/windows_support_ended.rst
  docs/root/faq/overview.rst
  docs/root/faq/windows/win_fips_support.rst
  docs/root/faq/windows/win_not_supported_features.rst
  docs/root/faq/windows/win_performance.rst
  docs/root/faq/windows/win_requirements.rst
  docs/root/faq/windows/win_run_as_service.rst
  docs/root/faq/windows/win_security.rst
  docs/root/start/building.rst
  docs/root/start/install.rst
  docs/root/start/quick-start/run-envoy.rst
  docs/root/start/sandboxes/setup.rst
  docs/root/start/sandboxes/win32_front_proxy.rst
Labels: backport/review

#32589 Configurable heap memory release rate
  api/envoy/config/bootstrap/v3/bootstrap.proto
  source/common/memory/BUILD
  source/common/memory/stats.cc
  source/common/memory/stats.h
  source/server/server.cc
  source/server/server.h
  test/common/memory/BUILD
  test/common/memory/memory_release_test.cc
  test/per_file_coverage.sh
  tools/spelling/spelling_dictionary.txt
Labels: api

#34359 config: Update CONNECT-UDP forwarding proxy config
  configs/proxy_connect_udp_http3_downstream.yaml
Labels: waiting

#33857 Add missing upstream string formatters
  changelogs/current.yaml
  docs/root/configuration/observability/access_log/usage.rst
  source/common/formatter/stream_info_formatter.cc
  test/common/formatter/substitution_formatter_test.cc
Labels: backport/review

#34408 Update QUICHE from 1397c94d5 to cea6f57f9
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
Labels: deps
