Repository envoyproxy/envoy, pull requests merged in 2024-01, with the labels that each got.

#31366 Datadog: fix names in Span::spawnChild
  changelogs/current.yaml
  source/extensions/tracers/datadog/span.cc
  test/extensions/tracers/datadog/BUILD
  test/extensions/tracers/datadog/naming_test.cc
  test/extensions/tracers/datadog/span_test.cc
Labels: backport/review

#31489 fix HeaderAppendAction comment
  api/envoy/config/core/v3/base.proto
Labels: api

#31669 datadog: fix span error property
  source/extensions/tracers/datadog/BUILD
  source/extensions/tracers/datadog/span.cc
  test/extensions/tracers/datadog/span_test.cc
Labels: backport/review

#31720 deps/docs: Update `sphinx` and friends
  bazel/python_dependencies.bzl
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#31788 Update QUICHE from 748880344 to 83a9e8129
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
  source/common/http/http2/metadata_decoder.cc
  source/common/quic/platform/quiche_mem_slice_impl.cc
  source/common/quic/platform/quiche_mem_slice_impl.h
Labels: deps

#31534 examples: Add single page (React) app with OAuth
  .github/dependabot.yml
  .gitignore
  docs/BUILD
  docs/root/start/sandboxes/_static/spa-cookies.png
  docs/root/start/sandboxes/_static/spa-github-oauth.png
  docs/root/start/sandboxes/_static/spa-login-github.png
  docs/root/start/sandboxes/_static/spa-login.png
  docs/root/start/sandboxes/_static/spa-resources.png
  docs/root/start/sandboxes/index.rst
  docs/root/start/sandboxes/single-page-app.rst
  examples/shared/node/Dockerfile
  examples/shared/node/scripts/build-routed.sh
  examples/single-page-app/_github-clusters.yml
  examples/single-page-app/docker-compose.yml
  examples/single-page-app/envoy.yml
  examples/single-page-app/hmac-secret.tmpl.yml
  examples/single-page-app/myhub/api.py
  examples/single-page-app/myhub/data.yml
  examples/single-page-app/myhub/images/users/envoy.svg
  examples/single-page-app/myhub/images/users/user0.png
  examples/single-page-app/myhub/images/users/user1.png
  examples/single-page-app/myhub/images/users/user2.png
  examples/single-page-app/myhub/images/users/user3.png
  examples/single-page-app/myhub/myhub.py
  examples/single-page-app/myhub/shared.py
  examples/single-page-app/secrets/myhub-token-secret.yml
  examples/single-page-app/token-secret.tmpl.yml
  examples/single-page-app/ui/.env
  examples/single-page-app/ui/.env.development
  examples/single-page-app/ui/.env.production
  examples/single-page-app/ui/.eslintrc.yml
  examples/single-page-app/ui/index.html
  examples/single-page-app/ui/package.json
  examples/single-page-app/ui/public/envoy.svg
  examples/single-page-app/ui/public/myhub.svg
  examples/single-page-app/ui/src/@types/app.d.ts
  examples/single-page-app/ui/src/App.tsx
  examples/single-page-app/ui/src/components/Auth.tsx
  examples/single-page-app/ui/src/components/Header.tsx
  examples/single-page-app/ui/src/components/Home.tsx
  examples/single-page-app/ui/src/components/Layout.tsx
  examples/single-page-app/ui/src/components/Login.tsx
  examples/single-page-app/ui/src/components/Logout.tsx
  examples/single-page-app/ui/src/components/Repos.tsx
  examples/single-page-app/ui/src/components/Resources.tsx
  examples/single-page-app/ui/src/components/User.tsx
  examples/single-page-app/ui/src/components/Users.tsx
  examples/single-page-app/ui/src/hoc.tsx
  examples/single-page-app/ui/src/main.tsx
  examples/single-page-app/ui/src/myhub.tsx
  examples/single-page-app/ui/src/providers.tsx
  examples/single-page-app/ui/src/store/reducer/index.tsx
  examples/single-page-app/ui/src/vite-env.d.ts
  examples/single-page-app/ui/tsconfig.json
  examples/single-page-app/ui/tsconfig.node.json
  examples/single-page-app/ui/vite.config.ts
  examples/single-page-app/ui/yarn.lock
  examples/single-page-app/verify.sh
  examples/single-page-app/xds/lds.tmpl.yml
Labels: deps

#31843 repo: Dev v1.30.0
  VERSION.txt
  changelogs/1.29.0.yaml
  changelogs/current.yaml
Labels: version-change

#31862 deps/build: Bump Ubuntu base image -> e6173d4
  ci/Dockerfile-envoy
Labels: backport/review

#31735 api: add ProtoMessageLogging http filter proto
  api/BUILD
  api/envoy/extensions/filters/http/proto_message_logging/v3/BUILD
  api/envoy/extensions/filters/http/proto_message_logging/v3/config.proto
  api/versioning/BUILD
Labels: api

#31897 Fix a MSAN issue in ext_authz due to max_request_bytes_ change
  source/extensions/filters/http/ext_authz/ext_authz.cc
Labels: backport/review

#31090 ext_proc: send attributes
  api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
  bazel/repositories.bzl
  bazel/repository_locations.bzl
  changelogs/current.yaml
  source/extensions/filters/http/ext_proc/BUILD
  source/extensions/filters/http/ext_proc/config.cc
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/matching_utils.cc
  source/extensions/filters/http/ext_proc/matching_utils.h
  source/extensions/filters/http/ext_proc/processor_state.h
  test/extensions/filters/http/ext_proc/BUILD
  test/extensions/filters/http/ext_proc/config_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/extensions/filters/http/ext_proc/ordering_test.cc
  test/extensions/filters/http/ext_proc/unit_test_fuzz/BUILD
  test/extensions/filters/http/ext_proc/unit_test_fuzz/ext_proc_unit_test_fuzz.cc
Labels: api, deps

#30747 ext_proc: send and receive dynamic metadata
  api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
  api/envoy/service/ext_proc/v3/external_processor.proto
  changelogs/current.yaml
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/processor_state.h
  test/extensions/filters/http/ext_proc/BUILD
  test/extensions/filters/http/ext_proc/config_test.cc
  test/extensions/filters/http/ext_proc/ext_proc_integration_test.cc
  test/extensions/filters/http/ext_proc/filter_test.cc
  test/integration/filters/BUILD
  test/integration/filters/stream_info_to_headers_filter.cc
Labels: api

#32108 quic: add option to send disable_active_migration
  api/envoy/config/listener/v3/quic_config.proto
  changelogs/current.yaml
  source/common/quic/active_quic_listener.cc
  test/integration/quic_http_integration_test.cc
Labels: api
