Repository envoyproxy/envoy, pull requests merged in 2024-12, with the labels that each got.

#37448 docs: correct some spelling mistakes and de-dupe words in ExtAuthZ
  api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto
Labels: api

#37452 Revert "build(deps): bump cryptography from 43.0.3 to 44.0.0 in /tool…
  tools/base/requirements.txt
Labels: deps

#36571 ci: Add workflow for guards deprecation and update tool
  .github/workflows/envoy-release.yml
  tools/deprecate_guards/BUILD
  tools/deprecate_guards/deprecate_guards.py
Labels: no stalebot

#37511 Update QUICHE from dbc5afc11 to c4d62db87
  bazel/external/quiche.BUILD
  bazel/repository_locations.bzl
  test/common/quic/platform/quic_platform_test.cc
Labels: deps

#37297 ext_proc http bytes tracking support
  source/extensions/filters/http/ext_proc/client.h
  source/extensions/filters/http/ext_proc/client_base.h
  source/extensions/filters/http/ext_proc/client_impl.cc
  source/extensions/filters/http/ext_proc/client_impl.h
  source/extensions/filters/http/ext_proc/ext_proc.cc
  source/extensions/filters/http/ext_proc/ext_proc.h
  source/extensions/filters/http/ext_proc/http_client/http_client_impl.cc
  source/extensions/filters/http/ext_proc/http_client/http_client_impl.h
  source/extensions/filters/http/ext_proc/processor_state.cc
  test/extensions/filters/http/ext_proc/client_test.cc
  test/extensions/filters/http/ext_proc/http_client/BUILD
  test/extensions/filters/http/ext_proc/http_client/ext_proc_http_integration_test.cc
  test/extensions/filters/http/ext_proc/logging_test_filter.cc
  test/extensions/filters/http/ext_proc/mock_server.h
Labels: waiting

#37562 [dev/1.29] repo: Dev v1.29.12
  VERSION.txt
  changelogs/1.29.11.yaml
  changelogs/current.yaml
Labels: version-change

#37563 [dev/1.30] repo: Dev v1.30.9
  VERSION.txt
  changelogs/1.30.8.yaml
  changelogs/current.yaml
Labels: version-change

#37564 [dev/1.31] repo: Dev v1.31.5
  VERSION.txt
  changelogs/1.31.4.yaml
  changelogs/current.yaml
Labels: version-change

#37565 [dev/1.32] repo: Dev v1.32.3
  VERSION.txt
  changelogs/1.32.2.yaml
  changelogs/current.yaml
Labels: version-change

#37583 docs/theme: Update sphinx-rtd theme
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#37584 docs/deps: Bump `sphinx` -> 8.1.3
  tools/base/requirements.in
  tools/base/requirements.txt
Labels: deps

#37494 rate_limit: Add time unit week
  api/envoy/service/ratelimit/v3/rls.proto
  changelogs/current.yaml
  source/extensions/filters/http/ratelimit/ratelimit_headers.cc
  test/extensions/filters/http/ratelimit/ratelimit_headers_test.cc
Labels: waiting

#37473 Fix: oauth2 state encoding
  changelogs/current.yaml
  source/extensions/filters/http/oauth2/BUILD
  source/extensions/filters/http/oauth2/config.cc
  source/extensions/filters/http/oauth2/filter.cc
  source/extensions/filters/http/oauth2/filter.h
  test/extensions/filters/http/oauth2/filter_test.cc
  test/extensions/filters/http/oauth2/oauth_integration_test.cc
Labels: deps

#37604 docs: refactor TLS Context docs to make it more reader friendly
  api/envoy/extensions/transport_sockets/tls/v3/tls.proto
Labels: api

#37418 http_filter: Add gRPC JSON reverse transcoder filter
  CODEOWNERS
  api/BUILD
  api/envoy/extensions/filters/http/grpc_json_reverse_transcoder/v3/BUILD
  api/envoy/extensions/filters/http/grpc_json_reverse_transcoder/v3/transcoder.proto
  api/versioning/BUILD
  bazel/repository_locations.bzl
  changelogs/current.yaml
  docs/root/configuration/http/http_filters/_include/grpc-json-reverse-transcoder-filter.yaml
  docs/root/configuration/http/http_filters/grpc_json_reverse_transcoder_filter.rst
  docs/root/configuration/http/http_filters/http_filters.rst
  docs/root/intro/arch_overview/other_protocols/grpc.rst
  source/extensions/extensions_build_config.bzl
  source/extensions/extensions_metadata.yaml
  source/extensions/filters/http/grpc_json_reverse_transcoder/BUILD
  source/extensions/filters/http/grpc_json_reverse_transcoder/config.cc
  source/extensions/filters/http/grpc_json_reverse_transcoder/config.h
  source/extensions/filters/http/grpc_json_reverse_transcoder/filter.cc
  source/extensions/filters/http/grpc_json_reverse_transcoder/filter.h
  source/extensions/filters/http/grpc_json_reverse_transcoder/filter_config.cc
  source/extensions/filters/http/grpc_json_reverse_transcoder/filter_config.h
  source/extensions/filters/http/grpc_json_reverse_transcoder/utils.cc
  source/extensions/filters/http/grpc_json_reverse_transcoder/utils.h
  source/extensions/filters/http/well_known_names.h
  test/extensions/filters/http/grpc_json_reverse_transcoder/BUILD
  test/extensions/filters/http/grpc_json_reverse_transcoder/config_test.cc
  test/extensions/filters/http/grpc_json_reverse_transcoder/filter_test.cc
  test/extensions/filters/http/grpc_json_reverse_transcoder/grpc_json_reverse_transcoder_integration_test.cc
  test/extensions/filters/http/grpc_json_reverse_transcoder/utils_test.cc
  test/per_file_coverage.sh
  test/proto/bookstore.proto
  tools/code_format/config.yaml
Labels: api, deps

#37542 Minor cleanup in ext_proc_http_integration_test.cc
  test/extensions/filters/http/ext_proc/http_client/ext_proc_http_integration_test.cc
Labels: api

#37579 github/ci: Use ubuntu-24.04 by default
  .github/config.yml
  .github/workflows/_check_coverage.yml
  .github/workflows/_finish.yml
  .github/workflows/_load.yml
  .github/workflows/_load_env.yml
  .github/workflows/_precheck_deps.yml
  .github/workflows/_precheck_publish.yml
  .github/workflows/_publish_build.yml
  .github/workflows/_publish_publish.yml
  .github/workflows/_publish_verify.yml
  .github/workflows/_request.yml
  .github/workflows/_request_cache_bazel.yml
  .github/workflows/_request_cache_docker.yml
  .github/workflows/_request_checks.yml
  .github/workflows/command.yml
  .github/workflows/envoy-dependency.yml
  .github/workflows/envoy-release.yml
  .github/workflows/envoy-sync.yml
  .github/workflows/pr_notifier.yml
  .github/workflows/scorecard.yml
  .github/workflows/stale.yml
Labels: workflows:untested

#37731 github/ci: Workaround release branch Docker cache issue
  .github/workflows/_run.yml
Labels: workflows:untested

#37735 [1.32] github/ci: Set default runner in config
  .github/config.yml
Labels: workflows:untested

#37737 [1.30] github/ci: Set default runner in config
  .github/config.yml
Labels: workflows:untested

#37738 [1.31] github/ci: Set default runner in config
  .github/config.yml
Labels: workflows:untested

#37739 [1.29] github/ci: Set default runner in config
  .github/config.yml
Labels: workflows:untested

#37726 mobile/android: Remove `rules_android_ndk` patch
  mobile/bazel/envoy_mobile_repositories.bzl
  mobile/bazel/rules_android_ndk.patch
  mobile/ci/linux_ci_setup.sh
Labels: deps

#37745 [dev/1.30] repo: Dev v1.30.10
  VERSION.txt
  changelogs/1.30.9.yaml
  changelogs/current.yaml
Labels: version-change

#37744 [dev/1.29] repo: Dev v1.29.13
  VERSION.txt
  changelogs/1.29.12.yaml
  changelogs/current.yaml
Labels: version-change

#37747 [dev/1.32] repo: Dev v1.32.4
  VERSION.txt
  changelogs/1.32.3.yaml
  changelogs/current.yaml
Labels: version-change

#37746 [dev/1.31] repo: Dev v1.31.6
  VERSION.txt
  changelogs/1.31.5.yaml
  changelogs/current.yaml
Labels: version-change

#37578 bazel: Bump -> 7.1.2
  .bazelrc
  .bazelversion
  .github/workflows/_check_coverage.yml
  bazel/repository_locations.bzl
  mobile/.bazelrc
  mobile/BUILD
  mobile/bazel/framework_imports_extractor.bzl
  tools/proto_format/format_api.py
Labels: workflows:untested

#37788 docs: clarify the docs on runtime_filter
  api/envoy/config/accesslog/v3/accesslog.proto
Labels: v2-freeze
