Repository envoyproxy/envoy, pull requests merged in 2024-10, with the labels that each got.

#36439 http: allow runtime override of default for max response headers kb
  api/envoy/config/core/v3/protocol.proto
  api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto
  changelogs/current.yaml
  envoy/http/codec.h
  source/common/upstream/upstream_impl.cc
  test/common/upstream/upstream_impl_test.cc
  test/extensions/filters/network/http_connection_manager/config_test.cc
Labels: api

#35894 Add support for multiple formats of ORCA headers.
  source/common/orca/BUILD
  source/common/orca/orca_parser.cc
  source/common/orca/orca_parser.h
  test/common/orca/orca_parser_test.cc
Labels: deps

#36312 getaddrinfo: Add trace info in the DNS resolution details
  changelogs/current.yaml
  envoy/network/BUILD
  envoy/network/dns.h
  mobile/library/cc/engine_builder.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc
  source/extensions/common/dynamic_forward_proxy/dns_cache_impl.h
  source/extensions/network/dns_resolver/apple/apple_dns_impl.h
  source/extensions/network/dns_resolver/cares/dns_impl.h
  source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.cc
  source/extensions/network/dns_resolver/getaddrinfo/getaddrinfo.h
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/test_resolver.cc
  test/extensions/filters/http/dynamic_forward_proxy/test_resolver.h
  test/extensions/network/dns_resolver/getaddrinfo/getaddrinfo_test.cc
  test/mocks/network/mocks.h
Labels: api

#36522 1.28 backport: ci: change googleurl dep (#36515)
  bazel/repository_locations.bzl
Labels: deps

#36540 deps: Fix (renamed) ipp-crypto repo hash
  bazel/repository_locations.bzl
Labels: deps

#35848 dynamic_forward_proxy: fix sub_cluster_confg stuck with warm up due to DFPCluster removed
  changelogs/current.yaml
  envoy/upstream/cluster_manager.h
  source/common/runtime/runtime_features.cc
  source/common/upstream/cluster_manager_impl.cc
  source/common/upstream/cluster_manager_impl.h
  source/extensions/clusters/dynamic_forward_proxy/cluster.cc
  source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc
  test/common/upstream/cds_api_impl_test.cc
  test/common/upstream/cluster_manager_impl_test.cc
  test/extensions/filters/http/dynamic_forward_proxy/proxy_filter_integration_test.cc
  test/mocks/upstream/cluster_manager.h
Labels: api

#36576 [bp/1.29] deps: Fix (renamed) ipp-crypto repo hash (#36540)
  bazel/repository_locations.bzl
Labels: deps

#36597 repo: Release v1.32.0
  VERSION.txt
  changelogs/current.yaml
Labels: version-change

#36598 release: kick off 1.33
  VERSION.txt
  changelogs/1.32.0.yaml
  changelogs/current.yaml
Labels: version-change

#36369 tls: support for ECDSA P-384 and P-521 certificates
  changelogs/current.yaml
  docs/root/intro/arch_overview/security/ssl.rst
  envoy/ssl/handshaker.h
  source/common/quic/quic_server_transport_socket_factory.cc
  source/common/quic/quic_server_transport_socket_factory.h
  source/common/tls/context_impl.cc
  source/common/tls/context_impl.h
  source/common/tls/default_tls_certificate_selector.cc
  source/common/tls/default_tls_certificate_selector.h
  source/common/tls/server_context_impl.cc
  source/common/tls/server_context_impl.h
  test/common/quic/envoy_quic_proof_source_test.cc
  test/common/tls/BUILD
  test/common/tls/cert_selector/async_cert_selector.h
  test/common/tls/context_impl_test.cc
  test/common/tls/integration/ssl_integration_test.cc
  test/common/tls/integration/ssl_integration_test_base.cc
  test/common/tls/integration/ssl_integration_test_base.h
  test/common/tls/server_context_impl_test.cc
  test/common/tls/test_data/README.md
  test/common/tls/test_data/certs.sh
  test/common/tls/test_data/selfsigned_ecdsa_p521_cert.pem
  test/common/tls/test_data/selfsigned_ecdsa_p521_cert_info.h
  test/common/tls/test_data/selfsigned_ecdsa_p521_key.pem
  test/common/tls/test_data/selfsigned_secp224r1_cert.pem
  test/common/tls/test_data/selfsigned_secp224r1_cert_info.h
  test/common/tls/test_data/selfsigned_secp224r1_key.pem
  test/common/tls/tls_certificate_selector_test.cc
  test/config/integration/certs/certs.sh
  test/config/integration/certs/server_ecdsa_ocsp_resp.der
  test/config/integration/certs/server_ecdsa_p384_ocsp_resp.der
  test/config/integration/certs/server_ecdsa_p384cert.pem
  test/config/integration/certs/server_ecdsa_p384cert_hash.h
  test/config/integration/certs/server_ecdsa_p384key.pem
  test/config/integration/certs/server_ecdsa_p521_ocsp_resp.der
  test/config/integration/certs/server_ecdsa_p521cert.pem
  test/config/integration/certs/server_ecdsa_p521cert_hash.h
  test/config/integration/certs/server_ecdsa_p521key.pem
  test/config/integration/certs/server_ecdsacert.pem
  test/config/integration/certs/server_ecdsacert_hash.h
  test/config/integration/certs/server_ecdsakey.pem
  test/config/utility.cc
  test/config/utility.h
  test/integration/ssl_utility.cc
  test/integration/ssl_utility.h
Labels: deps

#36644 bazel/repo: Fix version export (for apt archive)
  bazel/BUILD
  bazel/generate_release_hash.sh
  bazel/repo.bzl
  tools/code/BUILD
Labels: deps

#36282 [bp/1.29] tools/python: Update all deps
  tools/base/requirements.txt
Labels: waiting

#36748 deps: Switch hosting server for kafka server binary download
  bazel/repository_locations.bzl
Labels: deps

#36900 bazel/deps: Fix `rules_license` setup
  bazel/repositories.bzl
Labels: deps

#36894 [dev/1.30] repo: Dev v1.30.8
  VERSION.txt
  changelogs/1.30.7.yaml
  changelogs/current.yaml
Labels: version-change

#36893 [dev/1.29] repo: Dev v1.29.11
  VERSION.txt
  changelogs/1.29.10.yaml
  changelogs/current.yaml
Labels: version-change

#36918 [dev/1.32] repo: Dev v1.32.2
  VERSION.txt
  changelogs/1.32.1.yaml
  changelogs/current.yaml
Labels: version-change
