Repository envoyproxy/envoy, pull requests merged in 2025-09, with the labels that each got.

#40943 stats: fix a bug where the prometheus name of ssl certificate stats are wrong (#40891)
  changelogs/current.yaml
  source/common/config/well_known_names.cc
  test/common/stats/tag_extractor_impl_test.cc
Labels: backport/review

#40529 Add dynamic metadata for TLS inspector filter errors
  changelogs/current.yaml
  docs/root/configuration/advanced/well_known_dynamic_metadata.rst
  docs/root/configuration/listeners/listener_filters/tls_inspector.rst
  source/extensions/filters/listener/tls_inspector/tls_inspector.cc
  source/extensions/filters/listener/tls_inspector/tls_inspector.h
  test/extensions/filters/listener/tls_inspector/tls_inspector_integration_test.cc
  test/extensions/filters/listener/tls_inspector/tls_inspector_test.cc
Labels: api, deps

#40259 filter: add setForceImmediateLocalReply() method to force an immediate local reply
  source/common/http/filter_manager.cc
  source/common/runtime/runtime_features.cc
Labels: waiting

#40971 repo: Dev v1.32.12
  VERSION.txt
  changelogs/1.32.11.yaml
  changelogs/current.yaml
Labels: version-change

#40973 repo: Dev v1.34.7
  VERSION.txt
  changelogs/1.34.6.yaml
  changelogs/current.yaml
Labels: version-change

#40974 repo: Dev v1.35.3
  VERSION.txt
  changelogs/1.35.2.yaml
  changelogs/current.yaml
Labels: version-change

#40661 dynamic_modules: add support for user-defined metrics
  source/extensions/dynamic_modules/abi.h
  source/extensions/dynamic_modules/abi_version.h
  source/extensions/dynamic_modules/sdk/rust/src/lib.rs
  source/extensions/filters/http/dynamic_modules/abi_impl.cc
  source/extensions/filters/http/dynamic_modules/factory.cc
  source/extensions/filters/http/dynamic_modules/filter.h
  source/extensions/filters/http/dynamic_modules/filter_config.cc
  source/extensions/filters/http/dynamic_modules/filter_config.h
  test/extensions/dynamic_modules/http/BUILD
  test/extensions/dynamic_modules/http/abi_impl_test.cc
  test/extensions/dynamic_modules/http/factory_test.cc
  test/extensions/dynamic_modules/http/filter_test.cc
  test/extensions/dynamic_modules/test_data/c/no_http_filter_new.c
  test/extensions/dynamic_modules/test_data/rust/http.rs
Labels: waiting

#40904 Backport: router: fix a bug where header mutations may not be processed properly (#40856)
  changelogs/current.yaml
  source/common/router/router.cc
  test/common/router/router_test.cc
  test/integration/header_integration_test.cc
Labels: backport/review

#41160 deps: revert cryptography module update
  tools/base/requirements.txt
Labels: deps

#41221 github/ci: Disable scheduled CVE checker
  .github/workflows/envoy-dependency.yml
Labels: workflows:untested

#41229 github/ci: Give coverage a bit more diskspace
  .github/workflows/_check_coverage.yml
Labels: workflows:untested

#41226 Fix for broken FIPS builds
  bazel/repositories.bzl
Labels: deps

#40919 server: enhance skip_deprecated_logs for deprecated runtime key warning
  source/server/options_impl.cc
  source/server/server.cc
  test/server/options_impl_test.cc
  test/server/server_test.cc
  test/server/test_data/server/deprecated_runtime_key_bootstrap.yaml
Labels: waiting

#41270 tools/dependency: Add CVE fetcher
  .github/workflows/_cve_fetch.yml
  .github/workflows/envoy-cve.yml
  .gitignore
  tools/dependency/BUILD
  tools/dependency/cve_fetch.py
  tools/dependency/cve_update.sh
Labels: workflows:untested

#41261 tools/dependency: Add CVE scanner pipeline
  .github/workflows/_cve_scan.yml
  .github/workflows/envoy-cve.yml
  tools/dependency/BUILD
  tools/dependency/ansi.jq
  tools/dependency/cve_matcher.jq
  tools/dependency/cve_report.jq
  tools/dependency/cve_test.sh
  tools/dependency/cve_utils.jq
  tools/dependency/cves.sh
  tools/dependency/version.jq
Labels: workflows:untested
